apiVersion: v1
kind: Secret
metadata:
  name: triliovault-keystone
type: Opaque
data:  
  OS_AUTH_URL:
  OS_REGION_NAME:
  OS_INTERFACE:
  OS_PROJECT_DOMAIN_NAME:
  OS_PROJECT_NAME:
  OS_USER_DOMAIN_NAME:
  OS_USERNAME:
  OS_PASSWORD:
  OS_DEFAULT_DOMAIN:
