FROM openstackhelm/nova:2023.2-ubuntu_jammy
MAINTAINER shyam.biradar@trilio.io

LABEL name="trilio/trilio-datamover-api" \
      version="6.0.1" \
      release="6.0" \
      vendor="TrilioData" \
      summary="TrilioData Datamover API" \
      description="TrilioData Datamover API container image for OpenStack Helm Bobcat 2023.2" \
      org.opencontainers.image.authors="shyam.biradar@trilio.io"

ARG PROJECT_DIR=trilio-datamover
ARG OPENSTACK_REPO=cloud-archive:bobcat

# Switch to root user
USER root

# Install prerequisite packages
RUN set -ex \
    && apt-get update && apt-get -y install \
        apt-utils \
        software-properties-common \
        ca-certificates \
        vim \
        less \
        iputils-ping

# Install datamover API package
COPY trilio.list /etc/apt/sources.list.d/

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC

RUN set -ex \
    && apt-add-repository ${OPENSTACK_REPO} && apt-get update -y && apt-get -y --allow-unauthenticated install \
       python3-dmapi

# Create necessary directories and set permissions
RUN mkdir -p /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR} \
    && chown -R dmapi.dmapi /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR}

# Add license directory
RUN mkdir /licenses

# Switch to dmapi user for further operations
USER dmapi
