FROM openstackhelm/nova:2023.1-ubuntu_jammy
MAINTAINER  kanav.malhotra@trilio.io
LABEL name="trilio/triliovault-datamover-api" \
      version="6.1.0" \
      release="6.1" \
      vendor="TrilioData" \
      summary="TrilioData Datamover API" \
      description="TrilioData Datamover API container image" \
      org.opencontainers.image.authors="kanav.malhotra@trilio.io"

ARG PROJECT_DIR=triliovault-datamover
ARG OPENSTACK_REPO=cloud-archive:antelope


# Switch to root and install a custom RPM, etc.
USER root

# Set noninteractive mode to avoid timezone selection prompts
ENV DEBIAN_FRONTEND=noninteractive 

# Install the pre-requisite packages 
RUN set -ex \
    && apt-get update && apt-get -y install \
        apt-utils \
        software-properties-common \
        ca-certificates \
        vim  \
        curl \
        less  \
        iputils-ping \
        python3-openstackclient \
    && curl -o /usr/local/bin/rabbitmqadmin https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/v3.12.x/deps/rabbitmq_management/bin/rabbitmqadmin \
    && chmod +x /usr/local/bin/rabbitmqadmin

# Install datamover packages
COPY trilio.list /etc/apt/sources.list.d/


ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC
RUN set -ex \
    && apt-add-repository ${OPENSTACK_REPO} && apt-get update -y && apt-get -y --allow-unauthenticated install \
       python3-dmapi 

RUN mkdir -p /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR} \
    && chown -R dmapi.dmapi /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR}

# Copy license file
RUN mkdir /licenses

# Become dmapi user for further operations
USER dmapi
