FROM openstackhelm/nova:2024.1-ubuntu_jammy

MAINTAINER  shyam.biradar@trilio.io
LABEL name="trilio/trilio-datamover-api" \
      version="6.1.2" \
      release="6.1" \
      vendor="TrilioData" \
      summary="TrilioData Datamover API" \
      description="TrilioData Datamover API container image" \
      org.opencontainers.image.authors="kanav.malhotra@trilio.io"

ARG PROJECT_DIR=trilio-datamover
ARG OPENSTACK_REPO=cloud-archive:caracal


# Switch to root and install a custom RPM, etc.
USER root

# Install the pre-requisite packages 
RUN set -ex \
    && apt-get update && apt-get -y install \
        apt-utils \
        software-properties-common \
        ca-certificates  \
        vim  \
        less  \
        iputils-ping

# Install datamover packages
COPY trilio.list /etc/apt/sources.list.d/


ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC
RUN set -ex \
    && apt-add-repository ${OPENSTACK_REPO} && apt-get update -y && apt-get -y --allow-unauthenticated install \
       python3-dmapi python3-trilio-dms python3-nova 

RUN mkdir -p /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR} \
    && chown -R dmapi.dmapi /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR}

# Copy license file
RUN mkdir /licenses

# Become dmapi user for further operations
USER dmapi
