# Use Ubuntu Jammy as the base image
FROM docker.io/ubuntu:jammy

LABEL name="trilio/triliovault-wlm" \
      version="6.1.0" \
      release="6.1" \
      vendor="TrilioData" \
      summary="TrilioData Workload Manager" \
      description="TrilioData Workload Manager container image" \
      org.opencontainers.image.authors="kanav.malhotra@trilio.io"

USER root

ARG PROJECT_DIR=triliovault-wlm
ARG TRILIO_MOUNT_DIR=/var/lib/trilio/triliovault-mounts
ARG UID=42424
ARG GID=42424
ARG OPENSTACK_REPO=cloud-archive:bobcat

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC \
    LIBGUESTFS_DEBUG=1 \
    LIBGUESTFS_TRACE=1

RUN set -ex \
    && apt-get update && apt-get -y install \
        apt-utils \
        software-properties-common \
        ca-certificates \
        curl \
        make \
        openssl \
        libssl3 \
        gnupg \
        gcc \
        python3 \
        python3-pip \
        python3-retrying \
        sudo \
        nfs-common \
        vim \
        less \
        iputils-ping \
        libxslt-dev \
        swig \
        udev \
        parted \
        apache2 \
        ntfs-3g \
        python3-pyvmomi \
        python3-editor \
        python3-pymongo \
        python3-cryptography \
        pacemaker-remote \
        resource-agents \
        pcs \
        mysql-client \
        python3-dev \
        patch \
    && pip3 --no-cache-dir install --upgrade pip \
    && pip3 install igraph namedatomiclock \
    && apt-get clean -y

# Install Trilio repo
COPY ./trilio.list /etc/apt/sources.list.d/

RUN set -ex \
    && apt-add-repository ${OPENSTACK_REPO} \
    && PYTHON_LIB_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") \
    && mkdir -p "${PYTHON_LIB_PATH}/wlmfs_appliance" \
    && apt-get update && apt-get -y upgrade \
    && apt-get -y install tzdata \
    && apt-get install -y nova-common

# Configuring the Nova user
COPY nova_userid.sh /opt/${PROJECT_DIR}/
# Split thesse since all three are dependent operations
RUN sed -i -r "s/^(user_id=).*/\1${UID}/" /opt/${PROJECT_DIR}/nova_userid.sh \
    && sed -i -r "s/^(group_id=).*/\1${GID}/" /opt/${PROJECT_DIR}/nova_userid.sh

RUN /opt/${PROJECT_DIR}/nova_userid.sh

RUN apt install -y python3-neutronclient python3-glanceclient python3-attr python3-workloadmgrclient \
    && apt-get install -y workloadmgr fuse3 python3-s3-fuse-plugin --allow-unauthenticated \
    && mkdir -p /var/trilio ${TRILIO_MOUNT_DIR} /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR} /etc/triliovault-object-store/ \
    && chmod 777 /var/trilio \
    && chmod 777 ${TRILIO_MOUNT_DIR}

RUN chown -R nova.nova /var/trilio /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR} /var/triliovault ${TRILIO_MOUNT_DIR} /etc/triliovault-object-store/
RUN usermod -aG disk nova

ADD log-rotate-conf /etc/logrotate.d/workloadmgr-api.conf

COPY auditlog.py /usr/lib/python3/dist-packages/workloadmgr/auditlog.py
RUN chmod 644 /usr/lib/python3/dist-packages/workloadmgr/auditlog.py

RUN curl -o /usr/local/bin/rabbitmqadmin https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/v3.12.x/deps/rabbitmq_management/bin/rabbitmqadmin && chmod +x /usr/local/bin/rabbitmqadmin

RUN mkdir -p /licenses
COPY licensing.txt /licenses

USER nova
