---
options:
  python-version:
    type: int
    default: 3
    description: THIS OPTION IS DEPRECATED AND HAS NO EFFECT
  triliovault-pkg-source:
    type: string
    default: "deb [trusted=yes] https://apt.fury.io/triliodata-4-2/ /"
    description: Repository address of triliovault packages
  trilio-backup-targets:
    type: string
    description: |
      List Trilio Backup Targets
    default": >
        [
          {
            "backup-target-name": "S3_BT1",
            "backup-target-type": "s3",
            "is-default": true,
            "s3-type": "amazon_s3",
            "s3-access-key": "<ACCESS_KEY>",
            "s3-secret-key": "<SECRET_KEY>",
            "s3-region-name": "us-west-2",
            "s3-bucket": "<BUCKET_NAME>",
            "s3-endpoint-url": "",
            "s3-signature-version": "default",
            "s3-auth-version": "DEFAULT",
            "s3-ssl-enabled": true,
            "s3-ssl-verify": true,
            "s3-self-signed-cert": false,
            "s3-ssl-ca_cert": "",
            "s3-bucket-object-lock-enabled": false
          },
          {
            "backup-target-name": "S3_BT1",
            "backup-target-type": "s3",
            "is-default": true,
            "s3-type": "other_s3",
            "s3-access-key": "<ACCESS_KEY>",
            "s3-secret-key": "<SECRET_KEY>",
            "s3-region-name": "us-east-1",
            "s3-bucket": "<BUCKET_NAME>",
            "s3-endpoint-url": "<CEPH_S3_URL>",
            "s3-signature-version": "default",
            "s3-auth-version": "DEFAULT",
            "s3-ssl-enabled": true,
            "s3-ssl-verify": true,
            "s3-self-signed-cert": true,
            "s3-ssl-ca_cert": "-----BEGIN CERTIFICATE-----
        SHKLLEffdfdfdfggdgdrrasbgnYJKoZIhvcNAQELBQAwgZAxCzAJBgNVBAYTAklO
        MQswCQYDVQQIDAJNSDENMAsGA1UEBwwEUFVORTEPMA0GA1UECgwGVFJJTElPMQsw
        CQYDVQQLDAJJVDEaMBgGA1UEAwwRKi50cmlsaW9kYXRhLmRlbW8xKzApBgkqhkiG
        9w0BCQEWHHBnqewlrodhssaksldgffegegrgmfvvdkcsoejdHhcNMTkwNjEzMDkx
        -----END CERTIFICATE-----",
            "s3-bucket-object-lock-enabled": false
          },
          {
            "backup-target-name": "NFS_BT3",
            "backup-target-type": "nfs",
            "is-default": false,
            "nfs-shares": "<NFS_SHARE>",
            "nfs-options": "nolock,soft,timeo=600,intr,lookupcache=none,nfsvers=3,retrans=10"
          }
        ]
  is-vmware-migration-enabled:
    type: boolean
    default: False
    description: If VMWare to OpenStack migration feature enabled or not 
  vault_s3_max_pool_connections:
    type: int
    default: 500
    description: |
      The maximum number of connections to keep in a connection pool
      This option is ignored if Trilio is before 4.2
  bucket_object_lock:
    type: boolean
    default: False
    description: |
      S3 bucket object locking is enabled
      This option is ignored if Trilio is before 4.2
  use_manifest_suffix:
    type: boolean
    default: False
    description: |
      To preserve backward compatibility, set this to False. When set to False,
      s3fuse creates manifest file names without suffix
      This option is ignored if Trilio is before 4.2
  # General configuration
  tv-datamover-max-uploads-pending:
    type: int
    default: 3
    description: max_uploads_pending parameter value in /etc/triliovault-datamover/triliovault-datamover.conf
  tv-datamover-max-commit-pending:
    type: int
    default: 3
    description: max_commit_pending parameter value in /etc/triliovault-datamover/triliovault-datamover.conf
  tv-datamover-qemu-agent-ping-timeout:
    type: int
    default: 30
    description: qemu_agent_ping_timeout parameter value in /etc/triliovault-datamover/triliovault-datamover.conf
  cinder-http-retries:
    type: int
    default: 10
    description: |
      This is the number of times datamover will try to connect to
      the cinder service.
      This option is ignored if Trilio is before 4.1.94
  multipath-rescan-opts:
    type: string
    default: "-m,-s,-u"
    description: |
      Provide comma separated options which are needed to form a rescan command like
      this; rescanscsi-bus.sh -m -s -u
      This option is ignored if Trilio is before 4.2
  nbd-timeout:
    type: int
    default: 10
    description: |
      Amount of time, in seconds, to wait for NBD device start up
      This option is ignored if Trilio is before 4.2
  # DROP
  tv-data-dir:
    type: string
    default: /var/triliovault-mounts
    description: TrilioVault data mount point
  tv-data-dir-old:
    type: string
    default: /var/triliovault
    description: Old TrilioVault data dir
