---
options:
  python-version:
    type: int
    default: 3
    description: THIS OPTION IS DEPRECATED AND HAS NO EFFECT
  triliovault-pkg-source:
    type: string
    default: "deb [trusted=yes] https://apt.fury.io/triliodata-4-2/ /"
    description: Repository address of triliovault packages
  is-vmware-migration-enabled:
    type: boolean
    default: False
    description: If VMWare to OpenStack migration feature enabled or not
  # General configuration
  tv-datamover-max-uploads-pending:
    type: int
    default: 3
    description: max_uploads_pending parameter value in /etc/triliovault-datamover/triliovault-datamover.conf
  tv-datamover-max-commit-pending:
    type: int
    default: 3
    description: max_commit_pending parameter value in /etc/triliovault-datamover/triliovault-datamover.conf
  tv-datamover-qemu-agent-ping-timeout:
    type: int
    default: 30
    description: qemu_agent_ping_timeout parameter value in /etc/triliovault-datamover/triliovault-datamover.conf
  cinder-http-retries:
    type: int
    default: 10
    description: |
      This is the number of times datamover will try to connect to
      the cinder service.
      This option is ignored if Trilio is before 4.1.94
  multipath-rescan-opts:
    type: string
    default: "-m,-s,-u"
    description: |
      Provide comma separated options which are needed to form a rescan command like
      this; rescanscsi-bus.sh -m -s -u
      This option is ignored if Trilio is before 4.2
  nbd-timeout:
    type: int
    default: 10
    description: |
      Amount of time, in seconds, to wait for NBD device start up
      This option is ignored if Trilio is before 4.2
  # DROP
  tv-data-dir:
    type: string
    default: /var/triliovault-mounts
    description: TrilioVault data mount point
  tv-data-dir-old:
    type: string
    default: /var/triliovault
    description: Old TrilioVault data dir
