FROM docker.io/tripleowallaby/openstack-horizon:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="tripleo/openstack-nova-compute-triliodata" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.2.0" \
      release="4.2" \
      summary="TripleO Wallaby Horizon plugin TrilioData Datamover" \
      description="TripleO Wallaby Horizon plugin TrilioData Datamover"

##Install datamover packages
RUN dnf clean all
ADD trilio.repo delorean-component-tripleo.repo /etc/yum.repos.d/
RUN rpm -ivh centos-stream-repos-8-4.el8.noarch.rpm centos-gpg-keys-8-4.el8.noarch.rpm
RUN rm -f centos-gpg-keys-8-4.el8.noarch.rpm centos-gpg-keys-8-4.el8.noarch.rpm
RUN dnf install -y python3-tripleo-repos
RUN tripleo-repos -b wallaby current ceph

RUN dnf install python3-tvault-horizon-plugin-el8 -y
RUN rm /etc/yum.repos.d/trilio.repo
RUN dnf clean all

##Move necessary files
ADD usr/share/openstack-dashboard/openstack_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
ADD usr/share/openstack-dashboard/openstack_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/
RUN /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/share/openstack-dashboard/manage.py compress --force


## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
