FROM registry.redhat.io/rhosp-rhel8/openstack-horizon:16.0
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp16/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.0.0" \
      release="4.0" \
      summary="Red Hat OpenStack Platform 16.0 horizon TrilioData TrilioVault Horizon Plugin" \
      description="Red Hat OpenStack Platform 16.0 horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf install python3-tvault-horizon-plugin python3-workloadmgrclient-el8 -y
RUN rm /etc/yum.repos.d/trilio.repo

##Move necessary files
ADD usr/share/openstack-dashboard/openstack_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
ADD usr/share/openstack-dashboard/openstack_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
