FROM docker.io/tripleotraincentos8/centos-binary-horizon:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp16/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.0.0" \
      release="4.0" \
      summary="Red Hat OpenStack Platform 16.0 horizon TrilioData TrilioVault Horizon Plugin" \
      description="Red Hat OpenStack Platform 16.0 horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
RUN dnf clean all
ADD trilio.repo delorean-component-tripleo.repo /etc/yum.repos.d/
RUN dnf install -y python3-tripleo-repos
RUN tripleo-repos -b train --no-stream current && tripleo-repos -b train --no-stream current ceph

RUN dnf install python3-tvault-horizon-plugin-el8 -y
RUN rm /etc/yum.repos.d/trilio.repo
RUN dnf clean all

##Move necessary files
ADD usr/share/openstack-dashboard/openstack_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
ADD usr/share/openstack-dashboard/openstack_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/
RUN /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/share/openstack-dashboard/manage.py compress --force


## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
