FROM registry.redhat.io/rhosp-rhel8/openstack-horizon:16.2
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="Red Hat OpenStack Platform 16.2 horizon TrilioData TrilioVault Horizon Plugin" \
      description="Red Hat OpenStack Platform 16.2 horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf install python3-tvault-horizon-plugin-el8 -y
RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical
RUN rm /etc/yum.repos.d/trilio.repo

##Move necessary files
ADD usr/share/openstack-dashboard/openstack_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
ADD usr/share/openstack-dashboard/openstack_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/
RUN /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/share/openstack-dashboard/manage.py compress --force

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses