heat_template_version: 2016-10-14

description: >
  Trilio service configured with Puppet

parameters:
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  Debug:
    default: ''
    description: Set to True to enable debugging on all services.
    type: string
  DefaultPasswords:
    default: {}
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NFSShares:
    default: ''
    description: Provide comma separated list of NFS shares to use as backup target
    type: string
  TvaultApplianceIP:
    default: ''
    description: Provide TrilioVault appliance IP address which is reachable from all compute nodes and controller node
    type: string
  NfsOptions:
    default: ''
    description: Provide any non-default NFS options for the NFS share
    type: string
  NovaConfFile:
    default: ''
    description: The location of the nova configuration file
    type: string
  NovaDistConfFile:
    default: ''
    description: The location of the default nova distribution configuration file
    type: string
  NovaComputeFiltersFile:
    default: ''
    description: The location of the nova compute filters file
    type: string

outputs:
  role_data:
    description: Role data for the trilio role.
    value:
      service_name: tvault-contego
      config_settings:
        trilio::nfs_shares: {get_param: NFSShares} 
        trilio::tvault_appliance_ip: {get_param: TvaultApplianceIP }
        trilio::nfs_options: {get_param: NfsOptions}
        trilio::nova_conf_file: {get_param: NovaConfFile}
        trilio::nova_dist_conf_file: {get_param: NovaDistConfFile}
        trilio::nova_compute_filters_file: {get_param: NovaComputeFiltersFile}
      step_config: |
        include ::tripleo::profile::base::trilio::contego
