FROM mirantis.azurecr.io/openstack/horizon:victoria-focal-20220528051016
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio-horizon-helm" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="5.0.0" \
      release="5.0" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Mirantis OpenStack on Kubernetes"

## Become root
USER root

ARG fury_repo="triliodata-dev-stable-5-0/"


#Eg. fury_repo : triliodata-dev-5-0
RUN source /var/lib/openstack/bin/activate && export PIP_EXTRA_INDEX_URL=https://pypi.fury.io/${fury_repo} && pip install tvault-horizon-plugin workloadmgrclient contegoclient --no-deps


RUN cp /var/lib/openstack/lib/python3.8/site-packages/trilio_dashboard/local/enabled/*.py /var/lib/openstack/lib/python3.8/site-packages/openstack_dashboard/enabled/
RUN cp /var/lib/openstack/lib/python3.8/site-packages/trilio_dashboard/templatetags/*.py /var/lib/openstack/lib/python3.8/site-packages/openstack_dashboard/templatetags/
RUN cp /var/lib/openstack/lib/python3.8/site-packages/trilio_dashboard/local/local_settings.d/_001_trilio_dashboard.py /var/lib/openstack/lib/python3.8/site-packages/openstack_dashboard/local/local_settings.d/

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses

## Become horizon user
USER horizon

