# TODO(TVAULT-7745): base tag taken from the MOSK 26.2 release artifacts list; the image
# could not be pulled without Mirantis registry credentials, so confirm the python3.12
# site-packages layout below during the MOSK 26.2 lab run.
FROM mirantis.azurecr.io/openstack/horizon:gazpacho-noble-20260901110644

LABEL name="triliovault-horizon-helm" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="6.3.0" \
      release="6.3" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Mirantis OpenStack on Kubernetes 26.2 (OpenStack Gazpacho)"

## Become root
USER root
ARG TRILIO_PIP_INDEX_URL="DEFAULT"
RUN source /var/lib/openstack/bin/activate && pip install pytz && export PIP_EXTRA_INDEX_URL=${TRILIO_PIP_INDEX_URL} && pip install tvault-horizon-plugin workloadmgrclient contegoclient --no-deps

RUN cp /var/lib/openstack/lib/python3.12/site-packages/trilio_dashboard/local/enabled/*.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/enabled/ && \
    cp /var/lib/openstack/lib/python3.12/site-packages/trilio_dashboard/templatetags/*.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/templatetags/ && \
    cp /var/lib/openstack/lib/python3.12/site-packages/trilio_dashboard/local/local_settings.d/_001_trilio_dashboard.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/local/local_settings.d/

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses

## Become horizon user
USER horizon
