FROM docker.io/openstackhelm/horizon:2023.1-ubuntu_jammy
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="ubuntu-binary-trilio-horizon-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="6.1.0" \
      release="6.1" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Openstack Helm"

ARG OPENSTACK_REPO=cloud-archive:antelope

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC

# Install pre-requisite packages 
RUN set -ex \
    && apt-get update && apt-get -y install \
        software-properties-common apt-utils vim less iputils-ping

# Install datamover packages
ADD trilio.list /etc/apt/sources.list.d/

RUN apt update -y  && \
    apt-add-repository ${OPENSTACK_REPO} && \
    apt-get install -y python3-tvault-horizon-plugin python3-workloadmgrclient --allow-unauthenticated

##Move necessary files
RUN cp /usr/lib/python3/dist-packages/trilio_dashboard/local/enabled/*.py /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/ \
    && cp /usr/lib/python3/dist-packages/trilio_dashboard/templatetags/*.py /usr/share/openstack-dashboard/openstack_dashboard/templatetags/
RUN /usr/bin/python3 /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/bin/python3 /usr/share/openstack-dashboard/manage.py compress --force

# Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
