FROM mirantis.azurecr.io/openstack/horizon:epoxy-noble-20250905110850

LABEL name="triliovault-horizon-helm" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="6.1.7" \
      release="6.1" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Mirantis OpenStack on Kubernetes 25.2"

## Become root
USER root
ARG TRILIO_PIP_INDEX_URL="DEFAULT"
RUN source /var/lib/openstack/bin/activate && pip install pytz && export PIP_EXTRA_INDEX_URL=${TRILIO_PIP_INDEX_URL} && pip install tvault-horizon-plugin workloadmgrclient contegoclient --no-deps

RUN cp /var/lib/openstack/lib/python3.12/site-packages/trilio_dashboard/local/enabled/*.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/enabled/ && \
    cp /var/lib/openstack/lib/python3.12/site-packages/trilio_dashboard/templatetags/*.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/templatetags/ && \
    cp /var/lib/openstack/lib/python3.12/site-packages/trilio_dashboard/local/local_settings.d/_001_trilio_dashboard.py /var/lib/openstack/lib/python3.12/site-packages/openstack_dashboard/local/local_settings.d/

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses

## Become horizon user
USER horizon
