---
- include_tasks: check-containers-kolla-docker.yml
  when: triliovault_kolla_module == 'kolla_docker'

- include_tasks: check-containers-kolla-container.yml
  when: triliovault_kolla_module == 'kolla_container'
