---
- name: "Configure haproxy for {{ project_name }}"
  import_role:
    name: haproxy-config
  vars:
    project_services: "{{ triliovault_services }}"
  tags: always

- name: Register triliovault users in ProxySQL mysql_users
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: community.mysql.mysql_query
    module_args:
      login_host: "{{ database_address }}"
      login_port: "{{ proxysql_admin_port | default(6032) }}"
      login_user: "cluster_admin"
      login_password: "{{ proxysql_cluster_password }}"
      query:
        - "DELETE FROM mysql_users WHERE username='{{ item.database_user }}'"
        - "INSERT INTO mysql_users (username, password, default_hostgroup, max_connections) VALUES ('{{ item.database_user }}', '{{ item.database_password }}', {{ triliovault_database_shard_id | default(0) }}, 200)"
  with_items: "{{ triliovault_db_details }}"
  run_once: True
  delegate_to: "{{ groups[item.group_name][0] }}"
  when:
    - enable_proxysql | default(false) | bool
    - openstack_release not in ['zed', '2023.1', '2023.2', '2024.1']

- name: Load and save triliovault ProxySQL users to runtime
  become: true
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: community.mysql.mysql_query
    module_args:
      login_host: "{{ database_address }}"
      login_port: "{{ proxysql_admin_port | default(6032) }}"
      login_user: "cluster_admin"
      login_password: "{{ proxysql_cluster_password }}"
      query:
        - "LOAD MYSQL USERS TO RUNTIME"
        - "SAVE MYSQL USERS TO DISK"
  run_once: True
  delegate_to: "{{ groups['triliovault-datamover-api'][0] }}"
  when:
    - enable_proxysql | default(false) | bool
    - openstack_release not in ['zed', '2023.1', '2023.2', '2024.1']
