---
- name: "Configure haproxy for {{ project_name }}"
  import_role:
    name: haproxy-config
  vars:
    project_services: "{{ triliovault_services }}"
  tags: always

- name: "Configure proxysql for {{ project_name }}"
  import_role:
    name: proxysql-config
  when:
    - enable_proxysql | default(false) | bool
    - openstack_release not in ['zed', '2023.1', '2023.2', '2024.1']
  notify:
    - Restart proxysql container
