FROM quay.io/openstack.kolla/horizon:zed-rocky-9
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="centos-binary-trilio-horizon-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="5.1.0" \
      release="5.1" \
      type="source" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Kolla-ansible deployed OpenStack on centos platform"

##Install datamover packages
ARG TRILIO_FURY_REPO="DEFAULT"
#Eg. TRILIO_FURY_REPO : triliodata-dev-5-0
RUN export PIP_EXTRA_INDEX_URL=https://pypi.fury.io/${TRILIO_FURY_REPO} && pip install tvault-horizon-plugin workloadmgrclient contegoclient --no-deps
RUN cp /var/lib/kolla/venv/lib/python3.9/site-packages/dashboards/local/enabled/*.py /var/lib/kolla/venv/lib/python3.9/site-packages/openstack_dashboard/enabled/
RUN cp /var/lib/kolla/venv/lib/python3.9/site-packages/dashboards/templatetags/*.py /var/lib/kolla/venv/lib/python3.9/site-packages/openstack_dashboard/templatetags/

#
RUN /var/lib/kolla/venv/bin/python /var/lib/kolla/venv/bin/manage.py collectstatic --clear --noinput
RUN /var/lib/kolla/venv/bin/python /var/lib/kolla/venv/bin/manage.py compress --force


## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
