FROM quay.io/openstack.kolla/centos-binary-horizon:yoga
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="centos-binary-trilio-horizon-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.2.0" \
      release="4.2" \
      type="binary" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Kolla-ansible deployed OpenStack on centos platform"

##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf config-manager --set-enabled epel 
RUN dnf install python3-tvault-horizon-plugin-el8 -y
RUN rm /etc/yum.repos.d/trilio.repo
RUN dnf config-manager --set-disabled epel

##Move necessary files
RUN cp /usr/lib/python3.6/site-packages/trilio_dashboard/local/enabled/*.py /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/ \
    && cp /usr/lib/python3.6/site-packages/trilio_dashboard/templatetags/*.py /usr/share/openstack-dashboard/openstack_dashboard/templatetags/
RUN /usr/bin/python3 /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/bin/python3 /usr/share/openstack-dashboard/manage.py compress --force


## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
