FROM quay.io/openstack.kolla/ubuntu-source-horizon:yoga
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="ubuntu-binary-trilio-horizon-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.2.0" \
      release="4.2" \
      type="source" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Kolla-ansible deployed OpenStack on ubuntu platform"

##Install datamover packages
ARG PIP_INDEX_URL="DEFAULT"

RUN export PIP_EXTRA_INDEX_URL=${PIP_INDEX_URL} && pip install tvault-horizon-plugin workloadmgrclient contegoclient --no-deps
RUN cp /var/lib/kolla/venv/lib/python3.8/site-packages/trilio_dashboard/local/enabled/*.py /var/lib/kolla/venv/lib/python3.8/site-packages/openstack_dashboard/enabled/
RUN cp /var/lib/kolla/venv/lib/python3.8/site-packages/trilio_dashboard/templatetags/*.py /var/lib/kolla/venv/lib/python3.8/site-packages/openstack_dashboard/templatetags/


#
RUN /var/lib/kolla/venv/bin/python /var/lib/kolla/venv/bin/manage.py collectstatic --clear --noinput
RUN /var/lib/kolla/venv/bin/python /var/lib/kolla/venv/bin/manage.py compress --force


## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses