apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  namespace: openshift-user-workload-monitoring
  labels:
    app: kube-state-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  namespaceSelector:
    matchNames:
      - openshift-user-workload-monitoring
  endpoints:
    - port: http-metrics
      interval: 30s
      honorLabels: true
