- name: Restart triliovault-datamover
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: "edpm_triliovault-datamover.service"

- name: Restart triliovault-object-store
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: "edpm_triliovault-object-store-{{ item.backup_target_name }}.service"
  loop: "{{ triliovault_backup_targets | selectattr('backup_target_type', 'equalto', 's3') | list }}"
