FROM registry.access.redhat.com/rhosp13/openstack-nova-api
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp13/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.0.0" \
      release="4.0" \
      summary="Red Hat OpenStack Platform 14.0 nova-api TrilioData trilio-datamover-api" \
      description="Red Hat OpenStack Platform 14.0 nova-api TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN yum install dmapi -y
RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical

RUN  rm -f /etc/yum.repos.d/trilio.repo
RUN usermod -a -G kolla dmapi

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi
