FROM registry.redhat.io/rhosp-rhel8/openstack-base:16.1
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp16/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="5.0.X" \
      release="5.0" \
      summary="Red Hat OpenStack Platform 16.1 nova-api TrilioData trilio-datamover-api" \
      description="Red Hat OpenStack Platform 16.1 nova-api TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf clean all && dnf config-manager \
  --enable openstack-16.1-for-rhel-8-x86_64-rpms \
  --enable fast-datapath-for-rhel-8-x86_64-rpms
RUN dnf -y install python3-nova python3-retrying
RUN dnf install python3-dmapi -y
RUN dnf -y update-minimal --security --sec-severity=Important --sec-severity=Critical
RUN  rm -f /etc/yum.repos.d/trilio.repo
RUN usermod -a -G kolla dmapi

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi
