#!/bin/bash
set -e
TVAULT_VERSION=$1
TVAULT_IPADDRESS=$2

juju-log "GOT the value from config $TVAULT_VERSION"
juju-log "GOT the value from config $TVAULT_IPADDRESS"

pip install --no-deps http://$TVAULT_IPADDRESS:8081/packages/python-workloadmgrclient-$TVAULT_VERSION &> /dev/null
        if [ $? -eq 0 ]; then
                juju-log "Installing python-workloadmgrclient-$TVAULT_VERSION"
        else
                juju-log "Error : pip install http://$TVAULT_IPADDRESS:8081/packages/python-workloadmgrclient-$TVAULT_VERSION"
                exit 1
        fi
        pip install --no-deps http://$TVAULT_IPADDRESS:8081/packages/tvault-horizon-plugin-$TVAULT_VERSION &> /dev/null
        if [ $? -eq 0 ]; then
                juju-log "Installing tvault-horizon-plugin-$TVAULT_VERSION"
        else
                juju-log "Error : pip install  http://$TVAULT_IPADDRESS:8081/packages/tvault-horizon-plugin-$TVAULT_VERSION"
                exit 1
        fi

juju-log "Workloadmanager client and tvault-horizon-plugin are installed....configure is next step"
        

###write tvault_panel.py and tvault_panel_group.py
HORIZON=/usr/share/openstack-dashboard

cat > $HORIZON/openstack_dashboard/local/enabled/tvault_panel_group.py <<-EOF
from django.utils.translation import ugettext_lazy as _
# The slug of the panel group to be added to HORIZON_CONFIG. Required.
PANEL_GROUP = 'backups'
# The display name of the PANEL_GROUP. Required.
PANEL_GROUP_NAME = _('Backups')
# The slug of the dashboard the PANEL_GROUP associated with. Required.
PANEL_GROUP_DASHBOARD = 'project'
EOF
cat > $HORIZON/openstack_dashboard/local/enabled/tvault_admin_panel_group.py <<-EOF
from django.utils.translation import ugettext_lazy as _
# The slug of the panel group to be added to HORIZON_CONFIG. Required.
PANEL_GROUP = 'backups-admin'
# The display name of the PANEL_GROUP. Required.
PANEL_GROUP_NAME = _('Backups-Admin')
# The slug of the dashboard the PANEL_GROUP associated with. Required.
PANEL_GROUP_DASHBOARD = 'admin'
EOF
cat > $HORIZON/openstack_dashboard/local/enabled/tvault_panel.py <<-EOF
# The slug of the panel to be added to HORIZON_CONFIG. Required.
PANEL = 'workloads'
# The slug of the dashboard the PANEL associated with. Required.
PANEL_DASHBOARD = 'project'
# The slug of the panel group the PANEL is associated with.
PANEL_GROUP = 'backups'
# Python panel class of the PANEL to be added.
ADD_PANEL = ('dashboards.workloads.panel.Workloads')
DISABLED = False
EOF
cat > $HORIZON/openstack_dashboard/local/enabled/tvault_settings_panel.py <<-EOF
# The slug of the panel to be added to HORIZON_CONFIG. Required.
PANEL = 'settings'
# The slug of the dashboard the PANEL associated with. Required.
PANEL_DASHBOARD = 'project'
# The slug of the panel group the PANEL is associated with.
PANEL_GROUP = 'backups'
# Python panel class of the PANEL to be added.
ADD_PANEL = ('dashboards.settings.panel.Settings')
DISABLED = False
EOF
cat > $HORIZON/openstack_dashboard/local/enabled/tvault_admin_panel.py <<-EOF
# The slug of the panel to be added to HORIZON_CONFIG. Required.
PANEL = 'workloads_admin'
# The slug of the dashboard the PANEL associated with. Required.
PANEL_DASHBOARD = 'admin'
# The slug of the panel group the PANEL is associated with.
PANEL_GROUP = 'backups-admin'
# Python panel class of the PANEL to be added.
ADD_PANEL = ('dashboards.workloads_admin.panel.Workloads_admin')
ADD_INSTALLED_APPS = ['dashboards']
DISABLED = False
EOF
cat > $HORIZON/openstack_dashboard/templatetags/tvault_filter.py <<-EOF
from django import template
from openstack_dashboard import api
from openstack_dashboard import policy
from datetime import datetime
from django.template.defaultfilters import stringfilter
import pytz

register = template.Library()

@register.filter(name='getusername')
def get_user_name(user_id, request):
    user_name = user_id
    if policy.check((("identity", "identity:get_user"),), request):
        try:
            user = api.keystone.user_get(request, user_id)
            if user:
                user_name = user.username
        except Exception:
            pass
    else:
        LOG.debug("Insufficient privilege level to view user information.")
    return user_name

@register.filter(name='getprojectname')
def get_project_name(project_id, request):
    project_name = project_id
    try:
        project_info = api.keystone.tenant_get(request, project_id, admin = True)
        if project_info:
            project_name = project_info.name
    except Exception:
        pass
    return project_name

def get_time_zone(request):
    tz = 'UTC'
    try:
        tz = request._get_cookies()['django_timezone']
    except:
        try:
            tz = request.COOKIES['django_timezone']
        except:
            pass

    return tz

def get_local_time(record_time, input_format, output_format, tz):
        """
        Convert and return the date and time - from GMT to local time
        """
        try:
            if not record_time or record_time is None or record_time == '':
                return ''
            else:
                if not input_format \
                        or input_format == None \
                        or input_format == '':
                    input_format = '%Y-%m-%dT%H:%M:%S.%f';
                if not output_format  \
                        or output_format == None \
                        or output_format == '':
                    output_format = "%m/%d/%Y %I:%M:%S %p";

                local_time = datetime.strptime(
                                record_time, input_format)
                local_tz = pytz.timezone(tz)
                from_zone = pytz.timezone('UTC')
                local_time = local_time.replace(tzinfo=from_zone)
                local_time = local_time.astimezone(local_tz)
                local_time = datetime.strftime(
                                local_time, output_format)
                return local_time
        except Exception as ex:
            pass
            return record_time

@register.filter(name='gettime')
def get_time_for_audit(time_stamp, request):
    display_time = time_stamp
    try:
        time_zone_of_ui = get_time_zone(request)
        display_time = get_local_time(time_stamp, '%I:%M:%S.%f %p - %m/%d/%Y','%I:%M:%S %p - %m/%d/%Y', time_zone_of_ui)
    except Exception as ex:
        pass
    return display_time

@register.filter(name='getsnapshotquantifier')
def display_time_quantifier(seconds):
    intervals = (
    ('weeks', 604800),  # 60 * 60 * 24 * 7
    ('days', 86400),    # 60 * 60 * 24
    ('hours', 3600),    # 60 * 60
    ('minutes', 60),
    ('seconds', 1),
    )

    result = []
    granularity = 4
    for name, count in intervals:
        value = seconds // count
        if value:
            seconds -= value * count
            if value == 1:
                name = name.rstrip('s')
            result.append("{} {}".format(value, name))
        else:
            # Add a blank if we're in the middle of other values
            if len(result) > 0:
                result.append(None)
    return ', '.join([x for x in result[:granularity] if x is not None])

@register.filter(name='custom_split')
@stringfilter
def custom_split(value, key):
    key=int(key)
    return value.split('_')[key]

EOF

######
