FROM quay.io/openstack.kolla/nova-api:zed-ubuntu-jammy
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="kolla/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="5.1.0" \
      release="5.1" \
      type="source" \
      summary="TrilioData trilio-datamover-api" \
      description="TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root

##Install datamover packages

ADD trilio.list /etc/apt/sources.list.d/
RUN apt-get update -y
RUN apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y python3-dmapi python3-nova --allow-unauthenticated


## Kolla specifc settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY triliovault_datamover_api_extend_start.sh /usr/local/bin/kolla_triliovault_datamover_api_extend_start
RUN usermod -a -G kolla dmapi


##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi
