FROM kolla/ubuntu-binary-nova-api:wallaby
MAINTAINER Trilio shyam.biradar@trilio.io

LABEL name="kolla/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="Trilio" \
      version="5.0.X" \
      release="5.0" \
      summary="Trilio trilio-datamover-api" \
      description="Trilio trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root

##Install datamover packages
ADD trilio.list /etc/apt/sources.list.d/
RUN apt-get update -y

##Install datamover packages
RUN apt-get install -y python3-dmapi --allow-unauthenticated

## Create Config Dir
RUN mkdir -p /var/log/triliovault /etc/triliovault-datamover \
    && chown -R dmapi:dmapi /var/log/triliovault \
    && chown -R root:dmapi /etc/triliovault-datamover \
    && chmod -R 755 /var/log/triliovault /etc/triliovault-datamover

## Kolla specifc settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY triliovault_datamover_api_extend_start.sh /usr/local/bin/kolla_triliovault_datamover_api_extend_start
RUN usermod -aG kolla dmapi

##Become nova user for further operations
USER dmapi
