- import_tasks: db_setup.yml
  when:
    - inventory_hostname == groups['dmapi_all'][0]
  vars:
    _oslodb_setup_host: "{{ dmapi_db_setup_host }}"
    _oslodb_databases:
      - name: "{{ dmapi_galera_database }}"
        users:
          - username: "{{ dmapi_galera_user }}"
            password: "{{ dmapi_galera_password }}"

- import_tasks: mq_setup.yml
  when:
    - inventory_hostname == groups['dmapi_all'][0]
  vars:
    _oslomsg_rpc_setup_host: "{{ dmapi_oslomsg_rpc_setup_host }}"
    _oslomsg_rpc_userid: "{{ dmapi_oslomsg_rpc_userid }}"
    _oslomsg_rpc_password: "{{ dmapi_oslomsg_rpc_password }}"
    _oslomsg_rpc_vhost: "{{ dmapi_oslomsg_rpc_vhost }}"
    _oslomsg_rpc_transport: "{{ dmapi_oslomsg_rpc_transport }}"
    _oslomsg_notify_setup_host: "{{ dmapi_oslomsg_notify_setup_host }}"
    _oslomsg_notify_userid: "{{ dmapi_oslomsg_notify_userid }}"
    _oslomsg_notify_password: "{{ dmapi_oslomsg_notify_password }}"
    _oslomsg_notify_vhost: "{{ dmapi_oslomsg_notify_vhost }}"
    _oslomsg_notify_transport: "{{ dmapi_oslomsg_notify_transport }}"

