---
- name: install packages on datamover api container | Install Tzdata package
  shell: "export DEBIAN_FRONTEND=noninteractive && apt install -y tzdata"

- name: Copy repo file
  template:
     src: triliovault.list
     dest: "{{ trilio_apt_repo_file_path }}"

- name: update cache
  command: apt-get update

- name: install packages on datamover api container | software-properties-common | python-dev | python-nova | curl
  apt:
    pkg:
      - software-properties-common
      - "{{ PYTHON_VERSION }}-dev"
      - "{{ PYTHON_VERSION }}-nova"
      - curl
    update_cache: yes
    state: latest

- name: Set Time Zone
  file:
    src: '/usr/share/zoneinfo/{{TIME_ZONE}}'
    dest: /etc/localtime
    owner: root
    group: root
    state: link
  ignore_errors: yes
  when: TIME_ZONE != ""
  notify:
    - update timezone

- name: create /tmp/datamover_url
  template:
     src: datamover_url
     dest: /tmp/datamover_url

- name: Install python3-dmapi pckg
  package:
    name: python3-dmapi
    state: latest
  when: PYTHON_VERSION=="python3"

- name: create datamover_api_logging.conf file
  template:
     src: datamover_api_logging.conf.j2
     dest: "{{ DMAPI_LOG_CONF }}"

- import_tasks: store_os_ssl_cert.yml
  when:
    - OS_CA_CERT != "" 

- name: find out path of dmapi bianry
  shell: which dmapi-api
  register: dmapi_bin

- name: execute populate-conf binary
  shell: populate-conf
  register: populate_conf_ubuntu
  notify:
    - restart tvault-datamover-api

- name: enable and daemon reload tvault-datamover-api service
  shell: systemctl daemon-reload && systemctl enable tvault-datamover-api.service
  when: populate_conf.changed or create_systemd.changed
  notify:
      - restart tvault-datamover-api

- name: ensure /tmp/datamover_url file is deleted
  file: path="/tmp/datamover_url" state=absent

- name: Disable tvault-datamover-api service
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - tvault-datamover-api

- name: Verify "{{datamover_log_dir}}/dmapi-error.log" is present or not
  stat: path="{{datamover_log_dir}}/dmapi-error.log"
  register: dmapi_error_log

- name: Change ownership of log file
  file:
    path: "{{datamover_log_dir}}/dmapi-error.log"
    state: file
    owner: dmapi
    group: dmapi
    mode: '644'
  when:
    - dmapi_error_log.stat.exists == true

- name: Enable tvault-datamover-api service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - tvault-datamover-api

