---
- name: install packages on datamover api container | Install Tzdata package
  shell: "export DEBIAN_FRONTEND=noninteractive && apt install -y tzdata"

- name: install packages on datamover api container | software-properties-common | python-dev | python-nova | curl
  apt:
    pkg:
      - software-properties-common
      - "{{ PYTHON_VERSION }}-dev"
      - "{{ PYTHON_VERSION }}-nova"
      - curl
    update_cache: yes
    state: latest

- name: Set Time Zone
  file:
    src: '/usr/share/zoneinfo/{{TIME_ZONE}}'
    dest: /etc/localtime
    owner: root
    group: root
    state: link
  ignore_errors: yes
  when: TIME_ZONE != ""
  notify:
    - update timezone

- name: create /tmp/datamover_url
  template:
     src: datamover_url
     dest: /tmp/datamover_url

- name: install tvault-datamover-api deb package when using python2
  shell: |
          curl -Og6 http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/dmapi_{{ TVAULT_PACKAGE_VERSION  }}_all.deb
          apt-get install ./dmapi_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y
          rm -rf dmapi_{{ TVAULT_PACKAGE_VERSION }}_all.deb
  when: PYTHON_VERSION=="python2"

- name: install tvault-datamover-api deb package when using python3
  shell: |
          curl -Og6 http://{{ IP_ADDRESS }}:{{ PORT_NO }}/deb-repo/deb-repo/python3-dmapi_{{ TVAULT_PACKAGE_VERSION }}_all.deb
          apt-get install ./python3-dmapi_{{ TVAULT_PACKAGE_VERSION }}_all.deb -y
          rm -rf python3-dmapi_{{ TVAULT_PACKAGE_VERSION }}_all.deb
  when: PYTHON_VERSION=="python3"

- name: find out path of dmapi bianry
  shell: which dmapi-api
  register: dmapi_bin

- name: execute populate-conf binary
  shell: populate-conf
  register: populate_conf_ubuntu
  notify:
      - restart tvault-datamover-api

- name: ensure /tmp/datamover_url file is deleted
  file: path="/tmp/datamover_url" state=absent

