apiVersion: v1
kind: ConfigMap
metadata:
  name: openstack-exporter-clouds-cm
  namespace: openshift-user-workload-monitoring
data:
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          auth_url: https://keystone-public-openstack.apps.QA1.engineering.trilio.io
          username: admin
          password: "$PASSWORD"
          project_name: admin
          user_domain_name: Default
          project_domain_name: Default
        region_name: regionOne
        cacert: /etc/ssl/certs/ca.crt
        interface: public
        identity_api_version: 3

