apiVersion: v1
kind: Service
metadata:
  name: openstack-exporter
  namespace: openshift-user-workload-monitoring
  labels:
    app: openstack-exporter
spec:
  selector:
    app: openstack-exporter
  ports:
    - name: os-metrics
      port: 9180
      targetPort: 9180
      protocol: TCP

