{{- if eq .Values.crdType "TVOControlPlane" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: triliovault-dms
  labels:
    application: triliovault
    component: dms
spec:
  selector:
    matchLabels:
      application: triliovault
      component: dms
  template:
    metadata:
      labels:
        application: triliovault
        component: dms
      {{- if .Values.pod.triliovault_dms.networks }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Values.pod.triliovault_dms.networks | quote }}
      {{- end }}
    spec:
      serviceAccountName: triliovault-dms
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      nodeSelector:
        trilio-control-plane: enabled
      terminationGracePeriodSeconds: 90
      initContainers:
        - name: triliovault-dms-init
          image: {{ .Values.images.triliovault_dms }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsGroup: {{ .Values.common.nova_user_id }}
            runAsUser: 0
          env:
            - name: WLM_RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trilio-openstack-secret
                  key: WlmRabbitPassword
            - name: WLM_RABBIT_USER
              value: "{{- .Values.rabbitmq.wlm_api.user -}}"
            - name: WLM_RABBIT_VHOST
              value: "{{- .Values.rabbitmq.wlm_api.vhost -}}"
            - name: WLM_RABBIT_HOST
              value: "{{- .Values.rabbitmq.common.host -}}"
            - name: IS_RABBIT_SSL_ENABLED
              value: "{{- .Values.rabbitmq.common.ssl -}}"
          command:
            - /bin/bash
            - -c
            - /tmp/triliovault-dms-init.sh
          terminationMessagePath: /var/log/termination-log
          volumeMounts:
            - name: trilio-logs
              mountPath: /var/log/triliovault
            - name: triliovault-dms-bin
              mountPath: /tmp/triliovault-dms-init.sh
              subPath: triliovault-dms-init.sh
            - name: pod-shared-triliovault-dms
              mountPath: /tmp/pod-shared-triliovault-dms
            - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              name: combined-ca-bundle
              readOnly: true
              subPath: tls-ca-bundle.pem
      containers:
        - name: triliovault-dms
          image: {{ .Values.images.triliovault_dms }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: {{ .Values.common.nova_user_id }}
          {{- if .Values.pod.triliovault_dms.debug_mode }}
          command:
            - /bin/bash
            - -c
            - /usr/bin/sleep 500m
          {{- else }}
          command:
            - /bin/bash
            - -c
            - /tmp/triliovault-dms.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /tmp/triliovault-dms.sh stop
          {{- end }}
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: trilio-logs
              mountPath: /var/log/triliovault
            - name: triliovault-dms-etc
              mountPath: /etc/triliovault-dms/server.conf
              subPath: server.conf
              readOnly: true
            - name: triliovault-dms-etc
              mountPath: /etc/triliovault-dms/client.conf
              subPath: client.conf
              readOnly: true
            - name: triliovault-dms-bin
              mountPath: /tmp/triliovault-dms.sh
              subPath: triliovault-dms.sh
            - name: pod-shared-triliovault-dms
              mountPath: /tmp/pod-shared-triliovault-dms
            - name: trilio-mounts
              mountPath: {{ .Values.common.vault_data_dir }}
              mountPropagation: Bidirectional
            - mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
              name: combined-ca-bundle
              readOnly: true
              subPath: tls-ca-bundle.pem
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: trilio-logs
          emptyDir: {}
        - name: triliovault-dms-etc
          secret:
            secretName: triliovault-dms-etc
            defaultMode: 0444
        - name: triliovault-dms-bin
          configMap:
            name: triliovault-dms-bin
            defaultMode: 0555
        - name: pod-shared-triliovault-dms
          emptyDir: {}
        - name: trilio-mounts
          hostPath:
            path: {{ .Values.common.vault_data_dir }}
            type: DirectoryOrCreate
        - name: combined-ca-bundle
          secret:
            defaultMode: 292
            secretName: combined-ca-bundle
{{- end }}
