{{- if eq .Values.crdType "TVOControlPlane" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: triliovault-dms-etc
type: Opaque
data:
  server.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_dms_server_conf.tpl") . | b64enc }}
  client_wlm.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_dms_client_conf_wlm.tpl") . | b64enc }}
  client_dmapi.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_dms_client_conf_dmapi.tpl") . | b64enc }}
{{- end }}
