{{- if eq .Values.crdType "TVOControlPlane" }}
apiVersion: {{ .Values.rabbitmq.cluster.api_version }}
kind: RabbitmqCluster
metadata:
  name: trilio-rabbitmq-cluster
  namespace: {{ .Values.rabbitmq.common.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-18"
spec:
  replicas: {{ .Values.rabbitmq.cluster.replicas }}
  image: {{ .Values.images.rabbitmq }}
  delayStartSeconds: 30
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              image: {{ .Values.images.rabbitmq }}
              args:
              - /usr/lib/rabbitmq/bin/rabbitmq-server
              env:
              - name: RABBITMQ_UPGRADE_LOG
                value: /var/lib/rabbitmq/rabbitmq_upgrade.log
              - name: HOME
                value: /var/lib/rabbitmq
              - name: PATH
                value: /usr/lib/rabbitmq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
              - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
                value: '-kernel inetrc ''/etc/rabbitmq/erl_inetrc'' -proto_dist inet_tls -ssl_dist_optfile /etc/rabbitmq/inter-node-tls.config'
              - name: RABBITMQ_CTL_ERL_ARGS
                value: -proto_dist inet_tls -ssl_dist_optfile /etc/rabbitmq/inter-node-tls.config
              volumeMounts:
              - mountPath: /etc/rabbitmq/inter-node-tls.config
                name: config-data
                readOnly: true
                subPath: inter_node_tls.config
            volumes:
            - name: config-data
              configMap:
                name: trilio-rabbitmq-cluster-config-data
                defaultMode: 272
                items:
                - key: inter_node_tls.config
                  path: inter_node_tls.config
  resources:
    requests:
      cpu: {{ .Values.rabbitmq.cluster.resources.requests.cpu }}
      memory: {{ .Values.rabbitmq.cluster.resources.requests.memory }}
    limits:
      cpu: {{ .Values.rabbitmq.cluster.resources.limits.cpu }}
      memory: {{ .Values.rabbitmq.cluster.resources.limits.memory }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.cluster.persistence.storage_class_name }}
    storage: {{ .Values.rabbitmq.cluster.persistence.storage }}
  tls:
    secretName: cert-trilio-rabbitmq-cluster
    caSecretName: cert-trilio-rabbitmq-cluster
    disableNonTLSListeners: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - trilio-rabbitmq-cluster
            topologyKey: kubernetes.io/hostname
  rabbitmq:
    additionalConfig: |
{{ .Values.rabbitmq.cluster.rabbitmq.additional_config | nindent 6 }}
{{- if .Values.rabbitmq.cluster.rabbitmq.advanced_config }}
    advancedConfig: |
{{ .Values.rabbitmq.cluster.rabbitmq.advanced_config | nindent 6 }}
{{- end }}
{{- if .Values.rabbitmq.cluster.rabbitmq.erlang_inet_config }}
    erlangInetConfig: |
{{ .Values.rabbitmq.cluster.rabbitmq.erlang_inet_config | nindent 6 }}
{{- end }}
  service:
    type: {{ .Values.rabbitmq.cluster.service.type }}
  terminationGracePeriodSeconds: {{ .Values.rabbitmq.cluster.termination_grace_period_seconds | default 604800 }}
{{- end }}
