FROM registry.redhat.io/rhosp-rhel9/openstack-base:17.1
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio/openstack-nova-compute-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="5.2.0" \
      release="5.2" \
      summary="Red Hat OpenStack Platform 17.1 nova-compute TrilioData Datamover" \
      description="Red Hat OpenStack Platform 17.1 nova-compute TrilioData Datamover"

# switch to root and install a custom RPM, etc.
USER root

## Setup repos
RUN dnf clean all && dnf config-manager --set-disabled \*
ADD trilio.repo /etc/yum.repos.d/
ADD virt-v2v-1.42.0-22.module+el8.9.0+18724+20190c23.x86_64.rpm /tmp/

RUN dnf config-manager \
  --enable rhel-9-for-x86_64-baseos-eus-rpms \
  --enable rhel-9-for-x86_64-appstream-eus-rpms \
  --enable rhel-9-for-x86_64-highavailability-eus-rpms \
  --enable openstack-17.1-for-rhel-9-x86_64-rpms \
  --enable fast-datapath-for-rhel-9-x86_64-rpms \
  --enable rhceph-6-tools-for-rhel-9-x86_64-rpms

## Install triliovault datamover packages
RUN dnf install --releasever 9.2 openstack-nova-common python3-nova python3-novaclient udev fuse virt-v2v virtio-win nbdkit --nobest -y
RUN usermod -u 42436 nova && groupmod -g 42436 nova && usermod -aG disk,libvirt,kolla nova
RUN dnf install --releasever 9.2 python3-tvault-contego-el9 python3-s3fuse-plugin-el9 qemu-img ceph-common python3-libvirt python3-cinderclient qemu-kvm-block-rbd -y
RUN dnf --releasever 9.2 -y update-minimal --security --sec-severity=Important --sec-severity=Critical --exclude=python3-libvirt --nobest


#Copy executable files
RUN mkdir -p /opt/triliovault/
ADD start_triliovault_datamover_s3 start_triliovault_datamover_nfs start_triliovault_object_store /opt/triliovault/
RUN chown -R nova:nova /opt/triliovault/
RUN chmod -R 755 /opt/triliovault

##Copy conf files
ADD nova-sudoers /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters
ADD log-rotate-conf /etc/logrotate.d/triliovault-datamover.conf
RUN chown root:root /etc/sudoers.d/nova-sudoers \
  && chown root:nova /usr/share/nova/nova-dist.conf
  
## Create conf directories
RUN mkdir -p /etc/triliovault-object-store /etc/triliovault-datamover /var/log/triliovault /var/triliovault /var/lib/nova/triliovault-mounts \
    && chown -R nova:nova /etc/triliovault-datamover /etc/triliovault-object-store/ /var/lib/nova /var/log/triliovault /var/triliovault \
    && chmod -R 755 /var/lib/nova


##Disable repos and Clean subscription
RUN dnf config-manager \
  --disable rhel-9-for-x86_64-baseos-eus-rpms \
  --disable rhel-9-for-x86_64-appstream-eus-rpms \
  --disable rhel-9-for-x86_64-highavailability-eus-rpms \
  --disable openstack-17.1-for-rhel-9-x86_64-rpms \
  --disable fast-datapath-for-rhel-9-x86_64-rpms \
  --disable rhceph-6-tools-for-rhel-9-x86_64-rpms

RUN dnf install /tmp/virt-v2v-1.42.0-22.module+el8.9.0+18724+20190c23.x86_64.rpm -y
RUN rm -f /tmp/virt-v2v-1.42.0-22.module+el8.9.0+18724+20190c23.x86_64.rpm

RUN dnf clean all


##Add license
RUN mkdir /licenses
COPY licensing.txt /licenses


##Become nova user for further operations
USER nova
