apiVersion: v1
kind: ConfigMap
metadata:
  name: trilio-backup-target-bin
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  create-backup-target.sh: |
    {{ tpl (.Files.Get "scripts/_create-backup-target.sh.tpl") . | nindent 4 }}
