FROM kolla/centos-binary-nova-compute:victoria
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="kolla/trilio-datamover" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="TrilioData Datamover" \
      description="TrilioData Datamover"

# switch to root and install a custom RPM, etc.
USER root

RUN dnf clean all
RUN dnf config-manager --save --setopt=epel.skip_if_unavailable=true

##Install datamover packages in CentOS 8
ADD trilio.repo /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Ceph-Nautilus.repo
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Ceph-Nautilus.repo
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-NFV-OpenvSwitch.repo
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-NFV-OpenvSwitch.repo
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-OpenStack-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-OpenStack-*
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-OpsTools.repo
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-OpsTools.repo
RUN dnf install -y python3-tvault-contego python3-s3fuse-plugin

## Kolla settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start


#Copy executable files
RUN mkdir -p /opt/tvault/ 
ADD start_datamover_s3 start_datamover_nfs start_tvault_object_store /opt/tvault/
RUN chown -R nova:nova /opt/tvault/ \
   && chmod 755 /opt/tvault/start_datamover_s3 /opt/tvault/start_datamover_nfs /opt/tvault/start_tvault_object_store

##Copy conf files
ADD nova-sudoers /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters
RUN usermod -aG disk nova \
 && usermod -aG kvm nova

ADD tvault-contego.conf /etc/tvault-contego/tvault-contego.conf
RUN chown nova:nova /etc/tvault-contego/tvault-contego.conf

RUN mkdir -p /var/triliovault-mounts \
 && chown nova:nova /var/triliovault-mounts \
 && mkdir -p /var/triliovault \
 && chmod 777 /var/triliovault-mounts \
 && chown nova:nova /var/triliovault \
 && chmod 777 /var/triliovault

ADD log-rotate-conf /etc/logrotate.d/tvault-contego

##Clean subscription
RUN dnf clean all
RUN rm -f /etc/yum.repos.d/trilio.repo

##Add license
RUN mkdir /licenses
COPY licensing.txt /licenses


##Become nova user for further operations
USER nova
