#!/bin/sh
dispatch_path="$(dirname $(realpath $0))"
JUJU_DISPATCH_PATH="${JUJU_DISPATCH_PATH:-$0}" PYTHONPATH="${dispatch_path}/lib:${dispatch_path}/venv" \
  exec python3 "${dispatch_path}/src/charm.py"
