#!/bin/sh
dispatch_path="$(dirname $(realpath $0))"
venv_bin_path="${dispatch_path}/venv/bin"
python_path="${venv_bin_path}/python"
if [ ! -e "${python_path}" ]; then
    mkdir -p "${venv_bin_path}"
    ln -s $(which python3) "${python_path}"
fi

export PYTHONPATH="${dispatch_path}/lib:${dispatch_path}/src"
export LD_LIBRARY_PATH="${dispatch_path}/usr/lib:${dispatch_path}/lib:${dispatch_path}/usr/lib/$(uname -m)-linux-gnu"

exec "${python_path}" "${dispatch_path}/src/charm.py"
