FROM kolla/ubuntu-binary-nova-compute:wallaby
MAINTAINER Trilio shiwanand.bicchewar@trilio.io

LABEL name="kolla/trilio-datamover" \
      maintainer="shiwanand.bicchewar@trilio.io" \
      vendor="Trilio" \
      version="5.0.X" \
      release="5.0" \
      summary="Trilio Datamover" \
      description="Trilio Datamover"

# switch to root and install a custom RPM, etc.
USER root

##Copy Debian Repo
ADD trilio.list /etc/apt/sources.list.d/
RUN apt-get update -y

##Add nova user into the disk and kvm group
RUN usermod -aG disk,kvm nova

##Install Triliovault-Datamover packages
RUN apt-get install -y python3-tvault-contego python3-s3-fuse-plugin --allow-unauthenticated

## Kolla settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start

#Copy executable files
RUN mkdir -p /opt/tvault/
ADD start_datamover_s3 start_datamover_nfs start_tvault_object_store /opt/tvault/
RUN chown -R nova:nova /opt/tvault/ \
   && chmod 755 /opt/tvault/start_datamover_s3 /opt/tvault/start_datamover_nfs /opt/tvault/start_tvault_object_store

##Copy conf files
ADD nova-sudoers /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters

## Create Config Dir.
RUN mkdir -p /var/log/triliovault /var/trilio/triliovault-mounts /var/triliovault /etc/triliovault-datamover /etc/triliovault-object-store \
    && chown -R nova:nova /var/log/triliovault /var/trilio/triliovault-mounts /var/triliovault \
    && chown -R root:nova /etc/triliovault-datamover  /etc/triliovault-object-store \
    && chmod -R 755 /var/log/triliovault /etc/triliovault-datamover /etc/triliovault-object-store \
    && chmod -R 777 /var/trilio/triliovault-mounts /var/triliovault


##Clean up
RUN rm -f /etc/apt/sources.list.d/trilio.list

##Become nova user for further operations
USER nova