FROM quay.io/openstack.kolla/nova-compute:zed-ubuntu-jammy
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="kolla/trilio-datamover" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="5.1.0" \
      release="5.1" \
      type="source" \
      summary="TrilioData Datamover" \
      description="TrilioData Datamover"

# switch to root and install a custom RPM, etc.
USER root

##Install datamover packages
ADD trilio.list /etc/apt/sources.list.d/
RUN apt-get update -y

RUN apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y nova-common python3-nova \
    && apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y python3-novaclient python3-monotonic udev fuse \
    && apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y qemu-utils ceph-common python3-libvirt python3-cinderclient \
    && apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y python3-tvault-contego python3-s3-fuse-plugin --allow-unauthenticated


## Kolla settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start

## Create directory to hold service start scripts
RUN mkdir -p /opt/triliovault && chown -R nova:nova /opt/triliovault

##Copy conf files
ADD nova-sudoers-source /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters
RUN usermod -aG disk nova \
 && usermod -aG kvm nova

RUN mkdir -p /var/triliovault-mounts \
 && chown nova:nova /var/triliovault-mounts \
 && mkdir -p /var/triliovault \
 && chmod 777 /var/triliovault-mounts \
 && chown nova:nova /var/triliovault \
 && chmod 777 /var/triliovault

ADD log-rotate-conf /etc/logrotate.d/tvault-contego


##Add license
RUN mkdir /licenses
COPY licensing.txt /licenses


##Become nova user for further operations
USER nova