FROM quay.io/openstack.kolla/centos-source-nova-compute:yoga
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="kolla/trilio-datamover" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.2.0" \
      release="4.2" \
      type="source" \
      summary="TrilioData Datamover" \
      description="TrilioData Datamover"

# switch to root and install a custom RPM, etc.
USER root

RUN dnf clean all
RUN dnf config-manager --save --setopt=epel.skip_if_unavailable=true

##Install datamover packages in CentOS 8
ADD trilio.repo /etc/yum.repos.d/
RUN dnf install openstack-nova-common python3-nova python3-novaclient python3-monotonic udev fuse -y \
    && dnf install python3-tvault-contego python3-s3fuse-plugin qemu-img ceph-common python3-libvirt python3-cinderclient qemu-kvm-block-rbd -y

RUN usermod -u 42436 nova && groupmod -g 42436 nova && usermod -aG disk,libvirt,kolla,kvm nova


## Kolla settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start


#Copy executable files
RUN mkdir -p /opt/tvault/ 
ADD start_datamover_s3 start_datamover_nfs start_tvault_object_store /opt/tvault/
RUN chown -R nova:nova /opt/tvault/ \
   && chmod 755 /opt/tvault/start_datamover_s3 /opt/tvault/start_datamover_nfs /opt/tvault/start_tvault_object_store

##Copy conf files
ADD nova-sudoers-source /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters

RUN mkdir -p /var/triliovault-mounts \
 && chown nova:nova /var/triliovault-mounts \
 && mkdir -p /var/triliovault \
 && chmod 777 /var/triliovault-mounts \
 && chown nova:nova /var/triliovault \
 && chmod 777 /var/triliovault

ADD log-rotate-conf /etc/logrotate.d/tvault-contego

##Clean subscription
RUN dnf clean all
RUN rm -f /etc/yum.repos.d/trilio.repo

##Add license
RUN mkdir /licenses
COPY licensing.txt /licenses


##Become nova user for further operations
USER nova
