FROM docker.io/tripleowallaby/openstack-nova-compute:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="tripleo/openstack-nova-compute-triliodata" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.2.0" \
      release="4.2" \
      summary="TripleO Wallaby nova-compute plugin TrilioData Datamover" \
      description="TripleO Wallaby nova-compute plugin TrilioData Datamover"

# switch to root and install a custom RPM, etc.
USER root

##Install datamover packages
RUN dnf clean all
ADD trilio.repo delorean-component-tripleo.repo /etc/yum.repos.d/
RUN rpm -ivh centos-stream-repos-8-4.el8.noarch.rpm centos-gpg-keys-8-4.el8.noarch.rpm
RUN rm -f centos-gpg-keys-8-4.el8.noarch.rpm centos-gpg-keys-8-4.el8.noarch.rpm
RUN dnf install -y python3-tripleo-repos
RUN tripleo-repos -b wallaby current ceph

RUN dnf install python3-tvault-contego puppet-triliovault python3-s3fuse-plugin -y

#Copy executable files
RUN mkdir -p /opt/tvault/
ADD start_datamover_s3  /opt/tvault/
ADD start_tvault_object_store_tripleo_centos8 /opt/tvault/start_tvault_object_store
ADD start_datamover_nfs_tripleo_centos8 /opt/tvault/start_datamover_nfs
RUN chown -R nova:nova /opt/tvault/
RUN chmod 755 /opt/tvault/start_datamover_s3 /opt/tvault/start_datamover_nfs /opt/tvault/start_tvault_object_store
RUN sed  -i '0,/^/s//sudo \/usr\/sbin\/modprobe nbd nbds_max=128\n\n/' /opt/tvault/start_datamover_nfs

##Copy conf files
ADD nova-sudoers-rhel8 /etc/sudoers.d/nova-sudoers
RUN chown root:root /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters
RUN usermod -aG disk nova
ADD tvault-contego.conf /etc/tvault-contego/tvault-contego.conf
RUN chown nova:nova /etc/tvault-contego/tvault-contego.conf
RUN mkdir -p /var/triliovault-mounts
RUN chown nova:nova /var/triliovault-mounts
RUN mkdir -p /var/triliovault
RUN chmod 777 /var/triliovault-mounts
RUN chown nova:nova /var/triliovault
RUN chmod 777 /var/triliovault
RUN mkdir -p /var/log/trilio-datamover
RUN chown nova:nova /var/log/trilio-datamover
ADD log-rotate-conf /etc/logrotate.d/tvault-contego

##Clean subscription
RUN dnf clean all
RUN rm -f /etc/yum.repos.d/trilio.repo

##Add license
RUN mkdir /licenses
COPY licensing.txt /licenses


##Become nova user for further operations
USER nova
