[DEFAULT]
verbose = {{ options.verbose }}
debug = {{ options.debug }}
log_config_append = /etc/triliovault-object-store/object_store_logging.conf

vault_storage_nfs_export = {{ options.vault_storage_nfs_export }}
vault_data_directory = /var/triliovault-mounts/{{ options.backup_target_mount_point }}
vault_data_directory_old = /var/triliovault
vault_storage_type = {{ options.backup_target_type }}
vault_s3_auth_version = DEFAULT
vault_s3_access_key_id = {{ options.s3_access_key }}
vault_s3_secret_access_key = {{ options.s3_secret_key }}
vault_s3_region_name =  {{ options.s3_region_name }}
vault_s3_bucket =  {{ options.s3_bucket }}
vault_s3_endpoint_url =  {{ options.s3_endpoint_url }}
vault_s3_ssl = {{ options.s3_ssl_enabled }}
vault_s3_ssl_verify = {{ options.s3_ssl_verify }}
{% if options.s3_self_signed_cert -%}
vault_s3_ssl_cert = /etc/triliovault-object-store/s3-cert-{{ options.backup_target_name }}.pem
{% endif %}

{%- if options.s3_bucket_object_lock_enabled -%}
bucket_object_lock=true
use_manifest_suffix=true
{% else %}
bucket_object_lock=false
use_manifest_suffix=false
{% endif %}


[s3fuse_sys_admin]
helper_command = sudo /usr/bin/nova-rootwrap /etc/nova/rootwrap.conf privsep-helper
