FROM kolla/ubuntu-binary-nova-api:wallaby
MAINTAINER Trilio shiwanand.bicchewar@trilio.io

LABEL name="trilio/triliovault-wlm" \
      org.opencontainers.image.authors="shiwanand.bicchewar@trilio.io" \
      vendor="Trilio" \
      version="5.0.X" \
      release="5.0" \
      summary="Kolla Ansible Openstack Ubuntu-20.04 nova-api Trilio TrilioVaultWLM" \
      description="Kolla Ansible Openstack Ubuntu-20.04 nova-api Trilio TrilioVaultWLM container image"


# switch to root and install a custom Debian packages, etc.
USER root


##Add trilio.list which contains the path for TrilioVaultWLM Debian packages
ADD trilio.list /etc/apt/sources.list.d/

## INSTALL REQUIRED PACKAGES
RUN set -ex \
     && apt-get -y update \
     && apt-get -y install zlib1g-dev libpython3-dev python3.8-dev \
     && apt-get -y install python3-dev libcurl4-openssl-dev libssl-dev python3-m2crypto libmysqlclient-dev qemu-utils libxml2-dev libxslt-dev \
     && apt-get -y install nfs-common swig python3-guestfs libguestfs-tools libvirt-daemon-system  python3.8-venv \
     && apt-get -y install python3-neutronclient python3-glanceclient \
     && pip3 --no-cache-dir install --upgrade pip \
     && apt-get clean -y

# Installing TrilioVaultWLM packages
RUN apt-get -y install workloadmgr python3-workloadmgrclient python3-contegoclient python3-s3-fuse-plugin --allow-unauthenticated


##Copy conf files
RUN mkdir -p /etc/triliovault-wlm /etc/triliovault-object-store /var/trilio/triliovault-mounts /var/triliovault /var/log/triliovault 
RUN chown -R nova:nova /var/log/triliovault /var/trilio /var/trilio/triliovault-mounts /var/triliovault \
    && chown -R root:nova /etc/triliovault-wlm /etc/triliovault-object-store 
RUN chmod -R 755 /var/log/triliovault /etc/triliovault-wlm /etc/triliovault-object-store \
    && chmod -R 777 /var/trilio/triliovault-mounts /var/triliovault

## Kolla specific settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY triliovault_wlm_extend_start.sh /usr/local/bin/kolla_triliovault_wlm_extend_start

## Nova user changes
RUN usermod -u 42436 nova && groupmod -g 42436 nova && usermod -aG disk,kolla nova

##Clean subscription
RUN rm -f /etc/apt/sources.list.d/trilio.list


##Become nova user for further operations
USER nova
