FROM quay.io/openstack.kolla/nova-api:zed-ubuntu-jammy
MAINTAINER Trilio shyam.biradar@trilio.io

LABEL name="kolla/openstack-nova-api-triliodata--wlm-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="5.1.0" \
      release="5.1"\
      type="source" \
      summary="TrilioData trilio-datamover-api" \
      description="TrilioData TrilioVault WLM Image based on Ubuntu OS"


# switch to root and install a custom Debian packages, etc.
USER root

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC
##Add trilio.list which contains the path for TrilioVaultWLM Debian packages
ADD trilio.list /etc/apt/sources.list.d/

## INSTALL REQUIRED PACKAGES
RUN set -ex \
     && apt-get -y update \
     && apt-get -y install zlib1g-dev libpython3-dev \
     && apt-get -y install libcurl4-openssl-dev libssl-dev python3-m2crypto libmysqlclient-dev qemu-utils libxml2-dev libxslt-dev \
     && apt-get -y install nfs-common swig python3-guestfs libguestfs-tools libvirt-daemon-system \
     && apt-get -y install python3-neutronclient python3-glanceclient \
     && pip3 --no-cache-dir install --upgrade pip \
     && apt-get clean -y

# Installing TrilioVaultWLM packages
RUN apt-get -o Dpkg::Options::="--force-confold" --force-yes -y install workloadmgr python3-workloadmgrclient python3-contegoclient python3-s3-fuse-plugin --allow-unauthenticated


##Copy conf files
RUN mkdir -p /etc/triliovault-wlm /etc/triliovault-object-store /var/trilio/triliovault-mounts /var/triliovault /var/log/triliovault 
RUN chown -R nova:nova /var/log/triliovault /var/trilio /var/trilio/triliovault-mounts /var/triliovault /var/lib/workloadmgr \
    && chown -R root:nova /etc/triliovault-wlm /etc/triliovault-object-store 
RUN chmod -R 755 /var/log/triliovault /etc/triliovault-wlm /etc/triliovault-object-store /var/lib/workloadmgr \
    && chmod -R 777 /var/trilio/triliovault-mounts /var/triliovault

## Kolla specific settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY triliovault_wlm_extend_start.sh /usr/local/bin/kolla_triliovault_wlm_extend_start

## Nova user changes
RUN usermod -u 42436 nova && groupmod -g 42436 nova && usermod -aG disk,kolla nova

##Clean subscription
RUN rm -f /etc/apt/sources.list.d/trilio.list


##Become nova user for further operations
USER nova
