{
 "title": "Trilio Openstack Backup Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "project_name",
    "label": "Project Name",
    "query": {
     "query": "label_values(openstack_identity_project_info{name!=\"service\"},name)"
    }
   },
   {
    "name": "project_id",
    "label": "Project ID",
    "query": {
     "query": "label_values(openstack_identity_project_info{name=\"$project_name\"}, id)"
    }
   },
   { "name": "datasource", "label": "Datasoure", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Project Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Snapshot",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (\n  mysql_trilio_snapshot_last_updated{ProjectID=\"$project_id\"} >= $__from\n  and\n  mysql_trilio_snapshot_last_updated{ProjectID=\"$project_id\"} <= $__to\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_trilio_restore_info{status=~\"failed|running|successful\", ProjectID=\"$project_id\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Protected Instance info",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_server_status{tenant_id=\"$project_id\"})\n-\n(\n  sum(openstack_protected_vm{ProjectID=\"$project_id\"})\n  or vector(0)\n)\n",
     "legendFormat": "Unprotected"
    },
    {
     "expr": "(\n  sum(openstack_protected_vm{ProjectID=\"$project_id\"})\n  or vector(0)\n)",
     "legendFormat": "Protected"
    }
   ]
  },
  {
   "title": "Backup Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(mysql_trilio_backup_size_info{ProjectID=\"$project_id\"})\n / scalar(trilio_allowed_quota_value{QuotaName=\"Storage\",ProjectID=\"$project_id\"})) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(openstack_protected_vm{ProjectID=\"$project_id\"}) / scalar(trilio_allowed_quota_value{QuotaName=\"VMs\",ProjectID=\"$project_id\"})) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snapshot  Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (mysql_trilio_snapshots_info{ProjectID=\"$project_id\"})/scalar(trilio_allowed_quota_value{QuotaName=\"Snapshots\",ProjectID=\"$project_id\"})) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Quota Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count by (ProjectID) (trilio_workload_info{ProjectID=\"$project_id\"})/scalar(trilio_allowed_quota_value{QuotaName=\"Workloads\",ProjectID=\"$project_id\"}))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of Workload",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (ID) (\n    max_over_time(\n      trilio_workload_info{Deleted=\"0\", ProjectID=~\"$project_id\"}[${__range}]\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Snapshots",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "mysql_trilio_snapshot_last_updated{status=\"failed\", ProjectID=\"$project_id\"} >= $__from and mysql_trilio_snapshot_last_updated{status=\"failed\", ProjectID=\"$project_id\"} <= $__to"
    }
   ]
  },
  {
   "title": "Failed Restores",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "mysql_trilio_restore_last_updated{status=\"failed\", ProjectID=\"$project_id\"} >= $__from and mysql_trilio_restore_last_updated{status=\"failed\", ProjectID=\"$project_id\"} <= $__to"
    }
   ]
  },
  { "title": "Cloud Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Snapshot",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (status) (\n  mysql_trilio_snapshot_last_updated >= $__from\n  and\n  mysql_trilio_snapshot_last_updated <= $__to\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (mysql_trilio_restore_info)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "No of Workload",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (ID) (\n    max_over_time(\n      trilio_workload_info{Deleted=\"0\"}[${__range}]\n    )\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Backup Size(GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mysql_trilio_backup_size_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Protected instance info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_server_status) - sum(openstack_protected_vm)",
     "legendFormat": "Unprotected"
    },
    { "expr": "sum(openstack_protected_vm)", "legendFormat": "Protected" }
   ]
  }
 ]
}