{{- if eq .Values.action "Install" }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: triliovault-wlm-api
  namespace: trilio-openstack
spec:
  minAvailable: 2
  selector:
    matchLabels:
      release_group: t4o
      application: triliovault
      component: wlm-api
{{- end }}
