{{- if eq .Values.trilio_backup_target.backup_target_type "s3" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: trilio-object-store-etc-single-bt-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
type: Opaque
data:
  object_store_logging.conf: |
     {{ tpl (.Files.Get "scripts/_object_store_logging_conf.tpl") . | b64enc }}
    {{- if eq .Values.trilio_backup_target.backup_target_type "s3" }}
  trilio-object-store-{{ .Values.trilio_backup_target.backup_target_name | lower }}.conf: |
    {{- $target := .Values.trilio_backup_target }}
    {{ include "to_ini_object_store" (dict "target" $target "Values" .Values) | b64enc }}
      {{- if .Values.trilio_backup_target.s3_self_signed_cert }}
  s3-cert-{{ .Values.trilio_backup_target.backup_target_name | lower }}.pem: |
    {{ .Values.trilio_backup_target.s3_ssl_ca_cert | b64enc }}
      {{- end }}
    {{- end }}
{{- end }}
