{{- if eq .Values.trilio_backup_target.backup_target_type "s3" }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trilio-object-store-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
  labels:
    application: trilio-openstack
    component: object-store-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
spec:
  selector:
    matchLabels:
      application: trilio-openstack
      component: object-store-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
  template:
    metadata:
      labels:
        application: trilio-openstack
        component: object-store-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
    spec:
      serviceAccountName: trilio-backup-targets-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      nodeSelector:
        triliovault-control-plane: enabled
        openstack-compute-node: enabled
      terminationGracePeriodSeconds: 30
      containers:
        - name: trilio-object-store-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
          image: {{ .Values.images.trilio_wlm }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: {{ .Values.common.nova_user_id }}
          command:
            - /bin/bash
            - -c
            - /tmp/trilio-object-store.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /tmp/trilio-object-store.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: trilio-logs
              mountPath: /var/log/trilio
            - mountPath: /etc/trilio-object-store/object_store_logging.conf
              name: trilio-object-store-etc
              readOnly: true
              subPath: object_store_logging.conf
            - name: trilio-object-store-etc
              mountPath: /etc/trilio-object-store/trilio-object-store.conf
              subPath: trilio-object-store-{{ .Values.trilio_backup_target.backup_target_name | lower }}.conf
              readOnly: true
            {{- if .Values.trilio_backup_target.s3_self_signed_cert }}
            - name: trilio-object-store-etc
              mountPath: /etc/trilio-object-store/s3-cert-{{ .Values.trilio_backup_target.backup_target_name | lower }}.pem
              subPath: s3-cert-{{ .Values.trilio_backup_target.backup_target_name | lower }}.pem
              readOnly: true
            {{- end }}
            - name: trilio-object-store-bin
              mountPath: /tmp/trilio-object-store.sh
              subPath: trilio-object-store.sh
            - name: pod-shared-trilio-object-store
              mountPath: /tmp/pod-shared-trilio-object-store
            - name: trilio-mounts
              mountPath: /var/lib/trilio
              mountPropagation: Bidirectional
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: trilio-logs
          emptyDir: {}
        - name: trilio-object-store-etc
          secret:
            secretName: trilio-object-store-etc-single-bt-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
            defaultMode: 0444
        - name: trilio-object-store-bin
          configMap:
            name: trilio-object-store-bin-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
            defaultMode: 0555
        - name: pod-shared-trilio-object-store
          emptyDir: {}
        - name: trilio-mounts
          hostPath:
            path: /var/lib/trilio
            type: DirectoryOrCreate
{{- end }}
