---
#- hosts: tvault
#  vars_files:
#   - /root/tvault_deploy_scripts/vars/tvault-contego-answers.yml
#   - /root/tvault_deploy_scripts/vars/tvault-contego-static-answers.yml
#
#  vars:
#   files_path: /root/automation/tvault-deploy-scripts/roles/ansible-tvault-contego-extension/
#   CONFIG_FILES: "aa"
#   CONFIG_FILES_1: "bb"
#
#  tasks:
- block:
  - name: copy object store service file , write content , enable and daemon reload service if object restore is True
    block:
      - set_fact:
          service_file_dest_path: /etc/systemd/system/tvault-contego.service
      - copy: src={{files_path}}/files/services/tvault-contego.service  dest={{service_file_dest_path}}
      - ini_file: path={{service_file_dest_path}} section=Service option=User value="{{TVAULT_CONTEGO_EXT_USER}}" state=present
      - ini_file: path={{service_file_dest_path}} section=Service option=Group value="{{TVAULT_CONTEGO_EXT_USER}}" state=present
      - ini_file: path={{service_file_dest_path}} section=Service option=ExecStart value="{{TVAULT_CONTEGO_EXT_PYTHON}} {{TVAULT_CONTEGO_EXT_BIN}} {{CONFIG_FILES}}" state=present 
    when: is_nova_conf_present.stat.exists != true

  - block:
      - set_fact:
          service_file_dest_path: /etc/systemd/system/tvault-contego.service
      - copy: src={{files_path}}/files/services/tvault-contego.service  dest={{service_file_dest_path}}
      - ini_file: path={{service_file_dest_path}} section=Service option=User value="{{TVAULT_CONTEGO_EXT_USER}}" state=present
      - ini_file: path={{service_file_dest_path}} section=Service option=Group value="{{TVAULT_CONTEGO_EXT_USER}}" state=present
      - ini_file: path={{service_file_dest_path}} section=Service option=ExecStart value="{{TVAULT_CONTEGO_EXT_PYTHON}} {{TVAULT_CONTEGO_EXT_BIN}} {{CONFIG_FILES_1}}" state=present
    when: is_nova_conf_present.stat.exists == true
 
  - name: execute systemd daemon reload and enable service
    block:
      - shell: systemctl daemon-reload
  
      - name: enable tvault-contego service and reload it
        service: name=tvault-contego state=started enabled=yes
  when: ansible_lsb.codename == 'xenial' or ansible_lsb.codename == 'willy'

- block:
   - block: 
      - copy:     
         content: |
           description "TrilioVault Contego - Openstack Nova Compute Extension"
           author "TrilioData <info@triliodata.com>"
           start on (filesystem and net-device-up IFACE!=lo)
           stop on runlevel [016]
           respawn
           chdir /var/run
           pre-start script
               if [ ! -d /var/run/{{TVAULT_CONTEGO_EXT_USER}} ]; then
                   mkdir /var/run/{{TVAULT_CONTEGO_EXT_USER}}
                   chown root:{{TVAULT_CONTEGO_EXT_USER}} /var/run/{{TVAULT_CONTEGO_EXT_USER}}
               fi
               if [ ! -d /var/lock/{{TVAULT_CONTEGO_EXT_USER}} ]; then
                   mkdir -p /var/lock/{{TVAULT_CONTEGO_EXT_USER}}
                   chown root:{{TVAULT_CONTEGO_EXT_USER}} /var/lock/{{TVAULT_CONTEGO_EXT_USER}}
               fi
               if [ -f /var/log/nova/tvault-contego.log ]; then
                  chown {{TVAULT_CONTEGO_EXT_USER}}:{{TVAULT_CONTEGO_EXT_USER}} /var/log/nova/tvault-contego.log
               fi
           end script
           script
               exec start-stop-daemon --start --chuid {{TVAULT_CONTEGO_EXT_USER}} --exec {{TVAULT_CONTEGO_EXT_PYTHON}} {{TVAULT_CONTEGO_EXT_BIN}} -- {{CONFIG_FILES}}
           end script
         dest: /etc/init/tvault-contego.conf
     when: is_nova_conf_present.stat.exists != true

   - block:
      - copy:
         content: |
           description "TrilioVault Contego - Openstack Nova Compute Extension"
           author "TrilioData <info@triliodata.com>"
           start on (filesystem and net-device-up IFACE!=lo)
           stop on runlevel [016]
           respawn
           chdir /var/run
           pre-start script
               if [ ! -d /var/run/{{TVAULT_CONTEGO_EXT_USER}} ]; then
                   mkdir /var/run/{{TVAULT_CONTEGO_EXT_USER}}
                   chown root:{{TVAULT_CONTEGO_EXT_USER}} /var/run/{{TVAULT_CONTEGO_EXT_USER}}
               fi
               if [ ! -d /var/lock/{{TVAULT_CONTEGO_EXT_USER}} ]; then
                   mkdir -p /var/lock/{{TVAULT_CONTEGO_EXT_USER}}
                   chown root:{{TVAULT_CONTEGO_EXT_USER}} /var/lock/{{TVAULT_CONTEGO_EXT_USER}}
               fi
               if [ -f /var/log/nova/tvault-contego.log ]; then
                  chown {{TVAULT_CONTEGO_EXT_USER}}:{{TVAULT_CONTEGO_EXT_USER}} /var/log/nova/tvault-contego.log
               fi
           end script
           script
               exec start-stop-daemon --start --chuid {{TVAULT_CONTEGO_EXT_USER}} --exec {{TVAULT_CONTEGO_EXT_PYTHON}} {{TVAULT_CONTEGO_EXT_BIN}} -- {{CONFIG_FILES}}
           end script
         dest: /etc/init/tvault-contego.conf
     when: is_nova_conf_present.stat.exists == true

  when: ansible_lsb.codename != 'xenial' or ansible_lsb.codename != 'willy'

