{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- if .Values.manifests.daemonset_dms }}
{{- $envAll := . }}

{{- $serviceAccountName := printf "%s-%s" "triliovault-dms" .Values.labels.dms_compute.node_selector_key }}
{{ tuple $envAll "dms" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: triliovault-dms-{{ .Values.labels.dms_compute.node_selector_key }}
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "triliovault" "dms" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  selector:
    matchLabels:
{{ tuple $envAll "triliovault" "dms" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll "dms" | include "helm-toolkit.snippets.kubernetes_upgrades_daemonset" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "triliovault" "dms" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-etc-dms-hash: {{ tuple "configmap-etc-dms-compute.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-bin-dms-hash: {{ tuple "configmap-bin-dms.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        runAsUser: 42424
        fsGroup: 42424
      affinity:
{{ tuple $envAll "triliovault" "dms" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        {{ .Values.labels.dms_compute.node_selector_key }}: {{ .Values.labels.dms_compute.node_selector_value }}
{{ if .Values.conf.triliovault.docker_registry_auth_enabled }}
      imagePullSecrets:
        - name: triliovault-image-registry
{{ end }}
      initContainers:
{{ tuple $envAll "dms" $envAll.Values.pod.mounts.triliovault_dms.init_container | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
        - name: dms-init
{{ tuple $envAll "triliovault_dms_init" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ dict "envAll" $envAll "application" "triliovault" "container" "triliovault_dms_init" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /tmp/triliovault-dms-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: triliovault-dms-bin
              mountPath: /tmp/triliovault-dms-init.sh
              subPath: triliovault-dms-init.sh
              readOnly: true
            - name: run
              mountPath: /run
      containers:
        - name: triliovault-dms
{{ tuple $envAll "triliovault_dms" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.dms | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "triliovault" "container" "triliovault_dms" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/triliovault-dms.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/triliovault-dms.sh
                  - stop
          volumeMounts:
{{ dict "envAll" $envAll "objectType" "mountpoint" "secretPrefix" "triliovault-dms" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 12 }}
            - name: pod-tmp
              mountPath: /tmp
            - name: localtime
              mountPath: "/etc/localtime"
              readOnly: yes
            - name: pod-shared-triliovault-dms
              mountPath: /tmp/pod-shared-triliovault-dms
            - name: vartrilio
              mountPath: /var/trilio
            - name: varlibtrilio
              mountPath: /var/lib/trilio
              mountPropagation: Bidirectional
            - name: varlogtriliovaultdms
              mountPath: /var/log/triliovault
            - name: triliovault-dms-etc
              mountPath: /etc/triliovault-dms/server.conf
              subPath: server.conf
              readOnly: true
            - name: triliovault-datamover-bin
              mountPath: /tmp/triliovault-dms.sh
              subPath: triliovault-dms.sh
              readOnly: true
            - mountPath: /etc/nova/nova.conf.d
              name: nova-confd
            - name: varlibnova
              mountPath: /var/lib/nova
            - name: varliblibvirt
              mountPath: /var/lib/libvirt
            - name: run
              mountPath: /run
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: machine-id
              mountPath: /etc/machine-id
              readOnly: true
            - name: dev
              mountPath: /dev
              {{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "10" ) }}
              mountPropagation: HostToContainer
              {{- end }}
            - name: etciscsi
              mountPath: /etc/iscsi
              {{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "10" ) }}
              mountPropagation: HostToContainer
              {{- end }}
            - mountPath: /lib/modules
              name: libmodules
              readOnly: true
            {{- if .Values.multipathd_enabled }}
            - name: host-rootfs
              mountPath: /mnt/host-rootfs
              mountPropagation: HostToContainer
            - name: usrlocalsbin
              mountPath: /usr/local/sbin
            - name: runlock
              mountPath: /run/lock
            - name: triliovault-datamover-bin
              mountPath: /usr/local/sbin/multipath
              subPath: multipath
            - name: triliovault-datamover-bin
              mountPath: /usr/local/sbin/multipathd
              subPath: multipathd
            - name: triliovault-datamover-bin
              mountPath: /usr/local/sbin/iscsiadm
              subPath: iscsiadm
            - name: etcmultipath
              mountPath: /etc/multipath
              {{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "10" ) }}
              mountPropagation: Bidirectional
              {{- end }}
            - name: multipathconf
              mountPath: /etc/multipath.conf
            - mountPath: /var/lib/openstack/lock
              mountPropagation: Bidirectional
              name: lockpath
            - name: sysblock
              mountPath: /sys/block
              {{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "10" ) }}
              mountPropagation: HostToContainer
              {{- end }}
            {{- end }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_db_triliovault_datamover.auth.admin.secret.tls.internal "path" "/etc/mysql/certs" | include "helm-toolkit.snippets.tls_volume_mount" | indent 12 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.secrets.tls.datamover.datamover_api.internal "path" "/etc/triliovault_datamover/certs" | include "helm-toolkit.snippets.tls_volume_mount" | indent 12 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_messaging_datamover.auth.admin.secret.tls.internal "path" "/etc/rabbitmq/certs" | include "helm-toolkit.snippets.tls_volume_mount" | indent 12 }}
      volumes:
{{ dict "envAll" $envAll "objectType" "volume" "secretPrefix" "triliovault-dms" | include "helm-toolkit.snippets.kubernetes_ssl_objects" | indent 8 }}
        - name: pod-tmp
          emptyDir: {}
        - name: localtime
          hostPath:
            path: "/etc/localtime"
        - name: pod-shared-triliovault-dms
          emptyDir: {}
        - name: vartrilio
          hostPath:
            path: /var/trilio
        - name: varlibtrilio
          hostPath:
            path: /var/lib/trilio
        - name: varlogtriliovaultdms
          hostPath:
            path: /var/log/triliovault-dms
        - name: triliovault-dms-etc
          secret:
            secretName: triliovault-etc-dms-compute
            defaultMode: 0444
        - name: triliovault-datamover-bin
          configMap:
            name: triliovault-bin-datamover
            defaultMode: 0555
        - name: triliovault-dms-bin
          configMap:
            name: triliovault-dms-bin
            defaultMode: 0555
        - name: varlibnova
          hostPath:
            path: /var/lib/nova
        - emptyDir: {}
          name: nova-confd
        - name: varliblibvirt
          hostPath:
            path: /var/lib/libvirt
        - name: run
          hostPath:
            path: /run
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: machine-id
          hostPath:
            path: /etc/machine-id
        {{- if .Values.multipathd_enabled }}
        - name: host-rootfs
          hostPath:
            path: /
        - name: runlock
          hostPath:
            path: /run/lock
        - name: usrlocalsbin
          emptyDir: {}
        - name: etcmultipath
          hostPath:
            path: /etc/multipath
        - name: multipathconf
          hostPath:
            path: /etc/multipath.conf
            type: FileOrCreate
        - name: lockpath
          hostPath:
            path: /var/lib/openstack/lock
            type: DirectoryOrCreate
        - name: sysblock
          hostPath:
            path: /sys/block
        {{- end }}
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: dev
          hostPath:
            path: /dev
        - name: etciscsi
          hostPath:
            path: /etc/iscsi
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_db_triliovault_datamover.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.secrets.tls.datamover.datamover_api.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_messaging_datamover.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- end }}
