- name: Restart triliovault-datamover
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: "edpm_triliovault-datamover.service"

- name: Restart triliovault-dms
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: "edpm_triliovault-dms.service"
  listen: "restart-triliovault-dms"