---

- name: Copy Triliovault-cloudrc into WLM container
  template:
    src: triliovault-cloudrc
    dest: "{{ TRILIOVAULT_RC }}"
    mode: '0777'

- name: Verify cloudrc is present or not
  stat: path = "{{ TRILIOVAULT_RC }}"
  register: cld_rc_output
  delegate_to: localhost

- name: Get workloadmgr intenral endpoint ID
  shell: ". {{ TRILIOVAULT_RC }} && openstack endpoint list --insecure --service workloadmgr --interface internal --insecure -f value -c ID"
  register: int_endpt_id
  ignore_errors: True
  delegate_to: localhost
  when:
    - cld_rc_output.stat.exists == true

- set_fact:
    WLM_INTERNAL_ID: "{{ int_endpt_id.stdout }}"
  ignore_errors: True

- name: Get workloadmgr admin endpoint ID
  shell: ". {{ TRILIOVAULT_RC }} && openstack endpoint list --insecure --service workloadmgr --interface admin --insecure -f value -c ID"
  register: admn_endpt_id
  ignore_errors: True
  delegate_to: localhost
  when:
    - cld_rc_output.stat.exists == true

- set_fact:
    WLM_ADMN_ID: "{{ admn_endpt_id.stdout }}"
  ignore_errors: True

- name: Get workloadmgr public endpoint ID
  shell: ". {{ TRILIOVAULT_RC }} && openstack endpoint list --insecure --service workloadmgr --interface public --insecure -f value -c ID"
  register: pub_endpt_id
  ignore_errors: True
  delegate_to: localhost
  when:
    - cld_rc_output.stat.exists == true

- set_fact:
    WLM_PUB_ID: "{{ pub_endpt_id.stdout }}"
  ignore_errors: True

- name: Delete workloadmgr internal endpoint
  shell: ". {{ TRILIOVAULT_RC }} && openstack endpoint delete --insecure {{ WLM_INTERNAL_ID }}"
  ignore_errors: True
  delegate_to: localhost
  when:
    - WLM_INTERNAL_ID != ""
    - cld_rc_output.stat.exists == true

- name: Delete workloadmgr admin endpoint
  shell: ". {{ TRILIOVAULT_RC }} && openstack endpoint delete --insecure {{ WLM_ADMN_ID }}"
  ignore_errors: True
  delegate_to: localhost
  when:
    - WLM_ADMN_ID != ""
    - cld_rc_output.stat.exists == true

- name: Delete workloadmgr public endpoint
  shell: ". {{ TRILIOVAULT_RC }} && openstack endpoint delete --insecure {{ WLM_PUB_ID }}"
  ignore_errors: True
  delegate_to: localhost
  when:
    - WLM_PUB_ID != ""
    - cld_rc_output.stat.exists == true

