{{- if eq .Values.crdType "TVOControlPlane" }}
apiVersion: rabbitmq.openstack.org/v1beta1
kind: RabbitMq
metadata:
  name: trilio-rabbitmq-cluster
  namespace: {{ .Values.rabbitmq.common.namespace }}
spec:
  replicas: {{ .Values.rabbitmq.cluster.replicas }}
  delayStartSeconds: 30
  resources:
    requests:
      cpu: {{ .Values.rabbitmq.cluster.resources.requests.cpu }}
      memory: {{ .Values.rabbitmq.cluster.resources.requests.memory }}
    limits:
      cpu: {{ .Values.rabbitmq.cluster.resources.limits.cpu }}
      memory: {{ .Values.rabbitmq.cluster.resources.limits.memory }}
  persistence:
    storageClassName: {{ .Values.rabbitmq.cluster.persistence.storage_class_name }}
    storage: {{ .Values.rabbitmq.cluster.persistence.storage }}
  tls:
    secretName: cert-trilio-rabbitmq-cluster
    caSecretName: cert-trilio-rabbitmq-cluster
    disableNonTLSListeners: true
  override:
    service:
      metadata:
        annotations:
          metallb.universe.tf/address-pool: {{ .Values.common.metallb_address_pool }}
          dnsmasq.network.openstack.org/hostname: trilio-rabbitmq-cluster.trilio-openstack.svc
      spec:
        type: LoadBalancer
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - trilio-rabbitmq-cluster
            topologyKey: kubernetes.io/hostname
  terminationGracePeriodSeconds: {{ .Values.rabbitmq.cluster.termination_grace_period_seconds | default 604800 }}
{{- end }}
