{{- if eq .Values.crdType "TVOControlPlane" }}
apiVersion: {{ .Values.rabbitmq.operator.api_version }}
kind: OperatorGroup
metadata:
  name: trilio-openstack-operatorgroup
  namespace: {{ .Values.common.namespace }}
spec:
  targetNamespaces:
  - {{ .Values.common.namespace }}

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trilio-rabbitmq-cluster-operator
  namespace: {{ .Values.common.namespace }}
spec:
  channel: {{ .Values.rabbitmq.operator.channel }}
  name: {{ .Values.rabbitmq.operator.operator_name }}
  source: {{ .Values.rabbitmq.operator.source }}
  sourceNamespace: {{ .Values.rabbitmq.operator.source_namespace }}
  installPlanApproval: {{ .Values.rabbitmq.operator.install_plan_approval }}
  startingCSV: {{ .Values.rabbitmq.operator.starting_csv }}
{{- end }}
