apiVersion: v1
kind: Service
metadata:
  name: trilio-rabbitmq-lb
  namespace: trilio-openstack
  annotations:
    metallb.io/address-pool: internalapi
    dnsmasq.network.openstack.org/hostname: trilio-rabbitmq-cluster.trilio-openstack.svc
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: trilio-rabbitmq-cluster
    app.kubernetes.io/part-of: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: trilio-rabbitmq-cluster
  ports:
  - name: amqps
    port: 5671
    targetPort: 5671
    protocol: TCP
  - name: management-tls
    port: 15671
    targetPort: 15671
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
