{{- if eq .Values.crdType "TVOControlPlane" }}
{{- $svcName := "trilio-rabbitmq-lb" }}
{{- $svcNamespace := "trilio-openstack" }}
{{- $service := lookup "v1" "Service" $svcNamespace $svcName }}
{{- $externalIP := "" }}
{{- $externalIP = (index $service.status.loadBalancer.ingress 0).ip }}
apiVersion: network.openstack.org/v1beta1
kind: DNSData
metadata:
  name: trilio-rabbitmq-dns
  namespace: openstack
  labels:
    dnsmasqname: dns
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-10"
spec:
  dnsDataLabelSelectorValue: dnsdata
  hosts:
  - hostnames:
    - trilio-rabbitmq-cluster.trilio-openstack.svc
    ip: {{ $externalIP }}
    # oc get svc trilio-rabbitmq-lb -n trilio-openstack -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
{{- end }}