apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-job-sa
  namespace: trilio-openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wait-job-role
  namespace: trilio-openstack
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions", "installplans", "clusterserviceversions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["rabbitmq.com"]
    resources: ["rabbitmqclusters", "users"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wait-job-rb
  namespace: trilio-openstack
subjects:
  - kind: ServiceAccount
    name: wait-job-sa
roleRef:
  kind: Role
  name: wait-job-role
  apiGroup: rbac.authorization.k8s.io

---

{{- if eq .Values.crdType "TVOControlPlane" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trilio-tvo-deployment-patcher
  namespace: trilio-openstack
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
  resourceNames: ["messaging-topology-operator"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trilio-tvo-deployment-patcher
  namespace: trilio-openstack
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-12"
subjects:
- kind: ServiceAccount
  name: trilio-rabbitmq
  namespace: trilio-openstack
roleRef:
  kind: Role
  name: trilio-tvo-deployment-patcher
  apiGroup: rbac.authorization.k8s.io
{{- end }}
