{{- if eq .Values.crdType "TVOControlPlane" }}
{{- $rabbitmqSecretName := default "trilio-openstack-secret" .Values.openstack.rabbitmq_admin_secret_name }}
{{- $rabbitSecret := lookup "v1" "Secret" "trilio-openstack" $rabbitmqSecretName }}
{{- if $rabbitSecret }}
  {{- $rabbitPassword = $rabbitSecret.data.RabbitAdminPassword }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: trilio-rabbitmq-admin
  namespace: trilio-openstack
type: Opaque
data:
  username: {{ .Values.rabbitmq.common.admin_user | b64enc | quote }}
  password: "{{ $rabbitPassword }}"
{{- end }}