{{- if eq .Values.crdType "TVOControlPlane" }}
{{- $rabbitSecret := lookup "v1" "Secret" "trilio-openstack" "trilio-openstack-secret" }}
{{- if and $rabbitSecret (hasKey $rabbitSecret.data "RabbitAdminPassword") }}
{{- $rabbitPassword := get $rabbitSecret.data "RabbitAdminPassword" }}
apiVersion: v1
kind: Secret
metadata:
  name: trilio-rabbitmq-admin-credentials
  namespace: trilio-openstack
type: Opaque
data:
  username: {{ .Values.rabbitmq.common.admin_user | b64enc | quote }}
  password: {{ $rabbitPassword | quote }}
{{- else }}
{{- fail "Secret 'trilio-openstack-secret' missing or missing key 'RabbitAdminPassword'" }}
{{- end }}
{{- end }}

