# Job 1: Wait for RabbitMQ Operator Installation
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-rabbitmq-operator
  namespace: trilio-openstack
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-14"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: wait-job-sa
      restartPolicy: OnFailure
      containers:
        - name: wait-for-rabbitmq-operator
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -xc
            - |
              csv_name=$(oc get csv -n {{ .Values.rabbitmq.common.namespace }} -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep {{ .Values.rabbitmq.operator.operator_name }})
              until [ -n "$csv_name" ]; do
                echo "Waiting for RabbitMQ Operator CSV...";
                sleep 10;
                csv_name=$(oc get csv -n {{ .Values.rabbitmq.common.namespace }} -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep {{ .Values.rabbitmq.operator.operator_name }})
              done
              while true; do
                phase=$(oc get csv "$csv_name" -n {{ .Values.rabbitmq.common.namespace }} -o jsonpath='{.status.phase}')
                if [ "$phase" = "Succeeded" ]; then
                  echo "RabbitMQ Operator installed."
                  break
                fi
                echo "Waiting for RabbitMQ Operator CSV to be Succeeded... Current phase: $phase"
                sleep 10
              done
---
# Job 2: Wait for RabbitMQ Cluster CR Creation
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-rabbitmq-cluster
  namespace: trilio-openstack
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-12"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: wait-job-sa
      restartPolicy: OnFailure
      containers:
        - name: wait-for-rabbitmq-cluster
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -xc
            - |
              until oc get rabbitmqcluster -n {{ .Values.rabbitmq.common.namespace }} | grep -q trilio-rabbitmq-cluster; do
                echo "Waiting for RabbitMQ Cluster CR...";
                sleep 10;
              done
              oc wait --for=condition=Ready rabbitmqcluster/trilio-rabbitmq-cluster -n {{ .Values.rabbitmq.common.namespace }} --timeout=120s
              echo "RabbitMQ Cluster is ready."
---
# Job 3: Wait for Messaging Topology Operator Installation
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-messaging-topology-operator
  namespace: trilio-openstack
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: wait-job-sa
      restartPolicy: OnFailure
      containers:
        - name: wait-for-messaging-topology-operator
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -xc
            - |
              csv_name=$(oc get csv -n {{ .Values.rabbitmq.common.namespace }} -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep rabbitmq-messaging-topology-operator)
              until [ -n "$csv_name" ]; do
                echo "Waiting for Messaging Topology Operator CSV...";
                sleep 10;
                csv_name=$(oc get csv -n {{ .Values.rabbitmq.common.namespace }} -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' | grep rabbitmq-messaging-topology-operator)
              done
              while true; do
                phase=$(oc get csv "$csv_name" -n {{ .Values.rabbitmq.common.namespace }} -o jsonpath='{.status.phase}')
                if [ "$phase" = "Succeeded" ]; then
                  echo "Messaging Topology Operator installed."
                  break
                fi
                echo "Waiting for Messaging Topology Operator CSV to be Succeeded... Current phase: $phase"
                sleep 10
              done
---
# Job 4: Wait for RabbitMQ Admin User CR Creation
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-rabbitmq-admin-user
  namespace: trilio-openstack
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-8"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: wait-job-sa
      restartPolicy: OnFailure
      containers:
        - name: wait-for-rabbitmq-admin-user
          image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/sh
            - -xc
            - |
              until oc get users.rabbitmq.com -n {{ .Values.rabbitmq.common.namespace }} | grep -q {{ .Values.rabbitmq.admin_user.name }}; do
                echo "Waiting for RabbitMQ Admin User CR...";
                sleep 10;
              done
              oc wait --for=condition=Ready users.rabbitmq.com/{{ .Values.rabbitmq.admin_user.name }} -n {{ .Values.rabbitmq.common.namespace }} --timeout=120s
              echo "RabbitMQ Admin User is ready."
