FROM kolla/centos-binary-horizon:ussuri
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="centos-binary-trilio-horizon-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="TrilioVault Horizon Plugin" \
      description="TrilioVault Horizon Plugin for Kolla-ansible deployed OpenStack on centos platform"

##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf install python3-tvault-horizon-plugin python3-workloadmgrclient-el8 -y
RUN rm /etc/yum.repos.d/trilio.repo

##Move necessary files
ADD usr/share/openstack-dashboard/openstack_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
ADD usr/share/openstack-dashboard/openstack_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
