
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-trilio-backup-target-<BACKUP_TARGET_NAME>
data:
  trilio_env.yml: |
    triliovault_datamover_image: "docker.io/trilio/trilio-datamover:6.1.0-stable-19-rhosp18.0"
    triliovault_backup_target:
      backup_target_name: '<BACKUP_TARGET_NAME>'
      backup_target_type: 'nfs'
      is_default: False
      nfs_shares: '192.168.2.30:/nfs/share'
      nfs_options: 'nolock,soft,timeo=600,intr,lookupcache=none,nfsvers=3,retrans=10'