---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-trilio-datamover
data:
  trilio_env.yml: |
    rabbit_host: "rabbitmq.openstack.svc"
    rabbit_port: "5671"
    rabbit_ssl: true
    database_host: "openstack.openstack.svc"
    database_port: "3306"
    cinder_backend_ceph: true
    libvirt_images_rbd_ceph_conf: "/etc/ceph/ceph.conf"
    ceph_cinder_user: "cinder"
    oslomsg_rpc_use_ssl: true
    triliovault_datamover_image: "registry.connect.redhat.com/trilio/trilio-datamover-rhoso:6.0.0-stable-19-rhosp18.0"
    triliovault_wlm_image: "registry.connect.redhat.com/trilio/trilio-wlm:6.0.0-stable-19-rhosp18.0"
    trilio_container_registry_login_enabled: true
    trilio_container_registry_username: ""
    trilio_container_registry_url: "registry.connect.redhat.com"
    triliovault_backup_targets:
      - backup_target_name: 'BT1_S3'
        backup_target_type: 's3'
        is_default: False
        s3_type: 'amazon_s3'
        s3_access_key: ''
        s3_secret_key: ''
        s3_region_name: ''
        s3_bucket: ''
        s3_endpoint_url: ''
        s3_signature_version: 'default'
        s3_auth_version: 'DEFAULT'
        s3_ssl_enabled: true
        s3_ssl_verify: true
        s3_self_signed_cert: false
        s3_bucket_object_lock_enabled: false
      - backup_target_name: 'BT2_Other_S3'
        backup_target_type: 's3'
        is_default: True
        s3_type: 'other_s3'
        s3_access_key: 'ACCESSKEY2'
        s3_secret_key: 'SECRETKEY2'
        s3_region_name: 'REGION2'
        s3_bucket: 'BUCKET2'
        s3_endpoint_url: 'ENDPOINT_URL2'
        s3_signature_version: 'default'
        s3_auth_version: 'DEFAULT'
        s3_bucket_object_lock_enabled: false
        s3_ssl_enabled: true
        s3_ssl_verify: true
        s3_self_signed_cert: true
        s3_ssl_ca_cert: |
          SSL_CERT_LINE_1
          SSL_CERT_LINE_2
          SSL_CERT_LINE_N
    - backup_target_name: 'BT3_NFS'
        backup_target_type: 'nfs'
        is_default: false
        nfs_shares: '192.168.2.3:/nfs/share'
        nfs_options: 'nolock,soft,timeo=600,intr,lookupcache=none,nfsvers=3,retrans=10'
