---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-trilio-backup-target-<BACKUP_TARGET_NAME>
data:
  trilio_env.yml: |
    triliovault_wlm_image: "docker.io/trilio/trilio-wlm:6.1.0-stable-19-rhosp18.0"
    triliovault_backup_target:
      backup_target_name: '<BACKUP_TARGET_NAME>'
      backup_target_type: 's3'
      is_default: False
      s3_type: 'amazon_s3'
      s3_region_name: ''
      s3_bucket: ''
      s3_endpoint_url: ''
      s3_signature_version: 'default'
      s3_auth_version: 'DEFAULT'
      s3_bucket_object_lock_enabled: false
      s3_ssl_enabled: true
      s3_ssl_verify: true
      s3_self_signed_cert: false