---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-trilio-datamover
data:
  trilio_env.yml: |
    rabbit_host: "rabbitmq.openstack.svc"
    rabbit_port: "5671"
    rabbit_ssl: true
    rabbit_quorum_queue: false
    database_host: "openstack.openstack.svc"
    database_port: "3306"
    keystone_auth_url: "https://keystone.openstack.svc:5000/v3"
    keystone_ssl_verify: true
    cinder_backend_ceph: true
    libvirt_images_rbd_ceph_conf: "/etc/ceph/ceph.conf"
    ceph_cinder_user: "cinder"
    oslomsg_rpc_use_ssl: true
    triliovault_datamover_image: "registry.connect.redhat.com/trilio/trilio-datamover-rhoso:6.0.0-stable-19-rhosp18.0"
    triliovault_wlm_image: "registry.connect.redhat.com/trilio/trilio-wlm:6.0.0-stable-19-rhosp18.0"
    triliovault_dms_image: "registry.connect.redhat.com/trilio/trilio-dms-rhoso:6.0.0-stable-19-rhosp18.0"
    trilio_container_registry_login_enabled: true
    trilio_container_registry_username: ""
    trilio_container_registry_url: "registry.connect.redhat.com"