apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: trilio-datamover
spec:
  deployOnAllNodeSets: true
  label: dataplane-deployment-custom-service
  openStackAnsibleEERunnerImage: docker.io/trilio/rhoso-ansible-runner:6.1.0-stable-1-rhosp18.0
  edpmServiceType: trilio-datamover
  playbookContents: |
    - hosts: all
      vars_files:
        - /var/lib/openstack/configs/trilio-datamover/trilio_env.yml
      tasks:
        - name: Execute trilio-datamover role
          import_role:
            name: trilio-datamover
  dataSources:
    - configMapRef:
        name: cm-trilio-datamover
    - secretRef:
        name: trilio-openstack-secret

