kind: OpenStackDataPlaneDeployment
metadata:
  name: edpm-trilio-add-backup-target-<BACKUP_TARGET_NAME>
spec:
  nodeSets:
    - openstack-edpm-ipam
  servicesOverride:
    - trilio-add-backup-target-<BACKUP_TARGET_NAME>
