---

- name: Collect static files for horizon
  shell: "{{virtual_env}} && {{PYTHON_VERSION}} {{ MANAGE_FILE }}  collectstatic --noinput"
  notify:
     - restart webserver

- name: compress the collected files
  shell: "{{virtual_env}} && nohup {{PYTHON_VERSION}} {{ MANAGE_FILE }} compress --force"
  retries: 3
  delay: 3
  register: compress_result
  until: compress_result.rc == 0
  notify:
     - restart webserver

- name: write content into destination file - sync_static.py
  template: src="sync_static.py" dest="/tmp/sync_static.py"

- name: Change the working directory to horizon and execute shell command
  shell: "{{virtual_env}} && {{PYTHON_VERSION}} {{ MANAGE_FILE }} shell < /tmp/sync_static.py"
  args:
       chdir: "{{HORIZON_PATH}}"
  register: data
  notify:
    - restart webserver

- name: Change the working directory to horizon and execute collectstatic --noinput with data
  shell: "{{virtual_env}} && {{PYTHON_VERSION}} {{ MANAGE_FILE }}  collectstatic --noinput {{data.stdout}}"
  args:
    chdir: "{{HORIZON_PATH}}"
  notify:
     - restart webserver

- name: remove temporary file - sync_static.py
  file: path=/tmp/sync_static.py state=absent

- name: Get os_local_settings_path
  shell: find / -type d -path /sys -prune -o -name "*local_settings.d" 2>/dev/null | grep -E 'openstack_dashboard|horizon'
  register: os_local_settings_path

- name: Set file names
  set_fact:
    file_names: "{{ os_local_settings_path.stdout.split('\n')}}"
  when: os_local_settings_path.stdout != ""

- set_fact:
    os_local_settings_path_length: "{{ file_names|length }}"
  when: os_local_settings_path.stdout != ""

- name: HORIZON_CONFIG
  shell: . /openstack/venvs/horizon*/bin/activate && echo "HORIZON_CONFIG['customization_module'] = 'dashboards.overrides'" > `echo $os_local_settings_path | cut -d ' ' -f1 |{ read trilio_setting_path ; echo $trilio_setting_path/_001_trilio_dashboard.py ; }`
  when:
    - os_local_settings_path != ""
    - os_local_settings_path_length == 1

- name: Display local_settings.d path
  debug:
    msg: "local_settings.d path: {{file_names}}"
  when:
    - os_local_settings_path != ""

- name: Give the notification to run command manually inside horizon container
  debug:
    msg: ". /openstack/venvs/horizon*/bin/activate && echo \"HORIZON_CONFIG['customization_module'] = 'dashboards.overrides'\" > `echo /openstack/venvs/horizon*/lib/python3.6/site-packages/<find relative local_settings.d directory path inside openstack-dashboards> | cut -d ' ' -f1 |{ read trilio_setting_path ; echo $trilio_setting_path/_001_trilio_dashboard.py ; }`"
  when:
    - os_local_settings_path != ""
    - os_local_settings_path_length > "1"

- debug:
    msg: "\033[33m WARNING: Unable to locate local_settings.d on system. Trilio quota feature on dashboard may not work. \033[0m"
    verbosity: "{{ verbosity_level }}"
  when: os_local_settings_path == ""

