---

- name: find location of manage.py
  shell: "find {{ ENV_PATH }}  -name '*manage.py' | grep -E 'openstack-dashboard|horizon|bin'"
  register: output

- set_fact:
    MANAGE_FILE : "{{output.stdout}}"

- debug:
    msg: "manage.py is found at :{{MANAGE_FILE}}"
    verbosity: "{{ verbosity_level }}"
