---
- name: Found location of trilio.pth file
  shell: "{{ virtual_env }} && {{ PYTHON_VERSION }} -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())'"
  register: VENV_PKGLIB

- set_fact:
    TRILIO_FILE : "{{VENV_PKGLIB.stdout}}/trilio.pth"

- name: Removing trilio.pth file
  file:
    path: "{{ TRILIO_FILE }}"
    state: absent

