---
- name: Include vars of /tmp/connection_string into the 'tvault_vars' variable.
  include_vars:
    file: /tmp/connection_string
    name: tvault_vars
  delegate_to: localhost

- name: Deploy user provided Rabbitmq ssl certs and Key file
  import_tasks: /opt/openstack-ansible/playbooks/roles/ansible-datamover-api/tasks/get_rabbitmq_ssl_cert.yml
  when: tvault_vars.rabbit_ssl == true

- block:
  - name: Create {{VAULT_S3_SSL_CERT_DIR}} directory
    file: name="{{VAULT_S3_SSL_CERT_DIR}}"  state=directory

  - name: check {{VAULT_S3_SSL_CERT}} is present or not
    stat: path="{{VAULT_S3_SSL_CERT}}"
    register: tvault_ssl_cert_output
    delegate_to: localhost

  - name: Deploy user provided Tvault s3 {{VAULT_S3_SSL_CERT}}
    copy:
      src: "{{VAULT_S3_SSL_CERT}}"
      dest: "{{VAULT_S3_SSL_CERT_PATH}}"
    when:
      - tvault_ssl_cert_output.stat.exists == true
  when:
      - VAULT_S3_SSL_CERT != ""
      - S3|bool == True
      - s3_type == Other_S3_Compatible


- name: Create tvault-contego.conf file
  template:
     src: tvault-contego.conf.j2
     dest: "{{TVAULT_CONTEGO_CONF}}"

- name: Ensure /etc/tvault-contego/tvault-contego.conf has root:nova with 640
  file: name="/etc/tvault-contego/tvault-contego.conf" owner=root group=nova mode=0640
