---

- name: check if Nova conf file is present or not
  stat: path="{{NOVA_CONF_FILE}}"
  register: nova_conf_file

- name: Fail if Nova conf file is not present
  fail: msg="{{NOVA_CONF_FILE}} is not present"
  when: nova_conf_file.stat.exists != true

- name: check if tvault contego external bin is present or not
  stat: path="{{TVAULT_CONTEGO_EXT_BIN}}"
  register: tvault_contego_ext_bin

- debug: msg="tvault_contego_ext_bin:{{tvault_contego_ext_bin}}" verbosity={{verbosity_level}}

- name: Fail if tvault_contego_ext_bin directory is not present
  fail: msg="vault_contego_external_bin directory is not present"
  when: tvault_contego_ext_bin.stat.exists != true

- name: check if tvault contego conf file is present or not
  stat: path="{{TVAULT_CONTEGO_CONF}}"
  register: tvault_contego_conf

- name: create /etc/tvault-contego dir if tvault_contego_cof file is not present
  file: path=/etc/tvault-contego state=directory
  when: tvault_contego_conf.stat.exists != true

