---
- name: ensure virtenv dir(/home/tvault) is deleted
  file: path={{TVAULT_CONTEGO_VIRTENV}} state=absent

- name: ensure logrotate file is removed
  file: path=/etc/logrotate.d/tvault-contego state=absent

- name: ensure tvault contego conf file is deleted
  file: path={{TVAULT_CONTEGO_CONF}} state=absent

- name: ensure tvault contego log file  is deleted
  file: path=/var/log/nova/tvault-contego.log state=absent

- name: ensure tvault-contego service file is deleted if os release is rhel7
  file: path=/etc/systemd/system/tvault-contego.service state=absent

- name: ensure tvault-object-store service file is deleted if os release is rhel7
  file: path=/etc/systemd/system/tvault-object-store.service state=absent

- name: ensure tvault-swift service file is deleted if os release is rhel7
  file: path=/etc/systemd/system/tvault-swift.service state=absent 

- name: reload daemon
  shell: systemctl daemon-reload
             
- name: grep mountpath
  shell: df -h | grep '{{TVAULT_DATA_DIR}}' | awk -F' ' '{print $6}'
  register: mount_path

- debug: msg="{{mount_path.stdout}}"  verbosity={{verbosity_level}}

- set_fact:
    mount_list : "{{ mount_path.stdout.split('\n') }}"

- debug : msg="mount list is:{{mount_list}}"

- name:  unmount mountpath incase contego is failed to unmount
  shell: umount {{item}}
  with_items: "{{mount_list}}"
  when: mount_path.stdout != ""

