---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: triliovault-wlm-public-svc
  namespace: openstack
spec:
  secretName: cert-triliovault-wlm-public-svc
  issuerRef:
    name: rootca-public
    kind: Issuer
  duration: 43800h0m0s
  commonName: triliovault-wlm-public.trilio-openstack.svc
  dnsNames:
    - triliovault-wlm-public.trilio-openstack.svc
    - triliovault-wlm-public.trilio-openstack.svc.cluster.local
    - triliovault-wlm-public-trilio-openstack.$PUBLIC_ENDPOINT_DOMAIN

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: triliovault-wlm-internal-svc
  namespace: openstack
spec:
  secretName: cert-triliovault-wlm-internal-svc  
  issuerRef:
    name: rootca-internal
    kind: Issuer
  duration: 43800h0m0s
  commonName: triliovault-wlm-internal.trilio-openstack.svc
  dnsNames:
    - triliovault-wlm-internal.trilio-openstack.svc
    - triliovault-wlm-internal.trilio-openstack.svc.cluster.local

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: triliovault-datamover-public-svc
  namespace: openstack
spec:
  secretName: cert-triliovault-datamover-public-svc
  issuerRef:
    name: rootca-public
    kind: Issuer
  duration: 43800h0m0s
  commonName: triliovault-datamover-public.trilio-openstack.svc
  dnsNames:
    - triliovault-datamover-public.trilio-openstack.svc
    - triliovault-datamover-public.trilio-openstack.svc.cluster.local
    - triliovault-datamover-public-trilio-openstack.$PUBLIC_ENDPOINT_DOMAIN

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: triliovault-datamover-internal-svc
  namespace: openstack
spec:
  secretName: cert-triliovault-datamover-internal-svc  
  issuerRef:
    name: rootca-internal
    kind: Issuer
  duration: 43800h0m0s
  commonName: triliovault-datamover-internal.trilio-openstack.svc
  dnsNames:
    - triliovault-datamover-internal.trilio-openstack.svc
    - triliovault-datamover-internal.trilio-openstack.svc.cluster.local

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trilio-rabbitmq-cluster
  namespace: openstack
spec:
  secretName: cert-trilio-rabbitmq-cluster
  issuerRef:
    name: rootca-public
    kind: Issuer
  duration: 43800h0m0s
  commonName: trilio-rabbitmq-cluster.trilio-openstack.svc
  dnsNames:
    - trilio-rabbitmq-cluster.trilio-openstack.svc
