#!/usr/bin/env python3
"""
create_backup_targets_62.py

Reads backup-targets-migration.yaml (generated by export_backup_targets.py)
and creates each backup target in T4O 6.2.

T4O 6.2 backup target creation flow:

  S3 backup targets:
    1. Build a Barbican secret JSON payload from the 6.1 S3 config fields.
    2. Store the secret in OpenStack Barbican.
    3. Create the WLM backup target with the Barbican secret_ref.

  NFS backup targets:
    1. Create the WLM backup target directly with the NFS export path and options.

Authentication uses standard OpenStack environment variables (source your cloudrc):
  OS_AUTH_URL, OS_USERNAME, OS_PASSWORD, OS_PROJECT_NAME,
  OS_USER_DOMAIN_NAME, OS_PROJECT_DOMAIN_NAME, OS_REGION_NAME
  OS_CACERT  (optional: CA bundle path for self-signed certificates)

Usage:
  source /path/to/cloudrc
  python3 create_backup_targets_62.py [options]

Options:
  --input     Path to migration YAML  (default: backup-targets-migration.yaml)
  --insecure  Disable SSL certificate verification
  --dry-run   Print actions without executing them

Prerequisites:
  - T4O 6.2 deployed and WLM service accessible
  - OpenStack Barbican service running
  - python3-pyyaml   (dnf install python3-pyyaml)
  - python3-requests (dnf install python3-requests)
"""

import argparse
import json
import os
import sys

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.  dnf install python3-pyyaml", file=sys.stderr)
    sys.exit(1)

try:
    import requests
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
except ImportError:
    print("ERROR: requests is required.  dnf install python3-requests", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Field mapping: T4O 6.1 export YAML → Barbican secret JSON keys
# ---------------------------------------------------------------------------

# Required Barbican secret keys for S3 backup targets (ref: trilio-dms DEPLOYMENT_GUIDE.md)
S3_FIELD_MAP = {
    "s3_access_key":               "VAULT_S3_ACCESS_KEY_ID",
    "s3_secret_key":               "VAULT_S3_SECRET_ACCESS_KEY",
    "s3_bucket":                   "VAULT_S3_BUCKET",
    "s3_endpoint_url":             "VAULT_S3_ENDPOINT_URL",
    "s3_region_name":              "VAULT_S3_REGION_NAME",
    "s3_signature_version":        "VAULT_S3_SIGNATURE_VERSION",
    "s3_auth_version":             "VAULT_S3_AUTH_VERSION",
    "s3_ssl_enabled":              "VAULT_S3_SSL",
    "s3_ssl_verify":               "VAULT_S3_SSL_VERIFY",
    "s3_ssl_ca_cert":              "VAULT_S3_SSL_CERT",
    "s3_bucket_object_lock_enabled": "BUCKET_OBJECT_LOCK",
}

# Defaults for optional Barbican keys not present in 6.1 config
S3_DEFAULTS = {
    "VAULT_STORAGE_TYPE":            "s3",
    "VAULT_S3_MAX_POOL_CONNECTIONS": "500",
    "VAULT_S3_READ_TIMEOUT":         "30",
    "VAULT_S3_MAX_ATTEMPTS":         "3",
    "VAULT_DATA_DIRECTORY_OLD":      "/var/triliovault",
    "LOG_CONFIG_APPEND":             "/etc/triliovault-object-store/object_store_logging.conf",
    "HELPER_COMMAND":                "sudo /usr/bin/trilio-dms-rootwrap /etc/triliovault-dms/rootwrap.conf privsep-helper",
    "METADATA_CACHE_ENABLED":        "True",
    "USE_MANIFEST_SUFFIX":           "False",
}


# ---------------------------------------------------------------------------
# OpenStack / Barbican / WLM helpers
# ---------------------------------------------------------------------------

def get_env(key, required=True):
    val = os.environ.get(key, "")
    if required and not val:
        print(f"ERROR: {key} is not set. Source your cloudrc file.", file=sys.stderr)
        sys.exit(1)
    return val


def keystone_auth(verify):
    """Authenticate against Keystone v3. Returns (token, project_id, catalog)."""
    auth_url   = get_env("OS_AUTH_URL").rstrip("/")
    username   = get_env("OS_USERNAME")
    password   = get_env("OS_PASSWORD")
    proj_name  = get_env("OS_PROJECT_NAME")
    user_dom   = get_env("OS_USER_DOMAIN_NAME", required=False) or "Default"
    proj_dom   = get_env("OS_PROJECT_DOMAIN_NAME", required=False) or "Default"

    body = {
        "auth": {
            "identity": {
                "methods": ["password"],
                "password": {
                    "user": {
                        "name": username,
                        "password": password,
                        "domain": {"name": user_dom},
                    }
                },
            },
            "scope": {
                "project": {
                    "name": proj_name,
                    "domain": {"name": proj_dom},
                }
            },
        }
    }

    url = f"{auth_url}/v3/auth/tokens"
    print(f"  Authenticating to Keystone: {url}")
    resp = requests.post(url, json=body, verify=verify)
    if resp.status_code not in (200, 201):
        print(f"ERROR: Keystone auth failed ({resp.status_code}): {resp.text}", file=sys.stderr)
        sys.exit(1)

    token      = resp.headers["X-Subject-Token"]
    body_resp  = resp.json()
    project_id = body_resp["token"]["project"]["id"]
    catalog    = body_resp["token"].get("catalog", [])
    return token, project_id, catalog


def get_endpoint(catalog, svc_type, interface=None, region=None):
    """Extract an endpoint URL from the Keystone service catalog."""
    interface = interface or os.environ.get("OS_INTERFACE", "public")
    region    = region    or os.environ.get("OS_REGION_NAME", "")
    for svc in catalog:
        if svc.get("type") != svc_type:
            continue
        for iface in (interface, "internal", "public"):
            for ep in svc.get("endpoints", []):
                if region and ep.get("region_id") != region:
                    continue
                if ep.get("interface") == iface:
                    return ep["url"].rstrip("/")
    return None


# ---------------------------------------------------------------------------
# Barbican
# ---------------------------------------------------------------------------

def store_barbican_secret(barbican_base, token, secret_name, payload, verify, dry_run):
    """
    POST /v1/secrets  — store a JSON payload as a Barbican secret.
    Returns the secret_ref URL string, or None on failure.
    """
    url = f"{barbican_base}/v1/secrets"
    body = {
        "name":         secret_name,
        "payload":      json.dumps(payload),
        "payload_content_type": "application/json",
        "content_types": {"default": "application/json"},
    }
    headers = {
        "X-Auth-Token": token,
        "Content-Type": "application/json",
    }

    if dry_run:
        print(f"    [DRY-RUN] POST {url}")
        print(f"    Secret name   : {secret_name}")
        print(f"    Payload keys  : {list(payload.keys())}")
        return "http://barbican-dry-run/v1/secrets/dry-run-uuid"

    resp = requests.post(url, json=body, headers=headers, verify=verify)
    if resp.status_code in (200, 201):
        secret_ref = resp.json().get("secret_ref", "")
        print(f"    Barbican secret created: {secret_ref}")
        return secret_ref
    else:
        print(f"    ERROR: Barbican secret creation failed "
              f"(HTTP {resp.status_code}): {resp.text}")
        return None


def build_s3_barbican_payload(bt):
    """Build the Barbican secret JSON payload from a 6.1 S3 backup target dict."""
    payload = dict(S3_DEFAULTS)

    for field_61, vault_key in S3_FIELD_MAP.items():
        val = bt.get(field_61)
        if val is None:
            continue
        # Booleans must be stored as "True"/"False" strings
        if isinstance(val, bool):
            payload[vault_key] = str(val)
        else:
            payload[vault_key] = val

    # VAULT_STORAGE_NFS_EXPORT is the S3 filesystem_export representation
    # (used by s3vaultfuse as the virtual NFS path for the bucket)
    if bt.get("s3_bucket"):
        endpoint = bt.get("s3_endpoint_url", "").rstrip("/")
        bucket   = bt.get("s3_bucket", "")
        payload["VAULT_STORAGE_NFS_EXPORT"] = f"{endpoint}/{bucket}" if endpoint else bucket

    return payload


# ---------------------------------------------------------------------------
# WLM backup target
# ---------------------------------------------------------------------------

def create_wlm_backup_target(wlm_base, token, project_id, bt, secret_ref,
                              verify, dry_run):
    """
    POST /v1/{project_id}/backup_targets  — register a backup target in WLM.
    Returns True on success, False on failure.
    """
    bt_name = bt.get("backup_target_name", "")
    bt_type = bt.get("backup_target_type", "")
    url     = f"{wlm_base}/v1/{project_id}/backup_targets"

    if bt_type == "s3":
        metadata = {
            "btt_name":   bt_name,
            "secret_ref": secret_ref,
        }
    elif bt_type == "nfs":
        metadata = {
            "btt_name":         bt_name,
            "filesystem_export": bt.get("nfs_shares", ""),
        }
        if bt.get("nfs_options"):
            metadata["nfs_mount_opts"] = bt["nfs_options"]
    else:
        print(f"  ERROR: Unknown backup_target_type '{bt_type}'. Skipping '{bt_name}'.")
        return False

    body = {
        "backup_target": {
            "type":       bt_type,
            "is_default": 1 if bt.get("is_default") else 0,
            "immutable":  1 if bt.get("s3_bucket_object_lock_enabled") else 0,
            "metadata":   metadata,
        }
    }

    headers = {
        "X-Auth-Token":      token,
        "X-Auth-Project-Id": project_id,
        "Content-Type":      "application/json",
        "Accept":            "application/json",
        "User-Agent":        "python-workloadmgrclient",
    }

    if dry_run:
        print(f"    [DRY-RUN] POST {url}")
        print(f"    Payload: {json.dumps(body, indent=6)}")
        return True

    resp = requests.post(url, json=body, headers=headers, verify=verify)
    if resp.status_code in (200, 201):
        bt_id = resp.json().get("backup_target", {}).get("id", "")
        print(f"    WLM backup target created: id={bt_id}")
        return True
    else:
        print(f"    ERROR: WLM backup target creation failed "
              f"(HTTP {resp.status_code}): {resp.text}")
        return False


# ---------------------------------------------------------------------------
# Per-backup-target orchestration
# ---------------------------------------------------------------------------

def process_backup_target(bt, barbican_base, wlm_base, token, project_id,
                           verify, dry_run):
    """Handle one backup target — Barbican secret (if S3) + WLM registration."""
    bt_name = bt.get("backup_target_name", "?")
    bt_type = bt.get("backup_target_type", "?")
    print(f"\n  [{bt_type.upper()}] '{bt_name}'  default={bt.get('is_default', False)}")

    secret_ref = None

    if bt_type == "s3":
        if not bt.get("s3_access_key") or not bt.get("s3_secret_key"):
            print(f"    WARNING: S3 credentials missing for '{bt_name}'. "
                  "Edit backup-targets-migration.yaml and retry.")
            return False

        print(f"    Step 1/2: Store credentials in Barbican")
        payload    = build_s3_barbican_payload(bt)
        secret_ref = store_barbican_secret(
            barbican_base, token, bt_name, payload, verify, dry_run
        )
        if not secret_ref:
            return False

        print(f"    Step 2/2: Register backup target in WLM")

    elif bt_type == "nfs":
        print(f"    Step 1/1: Register NFS backup target in WLM")

    else:
        print(f"    ERROR: Unknown type '{bt_type}'. Skipping.")
        return False

    return create_wlm_backup_target(
        wlm_base, token, project_id, bt, secret_ref, verify, dry_run
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Create T4O 6.2 backup targets from migration YAML "
                    "(Barbican secret + WLM registration)"
    )
    parser.add_argument(
        "--input", default="backup-targets-migration.yaml",
        help="Migration YAML from export_backup_targets.py "
             "(default: backup-targets-migration.yaml)"
    )
    parser.add_argument("--insecure", action="store_true",
                        help="Disable SSL certificate verification")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print actions without executing them")
    args = parser.parse_args()

    # SSL verification
    if args.insecure:
        requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
        verify = False
    else:
        ca_cert = os.environ.get("OS_CACERT", "")
        verify  = ca_cert if ca_cert else True

    # Load migration YAML
    print(f"Reading backup targets from: {args.input}")
    try:
        with open(args.input) as f:
            migration = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"ERROR: {args.input} not found. Run export_backup_targets.py first.",
              file=sys.stderr)
        sys.exit(1)

    backup_targets = migration.get("backup_targets", [])
    if not backup_targets:
        print("No backup targets found in migration file. Exiting.")
        sys.exit(0)

    print(f"Found {len(backup_targets)} backup target(s).\n")

    # Keystone auth
    print("Authenticating with OpenStack Keystone...")
    token, project_id, catalog = keystone_auth(verify)
    print(f"  Token obtained. Project ID: {project_id}")

    # Barbican endpoint
    barbican_base = os.environ.get("OS_BARBICAN_URL") or get_endpoint(catalog, "key-manager")
    if not barbican_base:
        print("ERROR: Barbican (key-manager) endpoint not found in service catalog.\n"
              "Set OS_BARBICAN_URL=<barbican_endpoint> and retry.", file=sys.stderr)
        sys.exit(1)
    print(f"  Barbican endpoint: {barbican_base}")

    # WLM endpoint
    wlm_base = os.environ.get("OS_WLM_URL") or get_endpoint(catalog, "workloads")
    if not wlm_base:
        print("ERROR: WLM (workloads) endpoint not found in service catalog.\n"
              "Set OS_WLM_URL=<wlm_endpoint> and retry.", file=sys.stderr)
        sys.exit(1)
    # Strip /v1/... suffix if catalog includes it
    if "/v1/" in wlm_base:
        wlm_base = wlm_base.split("/v1/")[0]
    print(f"  WLM endpoint: {wlm_base}\n")

    # Process each backup target
    success_count = 0
    fail_count    = 0

    for bt in backup_targets:
        ok = process_backup_target(
            bt, barbican_base, wlm_base, token, project_id, verify, args.dry_run
        )
        if ok:
            success_count += 1
        else:
            fail_count += 1

    # Summary
    label = "[DRY-RUN] " if args.dry_run else ""
    print(f"\n{label}Summary: {success_count} created, {fail_count} failed "
          f"out of {len(backup_targets)} backup target(s).")

    if fail_count:
        print("\nSome backup targets failed. Review errors above.")
        print("You can also create them manually via the T4O UI or workloadmgr CLI.")
        sys.exit(1)

    if not args.dry_run:
        print("\nAll backup targets created successfully.")
        print("Next: create a cloud admin trust — "
              "workloadmgr trust-create --is_cloud_trust True admin --insecure")


if __name__ == "__main__":
    main()
