#!/usr/bin/env python3
"""
create_backup_targets_62.py

Reads backup-targets-migration.yaml (generated by export_backup_targets.py)
and creates each backup target in T4O 6.2 via the WorkloadManager REST API.

Authentication uses standard OpenStack environment variables (sourced from
your cloudrc file before running this script):
  OS_AUTH_URL, OS_USERNAME, OS_PASSWORD, OS_PROJECT_NAME,
  OS_USER_DOMAIN_NAME, OS_PROJECT_DOMAIN_NAME, OS_REGION_NAME
  OS_CACERT  (optional: path to CA bundle for self-signed certs)

Usage:
  source /path/to/cloudrc
  python3 create_backup_targets_62.py [options]

Options:
  --input     Path to migration YAML file  (default: backup-targets-migration.yaml)
  --insecure  Disable SSL certificate verification
  --dry-run   Print API requests without executing them

Prerequisites:
  - T4O 6.2 deployed and WLM service accessible
  - PyYAML   (dnf install python3-pyyaml)
  - requests (dnf install python3-requests)
"""

import argparse
import json
import os
import sys

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.  Install with:  dnf install python3-pyyaml", file=sys.stderr)
    sys.exit(1)

try:
    import requests
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
except ImportError:
    print("ERROR: requests is required.  Install with:  dnf install python3-requests", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# OpenStack / WLM auth helpers
# ---------------------------------------------------------------------------

def get_os_env(key, required=True):
    """Read an OpenStack environment variable, optionally raising if missing."""
    val = os.environ.get(key, "")
    if required and not val:
        print(f"ERROR: Environment variable {key} is not set. Source your cloudrc file.", file=sys.stderr)
        sys.exit(1)
    return val


def keystone_auth(verify):
    """
    Authenticate against Keystone v3 using OS_* environment variables.
    Returns (token, project_id, service_catalog).
    """
    auth_url = get_os_env("OS_AUTH_URL").rstrip("/")
    username = get_os_env("OS_USERNAME")
    password = get_os_env("OS_PASSWORD")
    project_name = get_os_env("OS_PROJECT_NAME")
    user_domain = get_os_env("OS_USER_DOMAIN_NAME", required=False) or "Default"
    project_domain = get_os_env("OS_PROJECT_DOMAIN_NAME", required=False) or "Default"

    token_url = f"{auth_url}/v3/auth/tokens"
    body = {
        "auth": {
            "identity": {
                "methods": ["password"],
                "password": {
                    "user": {
                        "name": username,
                        "password": password,
                        "domain": {"name": user_domain},
                    }
                },
            },
            "scope": {
                "project": {
                    "name": project_name,
                    "domain": {"name": project_domain},
                }
            },
        }
    }

    print(f"  Authenticating to Keystone: {token_url}")
    resp = requests.post(token_url, json=body, verify=verify)
    if resp.status_code not in (200, 201):
        print(f"ERROR: Keystone auth failed ({resp.status_code}): {resp.text}", file=sys.stderr)
        sys.exit(1)

    token = resp.headers["X-Subject-Token"]
    resp_body = resp.json()
    project_id = resp_body["token"]["project"]["id"]
    catalog = resp_body["token"].get("catalog", [])
    return token, project_id, catalog


def get_wlm_endpoint(catalog, interface="public", region=None):
    """
    Extract the WLM (workloads service) endpoint from the Keystone service catalog.
    Falls back to internal interface if public is not found.
    """
    region = region or os.environ.get("OS_REGION_NAME", "")
    for svc in catalog:
        if svc.get("type") == "workloads":
            for ep in svc.get("endpoints", []):
                if region and ep.get("region_id") != region:
                    continue
                if ep.get("interface") == interface:
                    return ep["url"].rstrip("/")
            # Fallback: internal
            for ep in svc.get("endpoints", []):
                if region and ep.get("region_id") != region:
                    continue
                if ep.get("interface") == "internal":
                    return ep["url"].rstrip("/")
    return None


# ---------------------------------------------------------------------------
# Backup target creation
# ---------------------------------------------------------------------------

def build_nfs_payload(bt, project_id):
    """Build the WLM API request body for an NFS backup target."""
    metadata = {
        "btt_name": bt["backup_target_name"],
        "filesystem_export": bt.get("nfs_shares", ""),
    }
    if bt.get("nfs_options"):
        metadata["nfs_options"] = bt["nfs_options"]
    return {
        "backup_target": {
            "type": "nfs",
            "is_default": 1 if bt.get("is_default") else 0,
            "metadata": metadata,
        }
    }


def build_s3_payload(bt, project_id):
    """Build the WLM API request body for an S3 backup target."""
    metadata = {
        "btt_name":        bt["backup_target_name"],
        "s3_bucket":       bt.get("s3_bucket", ""),
        "s3_endpoint_url": bt.get("s3_endpoint_url", ""),
        "s3_type":         bt.get("s3_type", "amazon_s3"),
        "s3_region_name":  bt.get("s3_region_name", ""),
        "s3_ssl_enabled":  str(bt.get("s3_ssl_enabled", True)).lower(),
        "s3_ssl_verify":   str(bt.get("s3_ssl_verify", True)).lower(),
    }
    if bt.get("s3_access_key"):
        metadata["s3_access_key"] = bt["s3_access_key"]
    if bt.get("s3_secret_key"):
        metadata["s3_secret_key"] = bt["s3_secret_key"]
    if bt.get("s3_ssl_ca_cert"):
        metadata["s3_ssl_ca_cert"] = bt["s3_ssl_ca_cert"]
    if bt.get("s3_signature_version"):
        metadata["s3_signature_version"] = bt["s3_signature_version"]
    if bt.get("s3_auth_version"):
        metadata["s3_auth_version"] = bt["s3_auth_version"]

    return {
        "backup_target": {
            "type": "s3",
            "is_default": 1 if bt.get("is_default") else 0,
            "immutable":  1 if bt.get("s3_bucket_object_lock_enabled") else 0,
            "metadata":   metadata,
        }
    }


def create_backup_target(wlm_base, token, project_id, bt, verify, dry_run):
    """
    POST /v1/{project_id}/backup_targets to create a single backup target.
    Returns True on success, False on failure.
    """
    bt_name = bt.get("backup_target_name", "")
    bt_type = bt.get("backup_target_type", "")
    url = f"{wlm_base}/v1/{project_id}/backup_targets"

    if bt_type == "nfs":
        payload = build_nfs_payload(bt, project_id)
    elif bt_type == "s3":
        payload = build_s3_payload(bt, project_id)
    else:
        print(f"  ERROR: Unknown backup_target_type '{bt_type}' for '{bt_name}'. Skipping.")
        return False

    headers = {
        "X-Auth-Token":      token,
        "X-Auth-Project-Id": project_id,
        "Content-Type":      "application/json",
        "Accept":            "application/json",
        "User-Agent":        "python-workloadmgrclient",
    }

    if dry_run:
        print(f"  [DRY-RUN] POST {url}")
        print(f"  Payload: {json.dumps(payload, indent=4)}")
        return True

    resp = requests.post(url, json=payload, headers=headers, verify=verify)
    if resp.status_code in (200, 201):
        resp_body = resp.json()
        bt_id = resp_body.get("backup_target", {}).get("id", "")
        print(f"  Created: '{bt_name}'  id={bt_id}")
        return True
    else:
        print(f"  ERROR: Failed to create '{bt_name}' "
              f"(HTTP {resp.status_code}): {resp.text}")
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Create T4O 6.2 backup targets from migration YAML via WLM REST API"
    )
    parser.add_argument(
        "--input", default="backup-targets-migration.yaml",
        help="Path to migration YAML generated by export_backup_targets.py "
             "(default: backup-targets-migration.yaml)"
    )
    parser.add_argument(
        "--insecure", action="store_true",
        help="Disable SSL certificate verification"
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print API requests without executing them"
    )
    args = parser.parse_args()

    # SSL verification
    if args.insecure:
        requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
        verify = False
    else:
        ca_cert = os.environ.get("OS_CACERT", "")
        verify = ca_cert if ca_cert else True

    # Load migration YAML
    print(f"Reading backup targets from: {args.input}")
    try:
        with open(args.input) as f:
            migration = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"ERROR: {args.input} not found. Run export_backup_targets.py first.", file=sys.stderr)
        sys.exit(1)
    except yaml.YAMLError as e:
        print(f"ERROR: Failed to parse {args.input}: {e}", file=sys.stderr)
        sys.exit(1)

    backup_targets = migration.get("backup_targets", [])
    if not backup_targets:
        print("No backup targets found in migration file. Exiting.")
        sys.exit(0)

    print(f"Found {len(backup_targets)} backup target(s) to create.\n")

    # Authenticate with Keystone
    print("Authenticating with OpenStack Keystone...")
    token, project_id, catalog = keystone_auth(verify)
    print(f"  Token obtained. Project ID: {project_id}")

    # Get WLM endpoint
    interface = os.environ.get("OS_INTERFACE", "public")
    wlm_base = get_wlm_endpoint(catalog, interface=interface)
    if not wlm_base:
        # Fallback: let user specify via env
        wlm_base = os.environ.get("OS_WLM_URL", "")
    if not wlm_base:
        print(
            "ERROR: Could not find WLM (workloads) endpoint in Keystone service catalog.\n"
            "Set OS_WLM_URL=<wlm_public_endpoint> and retry.",
            file=sys.stderr
        )
        sys.exit(1)

    # Strip /v1/... suffix if endpoint already contains it (catalog may include it)
    if "/v1/" in wlm_base:
        wlm_base = wlm_base.split("/v1/")[0]

    print(f"  WLM endpoint: {wlm_base}\n")

    # Create each backup target
    success_count = 0
    fail_count = 0

    for bt in backup_targets:
        bt_name = bt.get("backup_target_name", "?")
        bt_type = bt.get("backup_target_type", "?")
        is_default = bt.get("is_default", False)
        print(f"Creating: '{bt_name}'  type={bt_type}  default={is_default}")

        if create_backup_target(wlm_base, token, project_id, bt, verify, args.dry_run):
            success_count += 1
        else:
            fail_count += 1

    # Summary
    print(f"\n{'[DRY-RUN] ' if args.dry_run else ''}Summary: "
          f"{success_count} created, {fail_count} failed "
          f"out of {len(backup_targets)} backup target(s).")

    if fail_count > 0:
        print("\nSome backup targets failed to create. Review errors above.")
        print("You can also create them manually via the T4O UI or workloadmgr CLI.")
        sys.exit(1)

    if not args.dry_run:
        print("\nAll backup targets created successfully.")
        print("Next step: Create a cloud admin trust via the T4O CLI or UI before running workloads.")


if __name__ == "__main__":
    main()
