#!/usr/bin/env python3
"""
create_backup_targets_62.py

Reads backup-targets-migration.yaml (generated by export_backup_targets.py)
and creates each backup target in T4O 6.2.

T4O 6.2 backup target creation flow:

  S3 backup targets:
    1. Build a Barbican secret JSON payload from the 6.1 S3 config fields.
    2. Store the secret in OpenStack Barbican via openstackclient pod.
    3. Create the WLM backup target with the Barbican secret_ref.

  NFS backup targets:
    1. Create the WLM backup target directly with the NFS export path and options.

All OpenStack API calls are executed inside the openstackclient pod in the
openstack namespace (where the cloudrc is already sourced). The bastion only
needs an authenticated oc CLI.

Usage:
  python3 create_backup_targets_62.py [options]

Options:
  --input        Path to migration YAML  (default: backup-targets-migration.yaml)
  --namespace    OpenShift namespace for openstackclient pod (default: openstack)
  --pod          Explicit openstackclient pod name (auto-detected if omitted)
  --insecure     Pass --insecure to openstack/curl commands inside the pod
  --dry-run      Print actions without executing them

Prerequisites:
  - oc CLI authenticated on the bastion with access to the openstack namespace
  - openstackclient pod running in the openstack namespace with cloudrc sourced
  - python3-pyyaml on the bastion (dnf install python3-pyyaml)
"""

import argparse
import json
import subprocess
import sys

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.  dnf install python3-pyyaml", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Field mapping: T4O 6.1 export YAML → Barbican secret JSON keys
# ---------------------------------------------------------------------------

# Required Barbican secret keys for S3 backup targets (ref: trilio-dms DEPLOYMENT_GUIDE.md)
S3_FIELD_MAP = {
    "s3_access_key":                 "VAULT_S3_ACCESS_KEY_ID",
    "s3_secret_key":                 "VAULT_S3_SECRET_ACCESS_KEY",
    "s3_bucket":                     "VAULT_S3_BUCKET",
    "s3_endpoint_url":               "VAULT_S3_ENDPOINT_URL",
    "s3_region_name":                "VAULT_S3_REGION_NAME",
    "s3_signature_version":          "VAULT_S3_SIGNATURE_VERSION",
    "s3_auth_version":               "VAULT_S3_AUTH_VERSION",
    "s3_ssl_enabled":                "VAULT_S3_SSL",
    "s3_ssl_verify":                 "VAULT_S3_SSL_VERIFY",
    "s3_ssl_ca_cert":                "VAULT_S3_SSL_CERT",
    "s3_bucket_object_lock_enabled": "BUCKET_OBJECT_LOCK",
}

# Defaults for optional Barbican keys not present in 6.1 config
S3_DEFAULTS = {
    "VAULT_STORAGE_TYPE":            "s3",
    "VAULT_S3_MAX_POOL_CONNECTIONS": "500",
    "VAULT_S3_READ_TIMEOUT":         "30",
    "VAULT_S3_MAX_ATTEMPTS":         "3",
    "VAULT_DATA_DIRECTORY_OLD":      "/var/triliovault",
    "LOG_CONFIG_APPEND":             "/etc/triliovault-object-store/object_store_logging.conf",
    "HELPER_COMMAND":                "sudo /usr/bin/trilio-dms-rootwrap /etc/triliovault-dms/rootwrap.conf privsep-helper",
    "METADATA_CACHE_ENABLED":        "True",
    "USE_MANIFEST_SUFFIX":           "False",
}


# ---------------------------------------------------------------------------
# oc exec helpers
# ---------------------------------------------------------------------------

def run_oc_exec(namespace, pod, cmd, capture=True):
    """
    Run a shell command inside the openstackclient pod via oc exec.
    Returns (stdout, returncode). stderr is printed directly.
    """
    full_cmd = ["oc", "exec", "-n", namespace, pod, "--", "/bin/bash", "-c", cmd]
    result = subprocess.run(full_cmd, capture_output=capture, text=True)
    return result.stdout.strip(), result.returncode


def get_openstackclient_pod(namespace):
    """
    Auto-detect the openstackclient pod name in the given namespace.
    Returns the pod name or exits on failure.
    """
    result = subprocess.run(
        ["oc", "get", "pods", "-n", namespace,
         "-l", "component=openstackclient",
         "-o", "jsonpath={.items[0].metadata.name}"],
        capture_output=True, text=True
    )
    pod = result.stdout.strip()
    if not pod or result.returncode != 0:
        # Fallback: try common pod name patterns
        result2 = subprocess.run(
            ["oc", "get", "pods", "-n", namespace,
             "--no-headers", "-o", "custom-columns=NAME:.metadata.name"],
            capture_output=True, text=True
        )
        for line in result2.stdout.splitlines():
            if "openstackclient" in line:
                return line.strip()
        print(f"ERROR: Could not find openstackclient pod in namespace '{namespace}'.\n"
              f"Use --pod to specify the pod name explicitly.", file=sys.stderr)
        sys.exit(1)
    return pod


# ---------------------------------------------------------------------------
# OpenStack token / project
# ---------------------------------------------------------------------------

def get_token_and_project(namespace, pod, insecure):
    """
    Retrieve the current auth token and project ID from inside the
    openstackclient pod using 'openstack token issue'.
    Returns (token, project_id).
    """
    insecure_flag = " --insecure" if insecure else ""
    cmd = f"openstack{insecure_flag} token issue -f json"
    stdout, rc = run_oc_exec(namespace, pod, cmd)
    if rc != 0 or not stdout:
        print(f"ERROR: 'openstack token issue' failed inside pod '{pod}'.\n"
              f"Ensure the cloudrc is sourced in the pod.", file=sys.stderr)
        sys.exit(1)
    try:
        data = json.loads(stdout)
        return data["id"], data["project_id"]
    except (json.JSONDecodeError, KeyError) as e:
        print(f"ERROR: Failed to parse token output: {e}\nOutput: {stdout}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Barbican
# ---------------------------------------------------------------------------

def store_barbican_secret(namespace, pod, secret_name, payload, insecure, dry_run):
    """
    Store a JSON payload as a Barbican secret via 'openstack secret store'
    inside the openstackclient pod.
    Returns the secret_ref URL string, or None on failure.
    """
    payload_json = json.dumps(payload)
    insecure_flag = " --insecure" if insecure else ""

    # Escape single quotes in the JSON payload for shell safety
    escaped_payload = payload_json.replace("'", "'\\''")

    cmd = (
        f"openstack{insecure_flag} secret store"
        f" --name '{secret_name}'"
        f" --payload '{escaped_payload}'"
        f" --payload-content-type 'application/json'"
        f" -f json"
    )

    if dry_run:
        print(f"    [DRY-RUN] openstack secret store --name '{secret_name}'")
        print(f"    Payload keys: {list(payload.keys())}")
        return "http://barbican-dry-run/v1/secrets/dry-run-uuid"

    stdout, rc = run_oc_exec(namespace, pod, cmd)
    if rc != 0 or not stdout:
        print(f"    ERROR: 'openstack secret store' failed for '{secret_name}'.\n"
              f"    Output: {stdout}")
        return None

    try:
        data = json.loads(stdout)
        secret_ref = data.get("secret_href", "")
        print(f"    Barbican secret created: {secret_ref}")
        return secret_ref
    except (json.JSONDecodeError, KeyError) as e:
        print(f"    ERROR: Failed to parse secret store output: {e}\nOutput: {stdout}")
        return None


def build_s3_barbican_payload(bt):
    """Build the Barbican secret JSON payload from a 6.1 S3 backup target dict."""
    payload = dict(S3_DEFAULTS)

    for field_61, vault_key in S3_FIELD_MAP.items():
        val = bt.get(field_61)
        if val is None:
            continue
        # Booleans must be stored as "True"/"False" strings
        if isinstance(val, bool):
            payload[vault_key] = str(val)
        else:
            payload[vault_key] = val

    # VAULT_STORAGE_NFS_EXPORT is the S3 filesystem_export representation
    # (used by s3vaultfuse as the virtual NFS path for the bucket)
    if bt.get("s3_bucket"):
        endpoint = bt.get("s3_endpoint_url", "").rstrip("/")
        bucket   = bt.get("s3_bucket", "")
        payload["VAULT_STORAGE_NFS_EXPORT"] = f"{endpoint}/{bucket}" if endpoint else bucket

    return payload


# ---------------------------------------------------------------------------
# WLM backup target
# ---------------------------------------------------------------------------

def get_wlm_endpoint(namespace, pod, insecure):
    """
    Retrieve the WLM (workloads) service endpoint from inside the
    openstackclient pod using 'openstack catalog show'.
    Returns the endpoint URL base, or None if not found.
    """
    insecure_flag = " --insecure" if insecure else ""
    cmd = f"openstack{insecure_flag} catalog show workloads -f json"
    stdout, rc = run_oc_exec(namespace, pod, cmd)
    if rc != 0 or not stdout:
        return None
    try:
        data = json.loads(stdout)
        for endpoint in data.get("endpoints", []):
            if endpoint.get("interface") == "public":
                url = endpoint["url"].rstrip("/")
                if "/v1/" in url:
                    url = url.split("/v1/")[0]
                return url
        # Fallback: return first endpoint found
        endpoints = data.get("endpoints", [])
        if endpoints:
            url = endpoints[0]["url"].rstrip("/")
            if "/v1/" in url:
                url = url.split("/v1/")[0]
            return url
    except (json.JSONDecodeError, KeyError):
        pass
    return None


def create_wlm_backup_target(namespace, pod, wlm_base, token, project_id,
                              bt, secret_ref, insecure, dry_run):
    """
    POST /v1/{project_id}/backup_targets via curl inside the openstackclient pod.
    Returns True on success, False on failure.
    """
    bt_name = bt.get("backup_target_name", "")
    bt_type = bt.get("backup_target_type", "")
    url     = f"{wlm_base}/v1/{project_id}/backup_targets"

    if bt_type == "s3":
        metadata = {
            "btt_name":   bt_name,
            "secret_ref": secret_ref,
        }
    elif bt_type == "nfs":
        metadata = {
            "btt_name":          bt_name,
            "filesystem_export": bt.get("nfs_shares", ""),
        }
        if bt.get("nfs_options"):
            metadata["nfs_mount_opts"] = bt["nfs_options"]
    else:
        print(f"  ERROR: Unknown backup_target_type '{bt_type}'. Skipping '{bt_name}'.")
        return False

    body = {
        "backup_target": {
            "type":       bt_type,
            "is_default": 1 if bt.get("is_default") else 0,
            "immutable":  1 if bt.get("s3_bucket_object_lock_enabled") else 0,
            "metadata":   metadata,
        }
    }

    body_json    = json.dumps(body)
    escaped_body = body_json.replace("'", "'\\''")
    insecure_flag = " -k" if insecure else ""

    cmd = (
        f"curl -s{insecure_flag} -o /tmp/wlm_response.json -w '%{{http_code}}'"
        f" -X POST '{url}'"
        f" -H 'X-Auth-Token: {token}'"
        f" -H 'X-Auth-Project-Id: {project_id}'"
        f" -H 'Content-Type: application/json'"
        f" -H 'Accept: application/json'"
        f" -d '{escaped_body}'"
        f" && cat /tmp/wlm_response.json"
    )

    if dry_run:
        print(f"    [DRY-RUN] POST {url}")
        print(f"    Payload: {json.dumps(body, indent=6)}")
        return True

    stdout, rc = run_oc_exec(namespace, pod, cmd)
    if rc != 0:
        print(f"    ERROR: curl command failed (rc={rc}): {stdout}")
        return False

    # stdout contains: <http_code><response_body>
    # Split http_code (last 3 chars before JSON) from response
    lines = stdout.strip().splitlines()
    # First line is the http_code from -w '%{http_code}', rest is the JSON body
    http_code = lines[0].strip() if lines else ""
    response_body = "\n".join(lines[1:]) if len(lines) > 1 else ""

    if http_code in ("200", "201"):
        try:
            bt_id = json.loads(response_body).get("backup_target", {}).get("id", "")
            print(f"    WLM backup target created: id={bt_id}")
        except json.JSONDecodeError:
            print(f"    WLM backup target created.")
        return True
    else:
        print(f"    ERROR: WLM backup target creation failed "
              f"(HTTP {http_code}): {response_body}")
        return False


# ---------------------------------------------------------------------------
# Per-backup-target orchestration
# ---------------------------------------------------------------------------

def process_backup_target(bt, namespace, pod, wlm_base, token, project_id,
                           insecure, dry_run):
    """Handle one backup target — Barbican secret (if S3) + WLM registration."""
    bt_name = bt.get("backup_target_name", "?")
    bt_type = bt.get("backup_target_type", "?")
    print(f"\n  [{bt_type.upper()}] '{bt_name}'  default={bt.get('is_default', False)}")

    secret_ref = None

    if bt_type == "s3":
        if not bt.get("s3_access_key") or not bt.get("s3_secret_key"):
            print(f"    WARNING: S3 credentials missing for '{bt_name}'. "
                  "Edit backup-targets-migration.yaml and retry.")
            return False

        print(f"    Step 1/2: Store credentials in Barbican")
        payload    = build_s3_barbican_payload(bt)
        secret_ref = store_barbican_secret(
            namespace, pod, bt_name, payload, insecure, dry_run
        )
        if not secret_ref:
            return False

        print(f"    Step 2/2: Register backup target in WLM")

    elif bt_type == "nfs":
        print(f"    Step 1/1: Register NFS backup target in WLM")

    else:
        print(f"    ERROR: Unknown type '{bt_type}'. Skipping.")
        return False

    return create_wlm_backup_target(
        namespace, pod, wlm_base, token, project_id, bt, secret_ref, insecure, dry_run
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Create T4O 6.2 backup targets from migration YAML "
                    "(Barbican secret + WLM registration via openstackclient pod)"
    )
    parser.add_argument(
        "--input", default="backup-targets-migration.yaml",
        help="Migration YAML from export_backup_targets.py "
             "(default: backup-targets-migration.yaml)"
    )
    parser.add_argument(
        "--namespace", default="openstack",
        help="OpenShift namespace containing the openstackclient pod "
             "(default: openstack)"
    )
    parser.add_argument(
        "--pod", default="",
        help="openstackclient pod name (auto-detected if omitted)"
    )
    parser.add_argument("--insecure", action="store_true",
                        help="Disable SSL certificate verification")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print actions without executing them")
    args = parser.parse_args()

    # Load migration YAML
    print(f"Reading backup targets from: {args.input}")
    try:
        with open(args.input) as f:
            migration = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"ERROR: {args.input} not found. Run export_backup_targets.py first.",
              file=sys.stderr)
        sys.exit(1)

    backup_targets = migration.get("backup_targets", [])
    if not backup_targets:
        print("No backup targets found in migration file. Exiting.")
        sys.exit(0)

    print(f"Found {len(backup_targets)} backup target(s).\n")

    # Locate openstackclient pod
    pod = args.pod or get_openstackclient_pod(args.namespace)
    print(f"Using openstackclient pod: {pod}  (namespace: {args.namespace})")

    # Get auth token and project ID from inside the pod
    print("Retrieving auth token from openstackclient pod...")
    token, project_id = get_token_and_project(args.namespace, pod, args.insecure)
    print(f"  Token obtained. Project ID: {project_id}")

    # Get WLM endpoint
    print("Resolving WLM endpoint...")
    wlm_base = get_wlm_endpoint(args.namespace, pod, args.insecure)
    if not wlm_base:
        print("ERROR: WLM (workloads) endpoint not found in service catalog.\n"
              "Ensure the workloads service is registered in Keystone.", file=sys.stderr)
        sys.exit(1)
    print(f"  WLM endpoint: {wlm_base}\n")

    # Process each backup target
    success_count = 0
    fail_count    = 0

    for bt in backup_targets:
        ok = process_backup_target(
            bt, args.namespace, pod, wlm_base, token, project_id,
            args.insecure, args.dry_run
        )
        if ok:
            success_count += 1
        else:
            fail_count += 1

    # Summary
    label = "[DRY-RUN] " if args.dry_run else ""
    print(f"\n{label}Summary: {success_count} created, {fail_count} failed "
          f"out of {len(backup_targets)} backup target(s).")

    if fail_count:
        print("\nSome backup targets failed. Review errors above.")
        print("You can also create them manually via the T4O UI or workloadmgr CLI.")
        sys.exit(1)

    if not args.dry_run:
        print("\nAll backup targets created successfully.")
        print("Next: create a cloud admin trust by launching a temporary WLM pod:")
        print("  WLM_IMAGE=$(oc get deployment -n trilio-openstack -l app=wlm-api "
              "-o jsonpath='{.items[0].spec.template.spec.containers[0].image}')")
        print("  oc run -n trilio-openstack wlm-trust-create --rm -it --restart=Never "
              "--image=$WLM_IMAGE -- "
              "workloadmgr trust-create --is_cloud_trust True admin --insecure")


if __name__ == "__main__":
    main()
