apiVersion: v1
kind: Secret
metadata:
  name: trilio-openstack-secret
type: Opaque
data:
  DbRootPassword: dGVzdHBhc3M=
  DmapiDatabasePassword: dGVzdHBhc3M=
  DmapiKeystonePassword: dGVzdHBhc3M=
  DmapiRabbitPassword: dGVzdHBhc3M=
  WlmDatabasePassword: dGVzdHBhc3M=
  WlmKeystonePassword: dGVzdHBhc3M=
  WlmRabbitPassword: dGVzdHBhc3M=
  ContainerRegistryPassword: dGVzdHBhc3M=