apiVersion: v1
kind: Secret
metadata:
  name: trilio-s3-backup-target-secret-<BACKUP_TARGET_NAME>
type: Opaque
data:
  <BACKUP_TARGET_NAME>_s3_access_key: QUNDRVNTSQ==
  <BACKUP_TARGET_NAME>_s3_secret_key: U0VDUkVUMQ==