apiVersion: v1
kind: Secret
metadata:
  name: trilio-openstack-secret
type: Opaque
data:
  DmapiDatabasePassword: dGVzdHBhc3M=
  DmapiKeystonePassword: dGVzdHBhc3M=
  DmapiRabbitPassword: dGVzdHBhc3M=
  WlmDatabasePassword: dGVzdHBhc3M=
  WlmKeystonePassword: dGVzdHBhc3M=
  WlmRabbitPassword: dGVzdHBhc3M=
  ContainerRegistryPassword: dGVzdHBhc3M=
  BT1_S3_s3_access_key: QUNDRVNTSQ==
  BT1_S3_s3_secret_key: U0VDUkVUMQ==
  BT2_Other_S3_s3_access_key: QUNDRVNTMg==
  BT2_Other_S3_s3_secret_key: U0VDUkVUMg==
  