apiVersion: v1
kind: Secret
metadata:
  name: openstack-secret
type: Opaque
data:
  CloudAdminPassword: {{ (lookup "v1" "Secret" .Values.openstack.namespace .Values.openstack.osp_secret_name).data.AdminPassword | quote }}
  DatabseRootPassword: {{ (lookup "v1" "Secret" .Values.openstack.namespace .Values.openstack.osp_secret_name).data.DbRootPassword | quote }}
  RabbitAdminPassword: {{ (lookup "v1" "Secret" .Values.openstack.namespace .Values.openstack.rabbitmq_admin_secret_name).data.password | quote }}