{{- if eq .Values.crdType "TVOControlPlane" }}
{{- $namespace := default "openstack" .Values.openstack.namespace }}
{{- $ospSecretName := default "osp-secret" .Values.openstack.osp_secret_name }}
{{- $rabbitmqSecretName := default "rabbitmq-default-user" .Values.openstack.rabbitmq_admin_secret_name }}
{{- $ospSecret := lookup "v1" "Secret" $namespace $ospSecretName }}
{{- $rabbitSecret := lookup "v1" "Secret" $namespace $rabbitmqSecretName }}

{{- $adminPassword := "" }}
{{- $dbRootPassword := "" }}
{{- $rabbitPassword := "" }}

{{- if $ospSecret }}
  {{- $adminPassword = $ospSecret.data.AdminPassword }}
  {{- $dbRootPassword = $ospSecret.data.DbRootPassword }}
{{- end }}
{{- if $rabbitSecret }}
  {{- $rabbitPassword = $rabbitSecret.data.password }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: openstack-secret
  annotations:
    checksum/config: "{{ printf "%s%s%s" $adminPassword $dbRootPassword $rabbitPassword | sha256sum }}"
type: Opaque
data:
  CloudAdminPassword: "{{ $adminPassword }}"
  DatabaseRootPassword: "{{ $dbRootPassword }}"
  RabbitAdminPassword: "{{ $rabbitPassword }}"
{{- end }}

