apiVersion: v1
kind: Secret
metadata:
  name: openstack-secret
type: Opaque
data:
  CloudAdminPassword: "dGVzdA=="
  DatabseRootPassword: {{ (lookup "v1" "Secret" "openstack" "osp-secret").data.DbRootPassword | quote }}
  RabbitAdminPassword: {{ (lookup "v1" "Secret" .Values.openstack.namespace .Values.openstack.rabbitmq_admin_secret_name).data.password | quote }}
