{{- if eq .Values.trilio_backup_target.backup_target_type "nfs" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: trilio-nfs-mount-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
  namespace: trilio-openstack
  labels:
    application: trilio-openstack
    component: nfs-mount
spec:
  selector:
    matchLabels:
      application: trilio-openstack
      component: nfs-mount
  template:
    metadata:
      labels:
        application: trilio-openstack
        component: nfs-mount
    spec:
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      serviceAccountName: trilio-backup-targets-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
      nodeSelector:
        triliovault-control-plane: enabled
        openstack-compute-node: enabled
      containers:
        - name: nfs-mount
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: {{ .Values.common.nova_user_id }}
          image: {{ .Values.images.trilio_backup_targets }}
          imagePullPolicy: IfNotPresent
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            {{- $encoded_path := .Values.trilio_backup_target.nfs_shares | b64enc }}
            {{- $mount_path := printf "%s/%s" .Values.common.vault_data_dir $encoded_path }}
            - name: nfs-mounts
              mountPath: {{ $mount_path | quote }}
              mountPropagation: Bidirectional
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: nfs-mounts
          persistentVolumeClaim:
            claimName: trilio-nfs-pvc-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
{{- end }}