{{- if eq .Values.trilio_backup_target.backup_target_type "nfs" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilio-nfs-pvc-{{ .Values.trilio_backup_target.backup_target_name | lower | replace "_" "-" }}
  namespace: trilio-openstack
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.trilio_backup_target.storage_size | default "100Gi" }}
  storageClassName: {{ .Values.trilio_backup_target.storage_class_name }} 
{{- end }}
