FROM kolla/ubuntu-binary-nova-api:ussuri
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="kolla/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="TrilioData trilio-datamover-api" \
      description="TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root

##Install datamover packages

ADD trilio.list /etc/apt/sources.list.d/
RUN apt-get update -y
RUN apt-get install -y python3-dmapi --allow-unauthenticated

RUN chown -R dmapi:dmapi /etc/nova/

## Kolla specifc settings
COPY extend_start.sh /usr/local/bin/kolla_extend_start
COPY triliovault_datamover_api_extend_start.sh /usr/local/bin/kolla_triliovault_datamover_api_extend_start

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi