FROM kolla/ubuntu-binary-nova-api:ussuri
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="kolla/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="TrilioData trilio-datamover-api" \
      description="TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root

##Install datamover packages

ADD trilio.list /etc/apt/sources.list.d/
RUN apt-get update -y
RUN groupadd -g 42487 dmapi \
   && useradd -u 42486 -g 42487 dmapi
RUN apt-get install -y python3-dmapi --allow-unauthenticated
RUN id dmapi

RUN mkdir -p /etc/nova \
   /var/log/kolla/dmapi \
 && chown -R dmapi:dmapi /etc/nova/ \
 && chown -R dmapi:dmapi /var/log/kolla/dmapi

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi

##################
# REQUIRED MOUNTS#
##################
# /etc/kolla/dmapi/nova.conf:/etc/nova/nova.conf
# /etc/kolla/dmapi/dmapi.conf:/etc/dmapi/dmapi.conf

##############
# RUN COMMAND#
##############
# docker run --network host --name trilio_dmapi -d -v /etc/kolla/dmapi/nova.conf:/etc/nova/nova.conf -v /etc/kolla/dmapi/dmapi.conf:/etc/dmapi/dmapi.conf kolla/ubuntu-source-trilio-dmapi:pike /var/lib/kolla/venv/bin/python /usr/bin/dmapi-api
