apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: openshift-user-workload-monitoring
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: $BASE64_ENCODED_GRAFANA_DASHBOARD_USER_NAME
  GF_SECURITY_ADMIN_PASSWORD: $BASE64_ENCODED_GRAFANA_DASHBOARD_PASSWORD
  PROMETHEUS_TOKEN: $BASE64_ENCODED_GRAFANA_SERVICE_ACCOUNT_BEARER_TOKEN
