{{- if eq .Values.action "add-s3-target" }}

{{- $serviceAccountName := printf "triliovault-s3-target-%s" (.Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-") }}
{{ tuple $envAll "triliovault_object_store" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: triliovault-s3-secret-{{ .Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-" }}
type: Opaque
data:
  object_store_logging.conf: {{ include "helm-toolkit.utils.to_oslo_conf" .Values.conf.object_store_logging | b64enc }}
  triliovault-object-store-datamover.conf: {{ include "helm-toolkit.utils.to_ini" .Values.conf.triliovault_object_store_datamover | b64enc }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: triliovault-object-store-bin
data:
  triliovault-object-store.sh: |
    #!/bin/bash
    set -ex

    COMMAND="${@:-start}"

    function start () {
      ## Start triliovault object store service
      /usr/bin/python3 /usr/bin/s3vaultfuse.py --config-file=/etc/triliovault-object-store/triliovault-object-store.conf &
      status=$?
      sleep 20s
      if [ $status -ne 0 ]; then
        echo "Failed to start tvault-object-store service: $status"
        exit $status
      fi
    }

    function stop () {
      pkill -f s3vaultfuse.py || true
      exit 0
    }

    $COMMAND
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliovault-s3-target-{{ .Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-" }}
  labels:
{{ tuple $envAll "triliovault" "s3-target" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
spec:
  replicas: {{ $.Values.pod.replicas.triliovault_object_store }}
  selector:
    matchLabels:
{{ tuple $envAll "triliovault" "s3-target" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
{{ tuple $envAll "triliovault" "datamover-api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      securityContext:
        runAsUser: 42424
        fsGroup: 42424
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: application
                    operator: In
                    values:
                    - triliovault
                  - key: component
                    operator: In
                    values:
                    - s3-target
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        trilio-control-plane: enabled
      terminationGracePeriodSeconds: 30
      containers:
        - name: triliovault-s3-target-{{ .Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-" }}
          image: {{ $.Values.images.triliovault_object_store }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 42424
          command: ["/bin/bash", "/tmp/triliovault-object-store.sh"]
          args: ["start"]
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /tmp/triliovault-object-store.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: trilio-logs
              mountPath: /var/log/triliovault
            - mountPath: /etc/triliovault-object-store/object_store_logging.conf
              name: triliovault-s3-secret
              readOnly: true
              subPath: object_store_logging.conf
            - name: triliovault-s3-secret
              mountPath: /etc/triliovault-object-store/triliovault-object-store.conf
              subPath: triliovault-object-store.conf
              readOnly: true
            {{- if .Values.triliovault_backup_target.s3_self_signed_cert }}
            - name: triliovault-object-store-etc
              mountPath: /etc/triliovault-object-store/s3-cert.pem
              subPath: s3-cert.pem
              readOnly: true
            {{- end }}
            - name: triliovault-object-store-bin
              mountPath: /tmp/triliovault-object-store.sh
              subPath: triliovault-object-store.sh
            - name: pod-shared-triliovault-object-store
              mountPath: /tmp/pod-shared-triliovault-object-store
            - name: trilio-mounts
              mountPath: {{ $.Values.nfs_data_dir }}
              mountPropagation: Bidirectional
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: trilio-logs
          emptyDir: {}
        - name: triliovault-s3-secret
          secret:
            secretName: triliovault-s3-secret-{{ .Values.triliovault_backup_target.backup_target_name | lower | replace "_" "-" }}
            defaultMode: 0444
        - name: triliovault-object-store-bin
          configMap:
            name: triliovault-object-store-bin
            defaultMode: 0555
        - name: pod-shared-triliovault-object-store
          emptyDir: {}
        - name: trilio-mounts
          hostPath:
            path: {{ $.Values.nfs_data_dir }}
            type: DirectoryOrCreate
{{- end }}