{{/*
Licensed under TrilioVault License
*/}}

{{- if .Values.manifests.deployment_datamover_api }}
{{- $envAll := . }}

{{- $mounts_triliovault_datamover_api := .Values.pod.mounts.triliovault_datamover_api.triliovault_datamover_api }}
{{- $mounts_triliovault_datamover_api_init := .Values.pod.mounts.triliovault_datamover_api.init_container }}

{{- $serviceAccountName := "triliovault-api" }}
{{ tuple $envAll "api" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliovault-datamover-api
  annotations:
    {{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" }}
  labels:
{{ tuple $envAll "triliovault" "datamover-api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.pod.replicas.datamover_api }}
  selector:
    matchLabels:
{{ tuple $envAll "triliovault" "datamover-api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
{{ tuple $envAll | include "helm-toolkit.snippets.kubernetes_upgrades_deployment" | indent 2 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "triliovault" "datamover-api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
{{ dict "envAll" $envAll "podName" "datamover-api" "containerNames" (list "datamover-api" "init") | include "helm-toolkit.snippets.kubernetes_mandatory_access_control_annotation" | indent 8 }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "triliovault" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      affinity:
{{ tuple $envAll "triliovault" "datamover-api" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.datamover_api.node_selector_key }}: {{ .Values.labels.datamover_api.node_selector_value }}
      terminationGracePeriodSeconds: {{ .Values.pod.lifecycle.termination_grace_period.datamover_api.timeout | default "30" }}
      initContainers:
{{ tuple $envAll "datamover-api" $mounts_triliovault_datamover_api_init | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: triliovault-datamover-api
{{ tuple $envAll "datamover_api" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.api | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "triliovault_datamover_api" "container" "triliovault_datamover_api" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          command:
            - /tmp/triliovault-datamover-api.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/triliovault-datamover-api.sh
                  - stop
          ports:
            - name: td-api
              containerPort: {{ tuple "datamover" "internal" "datamover-api" . | include "helm-toolkit.endpoints.endpoint_port_lookup" }}
{{ dict "envAll" $envAll "component" "datamover-api" "container" "default" "type" "liveness" "probeTemplate" (include "datamoverApiLivenessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
{{ dict "envAll" $envAll "component" "datamover-api" "container" "default" "type" "readiness" "probeTemplate" (include "datamoverApiReadinessProbeTemplate" $envAll | fromYaml) | include "helm-toolkit.snippets.kubernetes_probe" | indent 10 }}
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: triliovault-bin
              mountPath: /tmp/triliovault-datamover-api.sh
              subPath: triliovault-datamover-api.sh
              readOnly: true
            - name: triliovault-etc
              mountPath: /etc/dmapi/dmapi.conf
              subPath: dmapi.conf
              readOnly: true
            {{- if .Values.conf.triliovault.DEFAULT.log_config_append }}
            - name: triliovault-etc
              mountPath: {{ .Values.conf.triliovault.DEFAULT.log_config_append }}
              subPath: {{ base .Values.conf.triliovault.DEFAULT.log_config_append }}
              readOnly: true
            {{- end }}

{{/* 
Certificate blocks were here. Check if it is required for us
*/}}

{{ if $mounts_triliovault_datamover_api.volumeMounts }}{{ toYaml $mounts_triliovault_datamover_api.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: pod-tmp
          emptyDir: {}
        {{- if .Values.manifests.certificates }}
        - name: wsgi-triliovault
          emptyDir: {}
        {{- end }}
        - name: pod-var-nova
          emptyDir: {}
        - name: triliovault-bin
          configMap:
            name: triliovault-bin
            defaultMode: 0555
        - name: triliovault-etc
          secret:
            secretName: triliovault-etc
            defaultMode: 0444
{{- dict "enabled" .Values.manifests.certificates "name" .Values.endpoints.oslo_db.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" .Values.manifests.certificates "name" .Values.secrets.tls.compute.osapi.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{- dict "enabled" $envAll.Values.manifests.certificates "name" $envAll.Values.endpoints.oslo_messaging.auth.admin.secret.tls.internal | include "helm-toolkit.snippets.tls_volume" | indent 8 }}
{{ if $mounts_datamover_api.volumes}}{{ toYaml $mounts_datamover_api.volumes | indent 8 }}{{ end }}
{{- end }}
