{{/* **********************************************************************
     Set triliovault_object_store.conf services conf parameters
     **********************************************************************
*/}}

{{- if and (eq .Values.action "add-backup-target") (eq .Values.triliovault_backup_target.backup_target_type "s3") }}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_access_key_id -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_access_key_id" .Values.triliovault_backup_target.s3_access_key -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_secret_access_key -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_secret_access_key" .Values.triliovault_backup_target.s3_secret_key -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_region_name -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_region_name" .Values.triliovault_backup_target.s3_region_name -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_bucket -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_bucket" .Values.triliovault_backup_target.s3_bucket -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_signature_version -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_signature_version" .Values.triliovault_backup_target.s3_signature_version -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_auth_version -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_auth_version" .Values.triliovault_backup_target.s3_auth_version -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_endpoint_url -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_endpoint_url" .Values.triliovault_backup_target.s3_endpoint_url -}}
{{- end -}}

{{- if empty .Values.triliovault_object_store.DEFAULT.vault_s3_ssl -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_ssl" .Values.triliovault_backup_target.s3_ssl_enabled -}}
{{- end -}}

{{- if .Values.triliovault_backup_target.s3_ssl_enabled -}}
{{- $_ := set .Values.triliovault_object_store.DEFAULT "vault_s3_ssl_cert" "/etc/triliovault-object-store/s3-cert.pem" -}}
{{- end -}}

---
# Generate a Secret with target-specific configurations
apiVersion: v1
kind: Secret
metadata:
  name: triliovault-object-store-secret-{{ .Values.triliovault_backup_target.backup_target_name }}
type: Opaque
data:
  triliovault-object-store.conf: {{ include "helm-toolkit.utils.to_ini" .Values.triliovault_object_store | b64enc }}

{{- end }}