{{/*
Licensed under the TrilioVault License
*/}}

{{- if and .Values.manifests.service_ingress_api .Values.network.datamover_api.ingress.public }}
{{- $serviceIngressOpts := dict "envAll" . "backendServiceType" "datamover" -}}
{{ $serviceIngressOpts | include "helm-toolkit.manifests.service_ingress" }}
{{- end }}
