{{- if eq .Values.action "Install" }}
apiVersion: v1
kind: Secret
metadata:
  name: triliovault-datamover-etc
type: Opaque
data:
  triliovault-datamover.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_datamover_conf.tpl") . | b64enc }}
  datamover_logging.conf: |
    {{ tpl (.Files.Get "conf/_datamover_logging_conf.tpl") . | b64enc }}
  nova-compute.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_nova_compute.conf.tpl") . | b64enc }}
  {{- if .Values.ceph.enabled }}
  ceph.conf: |
    {{ tpl (.Files.Get "conf/_triliovault-ceph.conf.tpl") . | b64enc }} 
  {{ end }}
{{- end }}