apiVersion: v1
kind: Secret
metadata:
  name: triliovault-datamover-api-etc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
type: Opaque
stringData:
  triliovault-datamover-api.conf: |
    [DEFAULT]
    transport_url = rabbit://{{ .Values.rabbitmq.dmapi.user }}:{{ .Values.rabbitmq.dmapi.password }}@{{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}/{{ .Values.rabbitmq.dmapi.vhost }}
    log_dir = /var/log/triliovault
    state_path = /var/lib/nova

    [keystone_authtoken]
    auth_url = {{ .Values.keystone.auth_url }}
    auth_type = password
    project_domain_id = default
    project_name = service
    user_domain_id = default
    username = {{ .Values.keystone.datamover_api.username }}
    password = {{ .Values.keystone.datamover_api.password }}
    memcache_servers = {{ .Values.keystone.memcache_servers }}

    {{- if .Values.tls.ca_bundle_configmap }}
    insecure = false
    cafile = /etc/ssl/certs/sunbeam-ca.crt
    {{- end }}

    [database]
    connection = mysql+pymysql://{{ .Values.database.dmapi.user }}:{{ .Values.database.dmapi.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.dmapi.database }}

    [oslo_messaging_rabbit]
    rabbit_ha_queues = true
    ssl = false

    [api]
    auth_strategy = keystone
