apiVersion: v1
kind: Service
metadata:
  name: trilio-datamover-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
    component: datamover-api
spec:
  type: {{ .Values.service.datamover_api.type }}
  selector:
    application: triliovault
    component: datamover-api
  ports:
    - name: dmapi
      protocol: TCP
      port: {{ .Values.service.datamover_api.port }}
      targetPort: 8784
      {{- if eq .Values.service.datamover_api.type "NodePort" }}
      nodePort: {{ .Values.service.datamover_api.node_port }}
      {{- end }}
