---
- name: Ensure vault data directory exists
  become: true
  file:
    path: "{{ vault_data_dir }}"
    state: directory
    owner: '42436'
    group: '42436'
    mode: '0755'

- name: Ensure /var/lib/openstack/config/containers directory exists
  become: true
  file:
    path: /var/lib/openstack/config/containers
    state: directory
    owner: root
    group: root
    mode: '0755'
