- name: Ensure Trilio datamover configuration directory exists
  become: true
  file:
    path: "{{ triliovault_datamover_config_dest }}"
    state: directory
    owner: '42436'
    group: '42436'
    mode: '0644'


- name: Create Trilio datamover directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: '42436'
    group: '42436'
    mode: '0744'
  with_items:
    - "{{ vault_data_dir }}"
    - /var/log/containers/triliovault-datamover

- name: Create Trilio datamover configuration file
  become: true
  template:
    src: triliovault_datamover_conf.j2
    dest: "{{ triliovault_datamover_config_dest }}/triliovault-datamover.conf"
    owner: '42436'
    group: '42436'
    mode: '0644'
  notify:
    - Restart triliovault-datamover

- name: Create Trilio datamover kolla config json file
  become: true
  template:
    src: triliovault_datamover_config_json.j2
    dest: "{{ triliovault_datamover_config_dest }}/triliovault_datamover_config.json"
    owner: '42436'
    group: '42436'
    mode: '0644'
  notify:
    - Restart triliovault-datamover
    
- name: Create Trilio datamover logging configuration file
  become: true
  template:
    src: datamover_logging_conf.j2
    dest: "{{ triliovault_datamover_config_dest }}/datamover_logging.conf"
    owner: '42436'
    group: '42436'
    mode: '0644'
  notify:
    - Restart triliovault-datamover

- name: Create Trilio datamover start script
  become: true
  template:
    src: start_triliovault_datamover_sh.j2
    dest: "{{ triliovault_datamover_config_dest }}/start_triliovault_datamover.sh"
    owner: '42436'
    group: '42436'
    mode: '0755'
  notify:
    - Restart triliovault-datamover

#- name: Ensure VMware to OpenStack migration directory exists
#  when: vmware_to_openstack_migration_enabled | bool
#  file:
#    path: /opt/vmware-vix-disklib-distrib/
#    state: directory
#    owner: '42436'
#    group: '42436'
#    mode: '0755'

#- name: Copy VMware VDDK tarball
#  when: vmware_to_openstack_migration_enabled | bool
#  copy:
#    src: "files/{{ vddk_file_name }}"
#    dest: /opt/vddk.tar.gz
#    owner: '42436'
#    group: '42436'
#    mode: '0755'

- name: Check for FR5 nova config path
  become: true
  ansible.builtin.stat:
    path: /var/lib/openstack/nova
  register: nova_config_fr5

- name: Set nova config directory based on RHOSO version
  ansible.builtin.set_fact:
    nova_config_dir: "{{ '/var/lib/openstack/nova' if nova_config_fr5.stat.exists else '/var/lib/openstack/config/nova' }}"

- name: Render triliovault-datamover container
  become: true
  ansible.builtin.template:
    src: "triliovault-datamover-container-json.j2"
    dest: "/var/lib/openstack/config/containers/triliovault-datamover.json"
    mode: "0644"
  notify:
    - Restart triliovault-datamover


- name: Deploy trilio datamover container
  ansible.builtin.include_role:
    name: osp.edpm.edpm_container_manage
  vars:
    edpm_container_manage_config: '/var/lib/openstack/config/containers'
    edpm_container_manage_healthcheck_disabled: true
    edpm_container_manage_config_patterns: 'triliovault-datamover.json'
    edpm_container_manage_clean_orphans: false
