---
# tasks file for trilio-datamover

- name: Log in to the container registry using Podman
  become: true
  containers.podman.podman_login:
    username: "{{ trilio_container_registry_username }}"
    password: "{{ lookup('file', '/var/lib/openstack/configs/trilio-datamover/ContainerRegistryPassword') | trim }}"
    registry: "{{ trilio_container_registry_url }}"
  register: podman_login_result
  failed_when: podman_login_result.failed
  changed_when: not podman_login_result.failed
  when: trilio_container_registry_login_enabled | bool

- name: Trilio - Ensure nbd module loads at boot
  become: true
  copy:
    dest: "/etc/modules-load.d/nbd.conf"
    content: "nbd"
    mode: "0644"

- name: Trilio - Ensure nbd module parameters persist
  become: true
  copy:
    dest: "/etc/modprobe.d/nbd.conf"
    content: "options nbd nbds_max=128"
    mode: "0644"


- name: Trilio - Load nbd module
  become: true
  modprobe:
    name: "nbd"
    params: "nbds_max=128"
    state: "present"

- name: Create common Trilio directories
  ansible.builtin.include_tasks: common.yml

- name: Configure and install triliovault DMS services
  ansible.builtin.include_tasks: configure_dms.yml

- name: Configure and install triliovault datamover service
  ansible.builtin.include_tasks: configure_datamover.yml

- name: Cleanup old backup target mounts and containers (upgrade from 6.0/6.1 to 6.2)
  ansible.builtin.include_tasks: cleanup_old_backup_targets.yml
  tags:
    - upgrade-and-clean-backup-target-mounts
    - never
