# Base Image for OpenStack Helm Bobcat (Ubuntu Jammy 2023.2)
FROM penstackhelm/nova:2023.2-ubuntu_jammy
MAINTAINER shyam.biradar@trilio.io

LABEL name="trilio/trilio-datamover" \
      version="6.0.1" \
      release="6.0" \
      vendor="TrilioData" \
      summary="TrilioData Datamover" \
      description="TrilioData Datamover container image for OpenStack Helm Bobcat 2023.2" \
      org.opencontainers.image.authors="shyam.biradar@trilio.io"

ARG UID=42424
ARG GID=42424
ARG PROJECT_DIR=trilio-datamover
ARG TRILIO_MOUNT_DIR=/var/trilio/triliovault-mounts
ARG OPENSTACK_REPO=cloud-archive:bobcat

# Switch to root and install required packages
USER root

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC

# Install pre-requisite packages
RUN set -ex \
    && apt-get update && apt-get -y install \
        software-properties-common apt-utils vim less iputils-ping

# Install datamover packages
COPY trilio.list /etc/apt/sources.list.d/

RUN set -ex \
    && apt-add-repository ${OPENSTACK_REPO} && apt-get update -y && apt-get -y --allow-unauthenticated install \
        python3-tvault-contego \
        python3-nova \
        fuse \
        python3-s3-fuse-plugin \
        nfs-common \
        udev

# Configuring the Nova user
COPY nova_userid.sh /opt/${PROJECT_DIR}/

# Set user/group IDs dynamically
RUN sed -i -r "s/^(user_id=).*/\1${UID}/" /opt/${PROJECT_DIR}/nova_userid.sh \
    && sed -i -r "s/^(group_id=).*/\1${GID}/" /opt/${PROJECT_DIR}/nova_userid.sh
RUN chmod +x /opt/${PROJECT_DIR}/nova_userid.sh && /opt/${PROJECT_DIR}/nova_userid.sh

# Set udev rules for RBD
RUN echo 'KERNEL=="rbd[0-9]*", PROGRAM="/usr/bin/ceph-rbdnamer %n", SYMLINK+="rbd/%c{1}/%c{2}"' > /etc/udev/rules.d/trilio-rbd.rules

# Copy configuration files
ADD nova-sudoers /etc/sudoers.d/nova-sudoers
ADD trilio.filters /usr/share/nova/rootwrap/trilio.filters
RUN usermod -aG disk nova \
    && usermod -aG kvm nova

RUN mkdir -p ${TRILIO_MOUNT_DIR} /var/triliovault /etc/${PROJECT_DIR} /opt/${PROJECT_DIR} /var/log/${PROJECT_DIR} /etc/triliovault-object-store \
    && chown nova.nova -R ${TRILIO_MOUNT_DIR} \
        /var/triliovault \
        /etc/${PROJECT_DIR} \
        /opt/${PROJECT_DIR} \
        /var/log/${PROJECT_DIR} \
        /etc/triliovault-object-store \
    && chmod 777 ${TRILIO_MOUNT_DIR} /var/triliovault

ADD log-rotate-conf /etc/logrotate.d/tvault-contego

# Add license directory
RUN mkdir /licenses

# Switch back to nova user
USER nova