FROM quay.io/openstack.kolla/nova-api:2024.1-ubuntu-jammy
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="sunbeam/trilio-datamover-api" \
      vendor="TrilioData" \
      version="6.2.0" \
      release="6.2" \
      summary="TrilioData Datamover API" \
      description="TrilioData Datamover API Image based on Ubuntu Jammy for Sunbeam Canonical OpenStack"

USER root

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Etc/UTC

RUN set -ex \
    && apt-get update && apt-get -y install \
        apt-utils \
        software-properties-common \
        ca-certificates \
        curl \
        vim \
        less \
        iputils-ping \
        python3-retrying \
        mysql-client \
        python3-openstackclient \
        apache2 \
        net-tools \
    && apt-get clean -y

ADD trilio.list /etc/apt/sources.list.d/

RUN apt-get update -y \
    && apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y python3-dmapi python3-trilio-dms python3-nova --allow-unauthenticated

RUN sed -i '/^Listen /c\Listen 8784' /etc/apache2/ports.conf \
    && chown -R dmapi:dmapi /var/log/apache2 /var/www /etc/apache2 /var/cache/apache2

RUN curl -o /usr/local/bin/rabbitmqadmin https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/v3.12.x/deps/rabbitmq_management/bin/rabbitmqadmin \
    && chmod +x /usr/local/bin/rabbitmqadmin

RUN mkdir -p /etc/triliovault-datamover /opt/triliovault-datamover /var/log/triliovault-datamover \
    && chown -R dmapi:dmapi /etc/triliovault-datamover /opt/triliovault-datamover /var/log/triliovault-datamover

RUN mkdir -p /licenses
COPY licensing.txt /licenses

RUN rm -f /etc/apt/sources.list.d/trilio.list

USER dmapi
