FROM registry.redhat.io/rhoso-beta/openstack-horizon-rhel9:18.0.0
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="6.0.0" \
      release="6.0" \
      summary="Red Hat OpenStack Platform 18 horizon TrilioData TrilioVault Horizon Plugin" \
      description="Red Hat OpenStack Platform 18 horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
RUN dnf clean all && dnf config-manager --set-disabled \*
ADD trilio.repo /etc/yum.repos.d/

RUN dnf config-manager \
  --enable rhel-9-for-x86_64-baseos-eus-rpms \
  --enable rhel-9-for-x86_64-appstream-eus-rpms \
  --enable rhel-9-for-x86_64-highavailability-eus-rpms \
  --enable fast-datapath-for-rhel-9-x86_64-rpms \
  --enable rhceph-7-tools-for-rhel-9-x86_64-rpms

ADD trilio.repo /etc/yum.repos.d/
RUN dnf install --releasever 9.4 python3-tvault-horizon-plugin-el9 -y
RUN dnf --releasever 9.4 -y update-minimal --security --sec-severity=Important --sec-severity=Critical
RUN rm /etc/yum.repos.d/trilio.repo

##Copy necessary files
RUN cp -r /usr/lib/python3.9/site-packages/trilio_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
RUN cp -r /usr/lib/python3.9/site-packages/trilio_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/

RUN /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/share/openstack-dashboard/manage.py compress --force

##Disable repos and Clean subscription
RUN dnf config-manager \
    --disable rhel-9-for-x86_64-baseos-eus-rpms \
    --disable rhel-9-for-x86_64-appstream-eus-rpms \
    --disable rhel-9-for-x86_64-highavailability-eus-rpms \
    --disable fast-datapath-for-rhel-9-x86_64-rpms \
    --disable rhceph-7-tools-for-rhel-9-x86_64-rpms
RUN dnf clean all

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
