FROM registry.redhat.io/rhosp-rhel8/openstack-horizon:16.1
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="5.0.X" \
      release="5.0" \
      summary="Red Hat OpenStack Platform 16.1 horizon TrilioData TrilioVault Horizon Plugin" \
      description="Red Hat OpenStack Platform 16.1 horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf install python3-tvault-horizon-plugin-el8 -y
RUN yum -y update-minimal --security --sec-severity=Important --sec-severity=Critical
RUN rm /etc/yum.repos.d/trilio.repo

##Copy necessary files
RUN cp -r /usr/lib/python3.6/site-packages/trilio_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
RUN cp -r /usr/lib/python3.6/site-packages/trilio_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/

RUN /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/share/openstack-dashboard/manage.py compress --force

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
