FROM registry.redhat.io/rhosp-rhel9/openstack-horizon:17.1
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="5.0.X" \
      release="5.0" \
      summary="Red Hat OpenStack Platform 16.2 horizon TrilioData TrilioVault Horizon Plugin" \
      description="Red Hat OpenStack Platform 16.2 horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
RUN dnf clean all

RUN dnf config-manager --set-disabled '*'

RUN dnf config-manager \
  --enable openstack-16.2-for-rhel-8-x86_64-rpms \
  --enable fast-datapath-for-rhel-8-x86_64-rpms \
  --enable rhel-8-for-x86_64-baseos-tus-rpms \
  --enable rhel-8-for-x86_64-appstream-tus-rpms \
  --enable advanced-virt-for-rhel-8-x86_64-rpms \
  --enable rhceph-4-tools-for-rhel-8-x86_64-rpms \
  --enable codeready-builder-for-rhel-8-x86_64-rpms

ADD trilio.repo /etc/yum.repos.d/
RUN dnf install --releasever 8.4 python3-tvault-horizon-plugin-el8 -y
RUN dnf --releasever 8.4 -y update-minimal --security --sec-severity=Important --sec-severity=Critical
RUN rm /etc/yum.repos.d/trilio.repo

##Copy necessary files
RUN cp -r /usr/lib/python3.6/site-packages/trilio_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
RUN cp -r /usr/lib/python3.6/site-packages/trilio_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/

RUN /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
RUN /usr/share/openstack-dashboard/manage.py compress --force



## Clean repos
RUN dnf clean all
RUN dnf config-manager \
  --disable openstack-16.2-for-rhel-8-x86_64-rpms \
  --disable advanced-virt-for-rhel-8-x86_64-rpms \
  --disable rhceph-4-tools-for-rhel-8-x86_64-rpms \
  --disable fast-datapath-for-rhel-8-x86_64-rpms \
  --disable rhel-8-for-x86_64-baseos-tus-rpms \
  --disable rhel-8-for-x86_64-appstream-tus-rpms \
  --disable codeready-builder-for-rhel-8-x86_64-rpms

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
