FROM docker.io/tripleorocky/centos-binary-horizon:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp14/openstack-horizon-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.0.0" \
      release="4.0" \
      summary="TripleO OpenStack Platform Rocky horizon TrilioData TrilioVault Horizon Plugin" \
      description="TripleO OpenStack Platform Rocky horizon TrilioData TrilioVault Horizon Plugin"

##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN yum-config-manager --save --setopt=delorean.skip_if_unavailable=true
RUN yum install tvault-horizon-plugin workloadmgrclient -y
RUN rm /etc/yum.repos.d/trilio.repo

##Move necessary files
ADD usr/share/openstack-dashboard/openstack_dashboard/local/enabled/* /usr/share/openstack-dashboard/openstack_dashboard/local/enabled/
ADD usr/share/openstack-dashboard/openstack_dashboard/templatetags/* /usr/share/openstack-dashboard/openstack_dashboard/templatetags/

## Add license
RUN mkdir /licenses
COPY licensing.txt /licenses
