apiVersion: v2
name: monitoring-stack
description: Monitoring Stack is designed to manage the Trilio for Openstack's Monitoring and Visualization.
type: application
version: 0.1.0
appVersion: "1.0"
home: https://docs.trilio.io/openstack
icon: https://asset.brandfetch.io/idGK8s6yAt/id71ulaWGz.jpeg
maintainers:
- name: Trilio Data, Inc
sources:
- https://github.com/trilioData/triliovault-cfg-scripts/

dependencies:
  - name: prometheus-openstack-exporter
    version: 0.4.3
    repository: "file://charts/prometheus-openstack-exporter"

