FROM registry.redhat.io/rhosp-rhel9/openstack-base:17.1
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="trilio/openstack-nova-api-triliodata-triliovault-wlm-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="5.2.0" \
      release="5.2" \
      summary="Red Hat OpenStack Platform 17.1 nova-api TrilioData TrilioVault WLM" \
      description="Red Hat OpenStack Platform 17.1 nova-api TrilioData TrilioVault WLM"

# switch to root and install a custom RPM, etc.
USER root

## Configure dnf repos
RUN dnf clean all && dnf config-manager --set-disabled \*
ADD trilio.repo /etc/yum.repos.d/

RUN dnf config-manager \
  --enable rhel-9-for-x86_64-baseos-eus-rpms \
  --enable rhel-9-for-x86_64-appstream-eus-rpms \
  --enable rhel-9-for-x86_64-highavailability-eus-rpms \
  --enable openstack-17.1-for-rhel-9-x86_64-rpms \
  --enable fast-datapath-for-rhel-9-x86_64-rpms \
  --enable rhceph-6-tools-for-rhel-9-x86_64-rpms \
  --enable codeready-builder-for-rhel-9-x86_64-rpms
  

## Epel repo is needed for ntfs-3g package
RUN dnf install --releasever 9.2 -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

## Install dependencies
RUN dnf --releasever 9.2 -y install openstack-nova-common python3-nova python3-novaclient udev \
  fuse python3-neutronclient python3-retrying python3-cryptography \
  python3-devel libxslt-devel swig python3-pip python3-glanceclient fuse-libs \
  pacemaker-remote resource-agents pcs

RUN pip3 install --upgrade pip && pip3 install igraph && pip3 install namedatomiclock

## Install Triliovault wlm packages
RUN dnf -y --releasever 9.2 install python3-workloadmgr-el9 python3-workloadmgrclient-el9  python3-contegoclient-el9 python3-s3fuse-plugin-el9


## Install important security patches
RUN dnf -y --releasever 9.2 update-minimal --security --sec-severity=Important --sec-severity=Critical --exclude=python3-libvirt --nobest


## Nova user changes
RUN usermod -u 42436 nova && groupmod -g 42436 nova && usermod -aG disk,kolla nova

##Copy conf files
RUN mkdir -p /etc/triliovault-object-store /etc/triliovault-wlm /var/log/triliovault /var/triliovault /var/lib/nova/triliovault-mounts \
    && chown -R nova:nova /etc/triliovault-wlm /etc/triliovault-object-store/ /var/lib/nova /var/log/triliovault /var/triliovault /var/lib/workloadmgr \
    && chmod -R 755 /var/lib/nova /var/lib/workloadmgr

##Disable repos and Clean subscription
RUN dnf config-manager \
  --disable rhel-9-for-x86_64-baseos-eus-rpms \
  --disable rhel-9-for-x86_64-appstream-eus-rpms \
  --disable rhel-9-for-x86_64-highavailability-eus-rpms \
  --disable openstack-17.1-for-rhel-9-x86_64-rpms \
  --disable fast-datapath-for-rhel-9-x86_64-rpms \
  --disable rhceph-6-tools-for-rhel-9-x86_64-rpms

RUN dnf clean all


##Add license
RUN mkdir /licenses
COPY licensing.txt /licenses


##Become nova user for further operations
USER nova
