---
- name: get virsh(virtual shell) version of host
  shell: virsh -v
  register: virsh_v

- name: check if virsh version is greater 1.2.8
  debug: msg="{{ virsh_v.stdout | version_compare(virsh_version, '>=')}}"
  register: is_condition_satisefied

- debug: msg="virsh version found {{virsh_v.stdout}} ,condition satisfied"
  when: is_condition_satisefied.msg == True

- fail: msg="ERROR :virsh version found {{virsh_v.stdout}} which is below expected 1.2.8, please upgrade virsh and try again."
  when:  is_condition_satisefied.msg == False

