FROM docker.io/tripleotraincentos8/centos-binary-nova-api:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="tripleo/centos-binary-nova-compute-triliodata" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="TripleO Train nova-api TrilioData trilio-datamover-api" \
      description="TripleO Train nova-api TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
RUN dnf clean all
ADD trilio.repo delorean-component-tripleo.repo /etc/yum.repos.d/
RUN dnf install -y python3-tripleo-repos
RUN tripleo-repos -b train current && tripleo-repos -b train current ceph
RUN sed -i 's#baseurl.*#baseurl=http://mirror.centos.org/centos-8/8/storage/x86_64/ceph-nautilus/#g' /etc/yum.repos.d/tripleo-centos-ceph-nautilus.repo

RUN dnf install python3-dmapi -y
RUN  rm -f /etc/yum.repos.d/trilio.repo
RUN usermod -a -G kolla dmapi
RUN dnf clean all

#Copy executable files
RUN mkdir -p /opt/tvault/
ADD start_datamover_api_tripleo_centos8  /opt/tvault/start_datamover_api
RUN chown -R nova:nova /opt/tvault/
RUN chmod 755 /opt/tvault/start_datamover_api


##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi
