FROM docker.io/tripleotraincentos8/centos-binary-nova-api:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp16/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.0.0" \
      release="4.0" \
      summary="Red Hat OpenStack Platform 16.0 nova-api TrilioData trilio-datamover-api" \
      description="Red Hat OpenStack Platform 16.0 nova-api TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
RUN dnf clean all
ADD trilio.repo delorean-component-tripleo.repo /etc/yum.repos.d/
RUN dnf install -y python3-tripleo-repos
RUN tripleo-repos -b train --no-stream current && tripleo-repos -b train --no-stream current ceph


RUN dnf install python3-dmapi -y
RUN  rm -f /etc/yum.repos.d/trilio.repo
RUN usermod -a -G kolla dmapi
RUN dnf clean all

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi
