FROM docker.io/tripleotrain/centos-binary-nova-api:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="tripleo/centos-binary-nova-compute-triliodata" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.1.0" \
      release="4.1" \
      summary="TripleO Train nova-compute plugin TrilioData Datamover" \
      description="TripleO Train nova-compute plugin TrilioData Datamover"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
RUN yum clean all && yum-config-manager --save --setopt=delorean.skip_if_unavailable=true
ADD trilio.repo /etc/yum.repos.d/
RUN yum install dmapi -y
RUN  rm -f /etc/yum.repos.d/trilio.repo
RUN usermod -a -G kolla dmapi
RUN yum clean all

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi
