FROM docker.io/tripleowallaby/openstack-nova-api:current-tripleo-rdo
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="tripleo/openstack-nova-api-triliodata" \
      maintainer="shyam.biradar@trilio.io" \ 
      vendor="TrilioData" \
      version="4.2.0" \
      release="4.2" \
      summary="TripleO Wallaby nova-api TrilioData trilio-datamover-api" \
      description="TripleO Wallaby nova-api TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
RUN dnf clean all
ADD trilio.repo delorean-component-tripleo.repo /etc/yum.repos.d/
ADD centos-gpg-keys-8-4.el8.noarch.rpm centos-stream-repos-8-4.el8.noarch.rpm /root/
RUN rpm -ivh centos-stream-repos-8-4.el8.noarch.rpm centos-gpg-keys-8-4.el8.noarch.rpm
RUN rm -f centos-gpg-keys-8-4.el8.noarch.rpm centos-gpg-keys-8-4.el8.noarch.rpm
RUN dnf install -y python3-tripleo-repos
RUN tripleo-repos -b wallaby current ceph


RUN dnf install python3-dmapi -y
RUN  rm -f /etc/yum.repos.d/trilio.repo
RUN usermod -a -G kolla dmapi
RUN dnf clean all

#Copy executable files
RUN mkdir -p /opt/tvault/
ADD start_datamover_api_tripleo_centos8  /opt/tvault/start_datamover_api
RUN chown -R nova:nova /opt/tvault/
RUN chmod 755 /opt/tvault/start_datamover_api


##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER dmapi