FROM registry.redhat.io/rhosp-rhel8/openstack-nova-api:16.1
MAINTAINER TrilioData shyam.biradar@trilio.io

LABEL name="rhosp16/openstack-nova-api-triliodata-plugin" \
      maintainer="shyam.biradar@trilio.io" \
      vendor="TrilioData" \
      version="4.0.0" \
      release="4.0" \
      summary="Red Hat OpenStack Platform 16.1 nova-api TrilioData trilio-datamover-api" \
      description="Red Hat OpenStack Platform 16.1 nova-api TrilioData trilio-datamover-api"


# switch to root and install a custom RPM, etc.
USER root


##Install datamover packages
ADD trilio.repo /etc/yum.repos.d/
RUN dnf install python3-dmapi -y
RUN mkdir -p /var/log/trilio-datamover-api
RUN chown -R nova:nova /var/log/trilio-datamover-api/
RUN mkdir -p /var/cache/dmapi/
RUN chown nova:nova /var/cache/dmapi/
RUN rm -f /etc/yum.repos.d/trilio.repo

##Copy license file
RUN mkdir /licenses
COPY licensing.txt /licenses

##Become nova user for further operations
USER nova
