---
- name: Deploy tvault-contego.conf
  ansible.builtin.template:
    src: triliovault_datamover_conf.j2
    dest: "{{ trilio_datamover_conf }}"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart tvault-contego

- name: Deploy tvault-contego logging config
  ansible.builtin.template:
    src: datamover_logging_conf.j2
    dest: "{{ trilio_log_conf }}"
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart tvault-contego
