---
- name: Install TrilioVault DataMover
  ansible.builtin.import_tasks: install.yml
  tags: [trilio, trilio-install]

- name: Configure TrilioVault DataMover
  ansible.builtin.import_tasks: configure.yml
  tags: [trilio, trilio-configure]

- name: Manage TrilioVault DataMover service
  ansible.builtin.import_tasks: service.yml
  tags: [trilio, trilio-service]
