apiVersion: v2
appVersion: 6.1.5
description: Trilio Backup Targets for OpenStack Helm Chart for Kubernetes
home: https://docs.trilio.io/openstack
icon: https://asset.brandfetch.io/idGK8s6yAt/id71ulaWGz.jpeg
maintainers:
- name: Trilio Data, Inc
name: trilio-backup-targets
sources:
- https://github.com/trilioData/triliovault-cfg-scripts/
type: application
version: 6.1.5
