[client]
rabbitmq_url = {{ rabbitmq_url }}

db_url = {{ db_url }}

request_timeout = 60
log_level = INFO
log_file = /var/log/triliovault/trilio-dms-client.log
log_max_bytes = 26214400
log_backup_count = 5
db_pool_size = 20
db_max_overflow = 40
db_pool_recycle = 3600
