{{- if eq .Values.triliovault_backup_target.backup_target_type "s3" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: triliovault-object-store-bin
data:
  triliovault-object-store.sh: |
    {{ tpl (.Files.Get "scripts/_triliovault-object-store.sh.tpl") . | nindent 4 }}
{{- end }}
