apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-exporter-config
  namespace: openshift-user-workload-monitoring
data:
  config.yml: |
    global:
      scrape_timeout: 10s
      scrape_timeout_offset: 500ms
      min_interval: 0s
      max_connections: 3
      max_idle_connections: 3

    target:
      data_source_name: "mysql://$DB_USER_NAME:$DB_PASSWORD@DB_HOST_NAME:3306/workloadmgr"
      collectors: [mysql_workloads]

    collectors:
      - collector_name: mysql_workloads
        metrics:
          - metric_name: mysql_trilio_snapshots_info
            type: counter
            help: "Snapshot ID and Project from the snapshot table"
            key_labels:
              - ProjectID
              - status
            values:
              - count
            query: |
              SELECT
                project_id AS ProjectID,
                'successful' AS status, SUM(CASE WHEN status = 'available' THEN 1 ELSE 0 END) AS count
              FROM workloadmgr.snapshots
              GROUP BY project_id
              UNION ALL
              SELECT
                project_id AS ProjectID,
                'failed' AS status, SUM(CASE WHEN status = 'error' THEN 1 ELSE 0 END) AS count
              FROM workloadmgr.snapshots
              GROUP BY project_id
              UNION ALL
              SELECT
                project_id AS ProjectID,
                'running' AS status, SUM(CASE WHEN status IN ('executing', 'wait_to_be_uploading', 'uploading') THEN 1 ELSE 0 END) AS count
              FROM workloadmgr.snapshots
              GROUP BY project_id;

          - metric_name: mysql_trilio_restore_info
            type: gauge
            help: "Snapshot ID and Project from the restore table"
            key_labels:
              - ProjectID
              - status
            values:
              - count
            query: |
              SELECT
                project_id AS ProjectID,
                'successful' AS status, SUM(CASE WHEN status = 'available' THEN 1 ELSE 0 END) AS count
              FROM workloadmgr.restores
              GROUP BY project_id
              UNION ALL
              SELECT
                project_id AS ProjectID,
                'failed' AS status, SUM(CASE WHEN status = 'error' THEN 1 ELSE 0 END) AS count
              FROM workloadmgr.restores
              GROUP BY project_id
              UNION ALL
              SELECT
                project_id AS ProjectID,
                'running' AS status, SUM(CASE WHEN status IN ('executing', 'wait_to_be_uploading', 'uploading') THEN 1 ELSE 0 END) AS count
              FROM workloadmgr.restores
              GROUP BY project_id;

          - metric_name: openstack_protected_vm
            help: "Count of unique protected VMs in workload_vms per project"
            type: gauge
            values:
              - protected_vm_count
            key_labels:
              - ProjectID
            query: |
              SELECT
                w.project_id AS ProjectID,
                COUNT(DISTINCT wv.vm_id) AS protected_vm_count
              FROM workload_vms wv
              JOIN workloads w ON wv.workload_id = w.id
              WHERE w.deleted = 0 AND wv.deleted = 0
              GROUP BY w.project_id;

          - metric_name: mysql_trilio_backup_size_info_total_size
            type: gauge
            help: "Total backup size per project"
            values:
              - total_size
            key_labels:
              - ProjectID
            query: |
              SELECT
                project_id AS ProjectID,
                SUM(size) / 1073741824 AS total_size
              FROM workloadmgr.snapshots
              GROUP BY project_id;

          - metric_name: mysql_trilio_backup_size_info_total_snapshots
            type: gauge
            help: "Total number of snapshots per project"
            values:
              - total_snapshots
            key_labels:
              - ProjectID
            query: |
              SELECT
                project_id AS ProjectID,
                COUNT(id) AS total_snapshots
              FROM workloadmgr.snapshots
              GROUP BY project_id;

          - metric_name: mysql_trilio_backup_size_info_total_restore_size
            type: gauge
            help: "Total restore size per project"
            values:
              - total_restore_size
            key_labels:
              - ProjectID
            query: |
              SELECT
                project_id AS ProjectID,
                SUM(restore_size) / 1073741824 AS total_restore_size
              FROM workloadmgr.snapshots
              GROUP BY project_id;

          - metric_name: mysql_trilio_backup_size_info_total_uploaded_size
            type: gauge
            help: "Total uploaded size per project"
            values:
              - total_uploaded_size
            key_labels:
              - ProjectID
            query: |
              SELECT
                project_id AS ProjectID,
                SUM(uploaded_size) / 1073741824 AS total_uploaded_size
              FROM workloadmgr.snapshots
              GROUP BY project_id;

          - metric_name: mysql_trilio_snapshots_status
            type: counter
            help: "Snapshot details (ID, name, workload) and status from the snapshot table"
            key_labels:
              - ProjectID
              - WorkloadID
              - SnapshotID
              - SnapshotName
              - status
            values:
              - count
            query: |
              SELECT
                  project_id AS ProjectID,
                  workload_id AS WorkloadID,
                  id AS SnapshotID,
                  display_name AS SnapshotName,
                  'successful' AS status,
                  COUNT(*) AS count
              FROM workloadmgr.snapshots
              WHERE status = 'available'
              GROUP BY project_id, workload_id, id, display_name
              UNION ALL
              SELECT
                  project_id AS ProjectID,
                  workload_id AS WorkloadID,
                  id AS SnapshotID,
                  display_name AS SnapshotName,
                  'failed' AS status,
                  COUNT(*) AS count
              FROM workloadmgr.snapshots
              WHERE status = 'error'
              GROUP BY project_id, workload_id, id, display_name
              UNION ALL
              SELECT
                  project_id AS ProjectID,
                  workload_id AS WorkloadID,
                  id AS SnapshotID,
                  display_name AS SnapshotName,
                  'running' AS status,
                  COUNT(*) AS count
              FROM workloadmgr.snapshots
              WHERE status IN ('executing', 'wait_to_be_uploading', 'uploading')
              GROUP BY project_id, workload_id, id, display_name;