apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sql-exporter
  namespace: trilio-monitoring
  labels:
    release: prometheus-user-workload
spec:
  selector:
    matchLabels:
      app: sql-exporter
  namespaceSelector:
    matchNames:
      - trilio-monitoring
  endpoints:
    - port: metrics
      interval: 30s

