apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliovault-wlm-workloads
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
    component: wlm-workloads
spec:
  replicas: {{ .Values.pod.replicas.triliovault_wlm_workloads }}
  selector:
    matchLabels:
      application: triliovault
      component: wlm-workloads
  template:
    metadata:
      labels:
        application: triliovault
        component: wlm-workloads
    spec:
      serviceAccountName: triliovault-wlm
      {{- include "tvo.imagePullSecrets" . | nindent 6 }}
      nodeSelector:
        {{ .Values.labels.wlm_workloads.node_selector_key }}: {{ .Values.labels.wlm_workloads.node_selector_value }}
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      containers:
        - name: triliovault-wlm-workloads
          image: {{ .Values.images.triliovault_wlm }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command: ["/bin/bash", "-c", "workloadmgr-workloads --config-file /etc/triliovault-wlm/triliovault-wlm.conf"]
          {{- if .Values.tls.ca_bundle_configmap }}
          env:
            {{- include "tvo.caBundleEnv" . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: wlm-etc
              mountPath: /etc/triliovault-wlm/triliovault-wlm.conf
              subPath: triliovault-wlm.conf
              readOnly: true
            - name: trilio-logs
              mountPath: /var/log/triliovault
            - name: trilio-mounts
              mountPath: {{ .Values.common.vault_data_dir }}
              mountPropagation: Bidirectional
            {{- include "tvo.caBundleVolumeMount" . | nindent 12 }}
      volumes:
        - name: wlm-etc
          secret:
            secretName: triliovault-wlm-etc
            defaultMode: 0444
        - name: trilio-logs
          emptyDir: {}
        - name: trilio-mounts
          hostPath:
            path: {{ .Values.common.vault_data_dir }}
            type: DirectoryOrCreate
        {{- include "tvo.caBundleVolume" . | nindent 8 }}
