apiVersion: apps/v1
kind: Deployment
metadata:
  name: triliovault-wlm-scheduler
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
    component: wlm-scheduler
spec:
  replicas: {{ .Values.pod.replicas.triliovault_wlm_scheduler }}
  selector:
    matchLabels:
      application: triliovault
      component: wlm-scheduler
  template:
    metadata:
      labels:
        application: triliovault
        component: wlm-scheduler
    spec:
      serviceAccountName: triliovault-wlm
      {{- include "tvo.imagePullSecrets" . | nindent 6 }}
      nodeSelector:
        {{ .Values.labels.wlm_scheduler.node_selector_key }}: {{ .Values.labels.wlm_scheduler.node_selector_value }}
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      containers:
        - name: triliovault-wlm-scheduler
          image: {{ .Values.images.triliovault_wlm }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command: ["/bin/bash", "-c", "workloadmgr-scheduler --config-file /etc/triliovault-wlm/triliovault-wlm.conf"]
          volumeMounts:
            - name: wlm-etc
              mountPath: /etc/triliovault-wlm/triliovault-wlm.conf
              subPath: triliovault-wlm.conf
              readOnly: true
            - name: trilio-logs
              mountPath: /var/log/triliovault
      volumes:
        - name: wlm-etc
          secret:
            secretName: triliovault-wlm-etc
            defaultMode: 0444
        - name: trilio-logs
          emptyDir: {}
