apiVersion: batch/v1
kind: Job
metadata:
  name: triliovault-wlm-db-init
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
    component: wlm-db-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        application: triliovault
        component: wlm-db-init
    spec:
      restartPolicy: OnFailure
      serviceAccountName: triliovault-wlm
      {{- include "tvo.imagePullSecrets" . | nindent 6 }}
      nodeSelector:
        {{ .Values.labels.job.node_selector_key }}: {{ .Values.labels.job.node_selector_value }}
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      containers:
        - name: wlm-db-init
          image: {{ .Values.images.triliovault_wlm }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command: ["/bin/bash", "/tmp/bin/wlm-db-init.sh"]
          volumeMounts:
            - name: wlm-etc
              mountPath: /etc/triliovault-wlm/triliovault-wlm.conf
              subPath: triliovault-wlm.conf
              readOnly: true
            - name: wlm-bin
              mountPath: /tmp/bin
              readOnly: true
      volumes:
        - name: wlm-etc
          secret:
            secretName: triliovault-wlm-etc
            defaultMode: 0444
        - name: wlm-bin
          configMap:
            name: triliovault-wlm-bin
            defaultMode: 0555
