apiVersion: v1
kind: Secret
metadata:
  name: triliovault-wlm-etc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
type: Opaque
stringData:
  triliovault-wlm.conf: |
    [DEFAULT]
    auth_uri = {{ .Values.keystone.auth_url }}
    auth_url = {{ .Values.keystone.auth_url }}
    region_name = {{ .Values.keystone.region_name }}
    log_dir = /var/log/triliovault
    log_file = workloadmgr-api.log

    [keystone_authtoken]
    auth_uri = {{ .Values.keystone.auth_url }}
    auth_url = {{ .Values.keystone.auth_url }}
    auth_type = password
    project_domain_name = {{ .Values.keystone.service_project_domain }}
    user_domain_name = {{ .Values.keystone.service_project_domain }}
    project_name = {{ .Values.keystone.service_project_name }}
    username = {{ .Values.keystone.wlm_api.user }}
    password = {{ .Values.keystone.wlm_api.password }}
    {{- if .Values.tls.ca_bundle_configmap }}
    insecure = false
    cafile = /etc/ssl/certs/sunbeam-ca.crt
    {{- else }}
    insecure = {{ not .Values.keystone.ssl_verify }}
    {{- end }}

    [database]
    connection = mysql+pymysql://{{ .Values.database.wlm_api.user }}:{{ .Values.database.wlm_api.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.wlm_api.database }}

    [oslo_messaging_rabbit]
    rabbit_hosts = {{ .Values.rabbitmq.host }}:{{ .Values.rabbitmq.port }}
    rabbit_userid = {{ .Values.rabbitmq.wlm_api.user }}
    rabbit_password = {{ .Values.rabbitmq.wlm_api.password }}
    rabbit_virtual_host = {{ .Values.rabbitmq.wlm_api.vhost }}
    rabbit_use_ssl = {{ .Values.rabbitmq.ssl }}

    [vault]
    vault_data_dir = {{ .Values.common.vault_data_dir }}
    vault_auth = keystone
