apiVersion: v1
kind: Service
metadata:
  name: trilio-wlm-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
    component: wlm-api
spec:
  type: {{ .Values.service.wlm_api.type }}
  selector:
    application: triliovault
    component: wlm-api
  ports:
    - name: wlm-api
      protocol: TCP
      port: {{ .Values.service.wlm_api.port }}
      targetPort: 8781
      {{- if eq .Values.service.wlm_api.type "NodePort" }}
      nodePort: {{ .Values.service.wlm_api.node_port }}
      {{- end }}
