apiVersion: v1
kind: ServiceAccount
metadata:
  name: triliovault-wlm
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "tvo.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: triliovault-wlm
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-wlm
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: triliovault-wlm
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: triliovault-wlm
  apiGroup: rbac.authorization.k8s.io
